/* A local media advert, separate from financial records and portable with the full backup. */
(function(){
'use strict';
let draft=null,previewUrl='',bannerUrl='',loadVersion=0,saving=false;
const types=new Set(['image/jpeg','image/png','image/gif','image/webp','image/avif','video/mp4','video/webm','video/quicktime']);
function mediaType(file){const guessed={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',gif:'image/gif',webp:'image/webp',avif:'image/avif',mp4:'video/mp4',webm:'video/webm',mov:'video/quicktime'}[String(file.name).split('.').pop().toLowerCase()];return types.has(file.type)?file.type:(!file.type||file.type==='application/octet-stream')?guessed:''}
function safeLink(value){if(!value.trim())return '';let url;try{url=new URL(value.trim())}catch{throw Error('لینک را کامل با https:// وارد کن')}if(!['https:','http:'].includes(url.protocol)||url.username||url.password)throw Error('لینک معتبر http یا https وارد کن');return url.href}
function markup(ad){let link='';try{link=safeLink(ad?.link||'')}catch{}return `<aside class="dashboard-ad advert-card" aria-label="تبلیغات"><div class="advert-heading"><span>معرفی خدمات / تبلیغات</span><button class="btn" onclick="openAdvertisement()">${ad?'✎ ویرایش تبلیغ':'＋ افزودن تبلیغ'}</button></div>${ad?.enabled?`<div id="advertMedia" data-ad-file="${esc(ad.fileId||'')}" class="advert-media">${ad.fileId?'در حال آماده‌سازی تصویر یا ویدئو…':'عکس، GIF یا فیلم به تبلیغ اضافه کن.'}</div><div class="advert-copy"><strong>${esc(ad.title||'معرفی خدمات')}</strong>${ad.description?`<p>${esc(ad.description)}</p>`:''}${link?`<a class="btn" href="${esc(link)}" target="_blank" rel="noopener noreferrer">${esc(ad.linkLabel||'مشاهده بیشتر')} ↗</a>`:''}</div>`:`<p>${ad?'تبلیغ فعلاً مخفی است.':'عکس، GIF متحرک یا ویدئوی خدماتت را اینجا قرار بده.'}</p>`}</aside>`}
function putMedia(box,file,url){box.replaceChildren();if(mediaType(file)?.startsWith('video/')){const video=document.createElement('video');video.src=url;video.controls=true;video.playsInline=true;video.preload='metadata';video.setAttribute('aria-label','ویدئوی تبلیغ');box.append(video);const hint=document.createElement('small');hint.textContent='برای پخش و صدا، دکمهٔ پخش را بزن.';box.append(hint)}else{const img=document.createElement('img');img.src=url;img.alt=db.advertisement?.title||'پیش‌نمایش تبلیغ';box.append(img)}}
async function hydrate(){const version=++loadVersion;if(bannerUrl){URL.revokeObjectURL(bannerUrl);bannerUrl=''}const box=document.getElementById('advertMedia'),id=box?.dataset.adFile;if(!box||!id)return;let file;try{file=memoryFiles.get(id)||await readFile(id)}catch{}if(version!==loadVersion||!box.isConnected)return;if(!file?.blob){box.textContent='فایل تبلیغ در این مرورگر پیدا نشد؛ از ویرایش تبلیغ دوباره انتخاب کن.';return}bannerUrl=URL.createObjectURL(file.blob);putMedia(box,{type:file.type,name:file.name},bannerUrl)}
window.closeAdvertisement=function(){if(saving)return;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl='';draft=null;document.getElementById('advertEditor')?.remove()};
window.openAdvertisement=function(){if(saving)return;closeAdvertisement();draft=null;const a=db.advertisement||{};document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="advertEditor"><div class="dialog" role="dialog" aria-modal="true" aria-label="مدیریت تبلیغات"><div class="dialog-head"><h2>افزودن / ویرایش تبلیغ</h2><button class="close" onclick="closeAdvertisement()">×</button></div><div class="field"><label for="adFile">عکس، GIF متحرک یا ویدئو</label><input type="file" id="adFile" accept="image/jpeg,image/png,image/gif,image/webp,image/avif,video/mp4,video/webm,video/quicktime,.mov" onchange="previewAdvertisement(this)"><small>تا ۵۰ مگابایت؛ برای فیلم روی گوشی MP4 مناسب‌تر است.</small></div><div id="advertPreview" class="advert-media">${a.fileId?'فایل فعلی حفظ می‌شود؛ برای تعویض، فایل جدید انتخاب کن.':'پیش‌نمایش فایل انتخابی اینجا نمایش داده می‌شود.'}</div><div class="form-grid">${field('عنوان تبلیغ',`<input id="adTitle" value="${esc(a.title||'')}">`)}${field('توضیحات',`<textarea id="adDescription">${esc(a.description||'')}</textarea>`)}${field('لینک مقصد (اختیاری)',`<input id="adLink" dir="ltr" value="${esc(a.link||'')}" placeholder="https://...">`)}${field('متن دکمهٔ لینک',`<input id="adLinkLabel" value="${esc(a.linkLabel||'مشاهده بیشتر')}">`)}</div><label><input type="checkbox" id="adEnabled" ${a.enabled!==false?'checked':''}> نمایش تبلیغ در داشبورد</label><p>فایل در همین مرورگر ذخیره می‌شود و با پشتیبان کامل قابل انتقال است.</p><div class="dialog-actions"><button class="btn primary" id="adSave" onclick="saveAdvertisement()">ذخیره تبلیغ</button>${a.fileId?'<button class="btn" onclick="hideAdvertisement()">مخفی‌کردن تبلیغ</button>':''}<button class="btn" onclick="closeAdvertisement()">انصراف</button></div><p id="adStatus" role="status"></p></div></div>`)};
const status=message=>{const node=document.getElementById('adStatus');if(node)node.textContent=message};
window.previewAdvertisement=function(input){const file=input.files?.[0];if(!file)return;if(!mediaType(file)||!file.size||file.size>50*1024*1024){input.value='';return status('عکس، GIF یا ویدئوی معتبر تا ۵۰ مگابایت انتخاب کن')}if(previewUrl)URL.revokeObjectURL(previewUrl);draft=file;previewUrl=URL.createObjectURL(file);putMedia(document.getElementById('advertPreview'),file,previewUrl);status('پیش‌نمایش آماده است؛ برای ثبت، ذخیره تبلیغ را بزن.')};
window.saveAdvertisement=async function(){if(saving)return;let link;try{link=safeLink(v('adLink'))}catch(e){return status(e.message)}const previous=db.advertisement;if(!draft&&!previous?.fileId)return status('ابتدا عکس، GIF یا ویدئو انتخاب کن');const title=v('adTitle');if(!title)return status('عنوان تبلیغ را وارد کن');const candidate={title,description:v('adDescription'),link,linkLabel:v('adLinkLabel')||'مشاهده بیشتر',enabled:document.getElementById('adEnabled').checked,fileId:previous?.fileId||'',name:previous?.name||'',type:previous?.type||'',updatedAt:new Date().toISOString()},file=draft;const button=document.getElementById('adSave');saving=true;button.disabled=true;status('در حال ذخیره…');
try{if(file){candidate.fileId='advert-'+crypto.randomUUID();candidate.name=file.name;candidate.type=mediaType(file);await storeFile(candidate.fileId,file)}db.advertisement=candidate;try{save()}catch(error){if(previous===undefined)delete db.advertisement;else db.advertisement=previous;throw error}if(file)memoryFiles.set(candidate.fileId,{id:candidate.fileId,blob:file,type:candidate.type,name:file.name});saving=false;closeAdvertisement();render();toast('تبلیغ ذخیره شد')}catch(error){saving=false;if(button.isConnected)button.disabled=false;status('تبلیغ ذخیره نشد؛ فایل و اطلاعات قبلی حفظ شده‌اند. دوباره تلاش کن.')}};
window.hideAdvertisement=function(){const a=db.advertisement;if(!a)return;const previous=a.enabled;a.enabled=false;try{save()}catch{a.enabled=previous;return status('تغییر ذخیره نشد؛ دوباره تلاش کن')}closeAdvertisement();render();toast('تبلیغ مخفی شد؛ فایل برای استفادهٔ دوباره حفظ شده است')};
const baseDashboard=dashboard;dashboard=function(){const holder=document.createElement('div');holder.innerHTML=baseDashboard();const slot=holder.querySelector('.dashboard-ad');if(slot)slot.outerHTML=markup(db.advertisement);return holder.innerHTML};
const baseSettings=settings;settings=function(){const html=baseSettings();return html.replace('</main>','<section class="card"><h3>تبلیغات و معرفی خدمات</h3><p>عکس، GIF یا فیلم جایگاه داشبورد را انتخاب یا تعویض کن.</p><button class="btn primary" onclick="openAdvertisement()">مدیریت تبلیغات</button></section></main>')};
const baseRender=render;render=function(...args){const result=baseRender(...args);hydrate();return result};
const css=document.createElement('style');css.textContent='.dashboard-ad.advert-card{display:block;height:auto;min-height:0;padding:16px;text-align:right;border:1px solid #dce5dc;border-radius:18px;background:#fff;color:#17362f}.advert-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.advert-heading>span{font-size:12px;color:#748477}.advert-heading .btn{font-size:12px}.advert-media{border-radius:14px;overflow:hidden;background:#f0f4ed;text-align:center;padding:12px}.advert-media img,.advert-media video{width:100%;max-height:340px;object-fit:contain;display:block;border-radius:12px}.advert-media small{display:block;margin-top:8px;color:#738176}.advert-copy{padding-top:14px}.advert-copy strong{font-size:18px}.advert-copy p{white-space:pre-wrap;line-height:1.8}.advert-copy .btn{display:inline-block;margin-top:10px}';document.head.append(css);
window.PeymanyarAdvertisement={mediaType,safeLink,hydrate};render();
})();
