const STORAGE='peymanyar-v1-data';
const fa=n=>new Intl.NumberFormat('fa-IR').format(Number(n||0));
const money=n=>`${fa(n)} تومان`;
const uid=()=>Date.now()+Math.floor(Math.random()*1000);
const todayFa=()=>new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const seed={
 projects:[],
 people:[],
 transactions:[],
 contracts:[],
 daily:[],
 documents:[]
};
let db=load();db.categories=Array.isArray(db.categories)?db.categories:[];let page='dashboard';let filter='';
function load(){try{return JSON.parse(localStorage.getItem(STORAGE))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(db))}
function icon(name){return ({dashboard:'⌂',projects:'▦',finance:'◉',people:'♙',contracts:'▤',daily:'☷',documents:'◫',settings:'⚙'}[name]||'•')}
const navItems=[['dashboard','داشبورد'],['projects','پروژه‌ها'],['finance','امور مالی'],['people','افراد و پیمانکاران'],['contracts','قراردادها'],['daily','گزارش روزانه'],['documents','اسناد و فاکتورها'],['settings','تنظیمات']];
function navButton(p,label,mobile=false){return `<button class="${page===p?'active':''}" onclick="go('${p}')"><span class="${mobile?'':'icon'}">${icon(p)}</span>${mobile?`<span>${label}</span>`:label}</button>`}
function layout(body,title,sub='مدیریت یکپارچه پروژه‌های ساختمانی'){
 return `<div class="app"><aside class="sidebar"><div class="brand"><div class="brand-mark">پ</div><div><strong>پیمان‌یار</strong><small>دفتر معماری و اجرا</small></div></div><nav class="menu">${navItems.map(x=>navButton(...x)).join('')}</nav><div class="side-foot">اطلاعات این نسخه روی همین دستگاه ذخیره می‌شود.<br>نسخه آزمایشی حرفه‌ای ۱.۰</div></aside><div class="main"><header class="topbar"><div class="page-title"><h1>${title}</h1><span>${sub}</span></div><div class="top-actions"><button class="icon-btn hide-mobile" onclick="openQuick()" aria-label="ثبت سریع">＋</button><button class="icon-btn hide-mobile" onclick="window.print()" aria-label="چاپ">⎙</button><div class="avatar">م</div></div></header><main class="content">${body}</main></div><button class="fab" onclick="openQuick()" aria-label="ثبت سریع">＋</button><nav class="mobile-nav">${[['dashboard','خانه'],['projects','پروژه'],['finance','مالی'],['people','افراد'],['daily','گزارش']].map(x=>navButton(x[0],x[1],true)).join('')}</nav></div>`
}
function totals(){return {expense:db.transactions.filter(x=>x.kind==='expense').reduce((s,x)=>s+x.amount,0),income:db.transactions.filter(x=>x.kind==='income').reduce((s,x)=>s+x.amount,0)}}
function projectRow(p){return `<div class="project-row"><div class="row-top"><strong>${p.name}</strong><span class="pill ${p.status==='متوقف'?'paused':''}">${p.status}</span></div><div class="progress"><i style="width:${Math.min(p.progress,100)}%"></i></div><div class="project-meta"><span>${fa(p.progress)}٪ پیشرفت</span><span>${p.client}</span><span>${p.location||'—'}</span><span>${money(p.budget)}</span></div></div>`}
function activityRow(x){return `<div class="activity-item"><div class="activity-icon">${x.kind==='income'?'↙':'↗'}</div><div><strong>${x.category}</strong><small>${x.project} • ${x.party} • ${x.date}</small></div><span class="amount ${x.kind==='expense'?'out':''}">${x.kind==='income'?'+':'−'} ${money(x.amount)}</span></div>`}
function projects(){const rows=db.projects.filter(x=>x.name.includes(filter)||x.client.includes(filter));return layout(`<div class="section-head"><div><h2>پروژه‌ها</h2><p>پیشرفت فیزیکی، بودجه و مشخصات کارفرما</p></div><div class="toolbar"><input class="search" placeholder="جست‌وجوی پروژه" value="${filter}" oninput="filter=this.value;render()"><button class="btn primary" onclick="openForm('project')">پروژه جدید</button></div></div><div class="cards-grid">${rows.map(p=>`<article class="card"><div class="row-top"><h3>${p.name}</h3><span class="pill">${p.status}</span></div><p style="color:var(--muted)">${p.client} • ${p.location||'بدون موقعیت'}</p><div class="progress"><i style="width:${p.progress}%"></i></div><div class="split"><span>${fa(p.progress)}٪</span><strong>${money(p.budget)}</strong></div></article>`).join('')||empty()}</div>`,'پروژه‌ها')}
function finance(){const t=totals();const rows=db.transactions.filter(x=>[x.project,x.party,x.category].some(v=>(v||'').includes(filter)));return layout(`<div class="section-head"><div><h2>امور مالی</h2><p>پرداخت، هزینه، خرید مصالح و دریافتی کارفرما</p></div><div class="toolbar"><input class="search" placeholder="جست‌وجو در تراکنش‌ها" value="${filter}" oninput="filter=this.value;render()"><button class="btn" onclick="exportCSV()">خروجی Excel</button><button class="btn primary" onclick="openForm('transaction')">ثبت تراکنش</button></div></div><div class="kpi-row" style="margin-bottom:14px"><div class="kpi"><small>دریافتی</small><strong>${money(t.income)}</strong></div><div class="kpi"><small>پرداختی</small><strong>${money(t.expense)}</strong></div><div class="kpi"><small>تراز ثبت‌شده</small><strong>${money(t.income-t.expense)}</strong></div></div><div class="card table-wrap"><table class="table"><thead><tr><th>تاریخ</th><th>پروژه</th><th>طرف حساب</th><th>دسته‌بندی</th><th>نوع</th><th>مبلغ</th></tr></thead><tbody>${rows.slice().reverse().map(x=>`<tr><td>${x.date}</td><td>${x.project}</td><td>${x.party}</td><td>${x.category}</td><td><span class="pill ${x.kind==='expense'?'paused':''}">${x.kind==='income'?'دریافت':'پرداخت'}</span></td><td class="amount ${x.kind==='expense'?'out':''}">${money(x.amount)}</td></tr>`).join('')}</tbody></table>${rows.length?'':empty()}</div>`,'امور مالی')}
function people(){const rows=db.people.filter(x=>[x.name,x.role,x.project].some(v=>(v||'').includes(filter)));return layout(`<div class="section-head"><div><h2>افراد و پیمانکاران</h2><p>پرونده، تخصص و حساب تفصیلی هر شخص</p></div><div class="toolbar"><input class="search" placeholder="نام یا تخصص" value="${filter}" oninput="filter=this.value;render()"><button class="btn primary" onclick="openForm('person')">افزودن فرد</button></div></div><div class="cards-grid">${rows.map(p=>{const paid=db.transactions.filter(x=>x.party===p.name&&x.kind==='expense').reduce((s,x)=>s+x.amount,0);return `<article class="card person-card"><div class="person-head"><div class="person-avatar">${p.name[0]}</div><div><h3>${p.name}</h3><p>${p.role} • ${p.project||'همه پروژه‌ها'}</p></div></div><div class="person-totals"><span>مجموع پرداخت</span><strong>${money(paid)}</strong></div><small style="display:block;margin-top:10px;color:var(--muted)">${p.phone||'شماره ثبت نشده'}</small></article>`}).join('')||empty()}</div>`,'افراد و پیمانکاران')}
function contracts(){return layout(`<div class="section-head"><div><h2>قراردادها</h2><p>قرارداد کارفرما و پیمانکاران جزء</p></div><button class="btn primary" onclick="openForm('contract')">قرارداد جدید</button></div><div class="card table-wrap"><table class="table"><thead><tr><th>عنوان</th><th>پروژه</th><th>طرف قرارداد</th><th>تاریخ</th><th>مبلغ</th><th>وضعیت</th></tr></thead><tbody>${db.contracts.map(x=>`<tr><td>${x.title}</td><td>${x.project}</td><td>${x.party}</td><td>${x.date}</td><td>${money(x.amount)}</td><td><span class="pill">${x.status}</span></td></tr>`).join('')}</tbody></table>${db.contracts.length?'':empty()}</div>`,'قراردادها')}
function daily(){return layout(`<div class="section-head"><div><h2>گزارش روزانه کارگاه</h2><p>عملیات، تعداد نیرو، وضعیت هوا و اتفاقات مهم</p></div><button class="btn primary" onclick="openForm('daily')">گزارش جدید</button></div><div class="project-list">${db.daily.map(x=>`<article class="card"><div class="row-top"><strong>${x.project} • ${x.date}</strong><span class="pill">${fa(x.workers)} نفر</span></div><p>${x.text}</p><small style="color:var(--muted)">وضعیت هوا: ${x.weather||'ثبت نشده'}</small></article>`).join('')||empty()}</div>`,'گزارش روزانه')}
function documents(){return layout(`<div class="section-head"><div><h2>اسناد و فاکتورها</h2><p>آرشیو رسید، فاکتور خرید و مدارک پروژه</p></div></div><div class="card"><label class="file-zone"><input type="file" accept="image/*,.pdf" onchange="addDocument(this)"><strong>برای انتخاب فاکتور یا رسید لمس کن</strong><p style="color:var(--muted)">تصویر در فهرست دستگاه ثبت می‌شود؛ پردازش OCR در نسخه سرور فعال خواهد شد.</p><span class="btn gold">انتخاب فایل</span></label></div><div class="card table-wrap" style="margin-top:14px"><table class="table"><thead><tr><th>نام فایل</th><th>پروژه</th><th>تاریخ ثبت</th><th>اندازه</th></tr></thead><tbody>${db.documents.map(x=>`<tr><td>${x.name}</td><td>${x.project}</td><td>${x.date}</td><td>${x.size}</td></tr>`).join('')}</tbody></table>${db.documents.length?'':empty()}</div>`,'اسناد و فاکتورها')}
function settings(){return layout(`<div class="section-head"><div><h2>تنظیمات و پشتیبان</h2><p>مدیریت داده‌های این نسخه آزمایشی</p></div></div><div class="grid-2"><div class="card"><h3>پشتیبان اطلاعات</h3><p style="color:var(--muted)">از پروژه‌ها، اشخاص، تراکنش‌ها و گزارش‌ها یک فایل پشتیبان بگیر.</p><button class="btn primary" onclick="backup()">دانلود پشتیبان</button></div><div class="card danger-zone"><h3>بازگردانی اطلاعات نمونه</h3><p style="color:var(--muted)">همه تغییرات این دستگاه پاک و داده‌های آزمایشی برگردانده می‌شود.</p><button class="btn" onclick="resetDemo()">بازنشانی نسخه آزمایشی</button></div></div>`,'تنظیمات')}
function empty(){return '<div class="empty">هنوز اطلاعاتی ثبت نشده است.</div>'}
function render(){const view={dashboard,projects,finance,people,contracts,daily,documents,settings}[page]||dashboard;document.getElementById('app').innerHTML=view()}
function go(p){page=p;filter='';window.scrollTo(0,0);render()}
function options(list,key='name'){return list.map(x=>`<option value="${x[key]}">${x[key]}</option>`).join('')}
function openQuick(){openForm('transaction')}
function openForm(type){let title='',fields='';const projects=options(db.projects);if(type==='transaction'){title='ثبت تراکنش مالی';fields=`${field('پروژه',`<select id="fProject">${projects}</select>`)}${field('نوع عملیات','<select id="fKind"><option value="expense">پرداخت / هزینه</option><option value="income">دریافت</option></select>')}${field('طرف حساب','<input id="fParty" placeholder="نام پیمانکار، فروشنده یا کارفرما">')}${field('دسته‌بندی','<select id="fCategory"><option>پرداخت پیمانکار</option><option>خرید مصالح</option><option>تنخواه</option><option>حقوق و دستمزد</option><option>دریافت از کارفرما</option><option>سایر</option></select>')}${field('مبلغ به تومان','<input id="fAmount" inputmode="numeric" placeholder="مثلاً ۲۰۰۰۰۰۰۰">')}${field('تاریخ شمسی',`<input id="fDate" value="${todayFa()}">`)}${field('توضیحات','<textarea id="fNote"></textarea>','full')}`}else if(type==='project'){title='پروژه جدید';fields=`${field('نام پروژه','<input id="fName">')}${field('نام کارفرما','<input id="fClient">')}${field('موقعیت','<input id="fLocation">')}${field('بودجه','<input id="fBudget" inputmode="numeric">')}${field('درصد پیشرفت','<input id="fProgress" inputmode="numeric" value="0">')}${field('تاریخ شروع',`<input id="fStart" value="${todayFa()}">`)}`}else if(type==='person'){title='افزودن فرد یا پیمانکار';fields=`${field('نام و نام خانوادگی','<input id="fName">')}${field('تخصص / نقش','<input id="fRole" placeholder="جوشکار، بنا، نگهبان…">')}${field('پروژه',`<select id="fProject">${projects}</select>`)}${field('شماره تماس','<input id="fPhone" inputmode="tel">')}`}else if(type==='contract'){title='قرارداد جدید';fields=`${field('عنوان قرارداد','<input id="fTitle">')}${field('پروژه',`<select id="fProject">${projects}</select>`)}${field('طرف قرارداد','<input id="fParty">')}${field('مبلغ قرارداد','<input id="fAmount" inputmode="numeric">')}${field('تاریخ',`<input id="fDate" value="${todayFa()}">`)}${field('وضعیت','<select id="fStatus"><option>در حال اجرا</option><option>تکمیل شده</option><option>متوقف</option></select>')}`}else{title='گزارش روزانه جدید';fields=`${field('پروژه',`<select id="fProject">${projects}</select>`)}${field('تاریخ',`<input id="fDate" value="${todayFa()}">`)}${field('تعداد نیرو','<input id="fWorkers" inputmode="numeric">')}${field('وضعیت هوا','<input id="fWeather" placeholder="آفتابی، بارانی…">')}${field('شرح عملیات و اتفاقات','<textarea id="fText"></textarea>','full')}`}
 document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal" onclick="if(event.target===this)closeModal()"><div class="dialog" role="dialog" aria-modal="true"><div class="dialog-head"><h2>${title}</h2><button class="close" onclick="closeModal()" aria-label="بستن">×</button></div><div class="form-grid">${fields}</div><div class="dialog-actions"><button class="btn primary" onclick="submitForm('${type}')">ثبت اطلاعات</button><button class="btn" onclick="closeModal()">انصراف</button></div></div></div>`)}
function field(label,control,cls=''){return `<div class="field ${cls}"><label>${label}</label>${control}</div>`}
function v(id){return document.getElementById(id)?.value.trim()||''}function n(id){return Number(v(id).replace(/[٬,\s]/g,'').replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)))||0}
function submitForm(type){if(type==='transaction'){if(!n('fAmount')||!v('fParty'))return toast('نام طرف حساب و مبلغ الزامی است');db.transactions.push({id:uid(),project:v('fProject'),kind:v('fKind'),party:v('fParty'),category:v('fCategory'),amount:n('fAmount'),date:v('fDate'),note:v('fNote')})}else if(type==='project'){if(!v('fName'))return toast('نام پروژه را وارد کن');db.projects.push({id:uid(),name:v('fName'),client:v('fClient'),location:v('fLocation'),budget:n('fBudget'),progress:n('fProgress'),start:v('fStart'),status:'فعال'})}else if(type==='person'){if(!v('fName'))return toast('نام شخص را وارد کن');db.people.push({id:uid(),name:v('fName'),role:v('fRole'),project:v('fProject'),phone:v('fPhone')})}else if(type==='contract'){if(!v('fTitle'))return toast('عنوان قرارداد را وارد کن');db.contracts.push({id:uid(),title:v('fTitle'),project:v('fProject'),party:v('fParty'),amount:n('fAmount'),date:v('fDate'),status:v('fStatus')})}else{if(!v('fText'))return toast('شرح گزارش را وارد کن');db.daily.unshift({id:uid(),project:v('fProject'),date:v('fDate'),workers:n('fWorkers'),weather:v('fWeather'),text:v('fText')})}save();closeModal();toast('اطلاعات با موفقیت ثبت شد');render()}
function closeModal(){document.getElementById('modal')?.remove()}
function toast(msg){const e=document.getElementById('toast');e.textContent=msg;e.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>e.classList.remove('show'),2200)}
function normalizeDigits(s){return s.replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d))}
function parseQuick(){const input=document.getElementById('quickText'),box=document.getElementById('parsedResult'),text=input.value.trim();if(!text)return toast('ابتدا جمله را وارد کن');const project=db.projects.find(p=>text.includes(p.name));const person=db.people.find(p=>text.includes(p.name));const raw=normalizeDigits(text.replace(/[٬,]/g,''));const m=raw.match(/(\d+(?:\.\d+)?)\s*(میلیون|هزار|میلیارد)?/);let amount=m?Number(m[1]):0;if(m?.[2]==='هزار')amount*=1000;if(m?.[2]==='میلیون')amount*=1000000;if(m?.[2]==='میلیارد')amount*=1000000000;const date=(raw.match(/1[34]\d{2}[\/\-]\d{1,2}[\/\-]\d{1,2}/)||[])[0]||todayFa();const kind=/دریافت|گرفتم|واریز شد/.test(text)?'income':'expense';const category=/مصالح|خرید|فاکتور/.test(text)?'خرید مصالح':kind==='income'?'دریافت از کارفرما':'پرداخت پیمانکار';window.parsed={project:project?.name||'',party:person?.name||'',amount,date,kind,category};box.innerHTML=`<div class="parsed"><strong>پیش‌نویس تشخیص داده‌شده</strong><div class="parsed-grid"><div><small>پروژه</small>${window.parsed.project||'نامشخص'}</div><div><small>طرف حساب</small>${window.parsed.party||'نامشخص'}</div><div><small>مبلغ</small>${amount?money(amount):'نامشخص'}</div><div><small>تاریخ</small>${date}</div><div><small>نوع</small>${kind==='income'?'دریافت':'پرداخت'}</div><div><small>دسته</small>${category}</div></div><button class="btn primary" onclick="confirmParsed()" ${!project||!person||!amount?'disabled':''}>تأیید و ثبت</button>${!project||!person||!amount?'<p style="color:var(--red);margin-bottom:0">برای جلوگیری از ثبت اشتباه مالی، پروژه، شخص و مبلغ باید مشخص باشند.</p>':''}</div>`}
function confirmParsed(){const x=window.parsed;if(!x?.project||!x.party||!x.amount)return;db.transactions.push({...x,id:uid(),note:'ثبت سریع فارسی'});save();toast('تراکنش پس از تأیید ثبت شد');render()}
function addDocument(input){const f=input.files[0];if(!f)return;db.documents.unshift({id:uid(),name:f.name,project:db.projects[0]?.name||'—',date:todayFa(),size:`${Math.max(1,Math.round(f.size/1024))} KB`});save();toast('مشخصات سند ثبت شد');render()}
function exportCSV(){const rows=[['تاریخ','پروژه','طرف حساب','دسته‌بندی','نوع','مبلغ'],...db.transactions.map(x=>[x.date,x.project,x.party,x.category,x.kind==='income'?'دریافت':'پرداخت',x.amount])];download('گزارش-مالی-پیمان‌یار.csv','\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv')}
function backup(){download('پشتیبان-پیمان‌یار.json',JSON.stringify(db,null,2),'application/json')}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function resetDemo(){if(!confirm('همه اطلاعات این دستگاه به نسخه نمونه برگردد؟'))return;db=structuredClone(seed);save();toast('اطلاعات نمونه بازگردانی شد');render()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function commandFields(cmd){
 if(cmd.intent==='project_create')return [['عملیات',cmd.label],['نام پروژه',cmd.name],['کارفرما',cmd.client||'ثبت نشده'],['موقعیت',cmd.location||'ثبت نشده'],['بودجه',cmd.budget?money(cmd.budget):'ثبت نشده'],['پیشرفت',`${fa(cmd.progress||0)}٪`]];
 if(cmd.intent==='person_create')return [['عملیات',cmd.label],['نام',cmd.name],['تخصص',cmd.role],['پروژه',cmd.project||'ثبت نشده'],['موبایل',cmd.phone||'ثبت نشده']];
 if(cmd.intent==='daily_create')return [['عملیات',cmd.label],['پروژه',cmd.project],['تاریخ',cmd.date],['تعداد نیرو',cmd.workers?`${fa(cmd.workers)} نفر`:'ثبت نشده'],['شرح',cmd.text]];
 if(cmd.intent==='transaction_create')return [['عملیات',cmd.label],['پروژه',cmd.project],['طرف حساب',cmd.party],['مبلغ',cmd.amount?money(cmd.amount):'نامشخص'],['تاریخ',cmd.date],['دسته',cmd.category]];
 return []
}
function assistantPanel(){return `<section class="card assistant-box"><div class="assistant-head"><div><h3>ثبت فارسی با صدا</h3><p>در آیفون دکمه را بزن؛ سپس میکروفن روی کیبورد فارسی را لمس کن و فرمانت را بگو.</p></div><button type="button" id="voiceBtn" class="mic-btn" onclick="startVoice()" aria-label="باز کردن ورودی صوتی فارسی">🎙</button></div><div id="voiceStatus" class="voice-status" role="status" aria-live="polite">برای شروع، دکمه میکروفن را بزن</div><div class="quick-input"><textarea id="quickText" rows="3" lang="fa-IR" dir="rtl" inputmode="text" enterkeyhint="done" autocapitalize="none" autocomplete="off" autocorrect="on" spellcheck="true" translate="no" oninput="scheduleCommandAnalysis()" aria-label="فرمان فارسی" placeholder="مثلاً: یک پروژه جدید به نام پروژه نمونه بساز"></textarea><button type="button" class="btn gold" onclick="parseQuick()">تحلیل فرمان</button></div><div class="assistant-examples"><button type="button" onclick="useExample('یک پروژه جدید به نام پروژه نمونه با کارفرما کارفرمای نمونه بساز')">ساخت پروژه</button><button type="button" onclick="useExample('پیمانکار جدید به نام پیمانکار نمونه جوشکار برای پروژه نمونه ثبت کن')">تعریف پیمانکار</button><button type="button" onclick="useExample('برای پروژه نمونه به پیمانکار نمونه یک میلیون تومان پرداخت کردم')">ثبت پرداخت</button><button type="button" onclick="useExample('گزارش روزانه پروژه نمونه را ثبت کن امروز ۷ نفر کار کردند و جوشکاری طبقه دوم انجام شد')">گزارش روزانه</button></div><div id="parsedResult"></div></section>`}
dashboard=function(){const t=totals();const avg=Math.round(db.projects.reduce((s,p)=>s+p.progress,0)/(db.projects.length||1));return layout(`<section class="welcome"><div><h2>تصویر امروز کارگاه‌ها</h2><p>هزینه، پیشرفت و تعهدات همه پروژه‌ها در یک نگاه</p></div><div class="today">امروز ${todayFa()}</div></section><section class="stats"><div class="stat"><span class="label">پروژه‌های فعال</span><strong>${fa(db.projects.filter(x=>x.status==='فعال').length)}</strong><small>میانگین پیشرفت ${fa(avg)}٪</small></div><div class="stat"><span class="label">دریافتی ثبت‌شده</span><strong>${money(t.income)}</strong><small>ورودی پروژه‌ها</small></div><div class="stat warn"><span class="label">هزینه و پرداخت</span><strong>${money(t.expense)}</strong><small>خروجی ثبت‌شده</small></div><div class="stat"><span class="label">پیمانکار و نیرو</span><strong>${fa(db.people.length)} نفر</strong><small>${fa(db.contracts.length)} قرارداد فعال</small></div></section>${assistantPanel()}<section class="grid-2" style="margin-top:16px"><div class="card"><div class="card-head"><h3>وضعیت پروژه‌ها</h3><button class="link-btn" onclick="go('projects')">مشاهده همه</button></div><div class="project-list">${db.projects.map(projectRow).join('')||empty()}</div></div><div class="card"><div class="card-head"><h3>آخرین گردش مالی</h3><button class="link-btn" onclick="go('finance')">گزارش مالی</button></div><div class="activity">${db.transactions.slice(-5).reverse().map(activityRow).join('')||empty()}</div></div></section>`,'داشبورد')}
function useExample(text){const input=document.getElementById('quickText');input.value=text;parseQuick()}
function scheduleCommandAnalysis(){const input=document.getElementById('quickText'),status=document.getElementById('voiceStatus');clearTimeout(window.commandAnalysisTimer);const text=input?.value.trim();if(!text)return;if(/[A-Za-z]/.test(text)&&!/[آ-ی]/.test(text)){if(status)status.textContent='کیبورد روی انگلیسی است؛ علامت 🌐 را بزن، «فارسی» را انتخاب کن و دوباره بگو.';return}if(status)status.textContent='متن فارسی دریافت شد؛ در حال تحلیل فرمان…';window.commandAnalysisTimer=setTimeout(()=>{if(document.getElementById('quickText')?.value.trim())parseQuick()},900)}
parseQuick=function(){
 const input=document.getElementById('quickText'),box=document.getElementById('parsedResult');if(!input||!box)return;const text=input.value.trim();if(!text)return toast('ابتدا فرمان را بگو یا بنویس');
 const cmd=PeymanyarCommand.parse(text,db,todayFa());window.parsedCommand=cmd;
 if(cmd.intent==='unknown'){box.innerHTML='<div class="parsed"><strong>فرمان را کامل متوجه نشدم</strong><p>مثلاً بگو: «پیمانکار جدید پیمانکار نمونه، جوشکار برای پروژه نمونه ثبت کن».</p></div>';return}
 if(cmd.intent==='financial_query'){const rows=db.transactions.filter(x=>(!cmd.person||x.party===cmd.person)&&(!cmd.project||x.project===cmd.project));const paid=rows.filter(x=>x.kind==='expense').reduce((s,x)=>s+x.amount,0),received=rows.filter(x=>x.kind==='income').reduce((s,x)=>s+x.amount,0);box.innerHTML=`<div class="parsed"><div class="command-title"><strong>گزارش مالی</strong><span class="command-badge">پاسخ</span></div><div class="parsed-grid"><div><small>پرداخت و هزینه</small>${money(paid)}</div><div><small>دریافت</small>${money(received)}</div><div><small>تعداد تراکنش</small>${fa(rows.length)}</div></div></div>`;return}
 const fields=commandFields(cmd).map(([k,v])=>`<div><small>${esc(k)}</small>${esc(v||'نامشخص')}</div>`).join(''),missing=cmd.missing||[];
 box.innerHTML=`<div class="parsed"><div class="command-title"><strong>پیش‌نویس فرمان</strong><span class="command-badge">${esc(cmd.label)}</span></div><div class="parsed-grid">${fields}</div>${missing.length?`<div class="missing">برای ثبت، این موارد را هم در جمله بگو: ${missing.map(esc).join('، ')}</div>`:'<button class="btn primary" onclick="confirmCommand()">تأیید و ثبت</button>'}</div>`
}
function confirmCommand(){const c=window.parsedCommand;if(!c||c.missing?.length)return;if(c.intent==='project_create'){db.projects.push({id:uid(),name:c.name,client:c.client||'ثبت نشده',location:c.location||'',budget:c.budget||0,progress:c.progress||0,status:'فعال',start:c.date})}else if(c.intent==='person_create'){db.people.push({id:uid(),name:c.name,role:c.role,phone:c.phone||'',project:c.project||''})}else if(c.intent==='daily_create'){db.daily.unshift({id:uid(),project:c.project,date:c.date,workers:c.workers||0,weather:c.weather||'',text:c.text})}else if(c.intent==='transaction_create'){db.transactions.push({id:uid(),project:c.project,party:c.party||'ثبت نشده',amount:c.amount,date:c.date,kind:c.kind,category:c.category,note:c.note})}else return;save();toast(`${c.label} با موفقیت انجام شد`);render()}
let voiceRecognition=null,voiceListening=false;
function setVoiceState(message,listening=false){const status=document.getElementById('voiceStatus'),btn=document.getElementById('voiceBtn');voiceListening=listening;if(status)status.textContent=message;if(btn){btn.classList.toggle('listening',listening);btn.textContent=listening?'■':'🎙';btn.setAttribute('aria-label',listening?'توقف ضبط صدا':'شروع ضبط صدای فارسی')}}
function voiceErrorMessage(code){return ({'not-allowed':'اجازه میکروفن داده نشد؛ از تنظیمات Safari دسترسی میکروفن را روی Allow بگذار.','service-not-allowed':'سرویس تشخیص صدا روی این مرورگر در دسترس نیست.','audio-capture':'میکروفن گوشی در دسترس نیست.','no-speech':'صدایی شنیده نشد؛ دوباره بزن و نزدیک گوشی صحبت کن.','network':'ارتباط سرویس صوتی گوشی برقرار نشد؛ اینترنت را بررسی کن.','language-not-supported':'تشخیص فارسی روی این مرورگر پشتیبانی نمی‌شود.','aborted':'ضبط متوقف شد.'}[code]||`تشخیص صدا انجام نشد (${code||'خطای نامشخص'}).`)}
async function startVoice(){
 const input=document.getElementById('quickText');if(!input)return;
 if(voiceListening&&voiceRecognition){voiceRecognition.stop();setVoiceState('ضبط متوقف شد؛ در حال تحلیل متن…');return}
 const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
 if(!Recognition){input.focus();input.click();setVoiceState('کیبورد باز شد؛ میکروفن کنار کیبورد فارسی را بزن و صحبت کن.');toast('حالا میکروفن کیبورد فارسی را بزن');return}
 try{if(navigator.mediaDevices?.getUserMedia){const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(track=>track.stop())}}catch(err){setVoiceState('اجازه میکروفن داده نشد؛ در تنظیمات Safari، Microphone را روی Allow بگذار.');return}
 const recognition=new Recognition();voiceRecognition=recognition;recognition.lang='fa-IR';recognition.continuous=false;recognition.interimResults=true;recognition.maxAlternatives=1;let finalText='';
 recognition.onstart=()=>setVoiceState('در حال شنیدن… فارسی صحبت کن',true);
 recognition.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0].transcript;if(e.results[i].isFinal)finalText+=`${text} `;else interim+=text}input.value=(finalText||interim).trim();if(interim)setVoiceState(`شنیدم: ${interim}`,true)};
 recognition.onerror=e=>{setVoiceState(voiceErrorMessage(e.error));voiceRecognition=null};
 recognition.onend=()=>{const text=input.value.trim();voiceRecognition=null;setVoiceState(text?'صدا به متن تبدیل شد؛ در حال تحلیل فرمان…':'ضبط تمام شد اما متنی دریافت نشد.');if(text)setTimeout(parseQuick,250)};
 try{recognition.start()}catch(err){setVoiceState('میکروفن آماده نشد؛ صفحه را تازه‌سازی و دوباره امتحان کن.')}
}
const FILE_DB='peymanyar-documents',FILE_STORE='files',memoryFiles=new Map();let viewerScale=1,viewerUrl='',pinchStart=0,pinchScale=1;
function openFileDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(FILE_DB,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(FILE_STORE))req.result.createObjectStore(FILE_STORE,{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function storeFile(id,file){const idb=await openFileDB();return new Promise((resolve,reject)=>{const tx=idb.transaction(FILE_STORE,'readwrite');tx.objectStore(FILE_STORE).put({id,blob:file,type:file.type,name:file.name});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function readFile(id){const idb=await openFileDB();return new Promise((resolve,reject)=>{const req=idb.transaction(FILE_STORE,'readonly').objectStore(FILE_STORE).get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
documents=function(){return layout(`<div class="section-head"><div><h2>اسناد و فاکتورها</h2><p>فایل را باز کن، بزرگ‌نمایی کن و جزئیات آن را ببین</p></div></div><div class="card"><label class="file-zone"><input type="file" accept="image/*,.pdf,application/pdf" onchange="addDocument(this)"><strong>برای انتخاب عکس، فاکتور یا PDF لمس کن</strong><p style="color:var(--muted)">فایل روی همین گوشی ذخیره می‌شود و قابل مشاهده و زوم است.</p><span class="btn gold">انتخاب فایل</span></label></div><div class="card table-wrap" style="margin-top:14px"><table class="table"><thead><tr><th>نام فایل</th><th>پروژه</th><th>تاریخ ثبت</th><th>اندازه</th><th>نمایش</th></tr></thead><tbody>${db.documents.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.project)}</td><td>${esc(x.date)}</td><td>${esc(x.size)}</td><td><div class="doc-actions"><button type="button" class="doc-open" onclick="viewDocument(${Number(x.id)})">بازکردن و زوم</button></div></td></tr>`).join('')}</tbody></table>${db.documents.length?'':empty()}</div>`,'اسناد و فاکتورها')}
addDocument=async function(input){const file=input.files?.[0];if(!file)return;const id=uid(),meta={id,name:file.name,project:db.projects[0]?.name||'—',date:todayFa(),size:`${Math.max(1,Math.round(file.size/1024))} KB`,type:file.type||''};memoryFiles.set(id,{id,blob:file,type:file.type,name:file.name});try{await storeFile(id,file)}catch{}db.documents.unshift(meta);save();render();setTimeout(()=>viewDocument(id),0)}
async function reattachDocument(id,input){const file=input.files?.[0];if(!file)return;const item={id,blob:file,type:file.type,name:file.name};memoryFiles.set(id,item);try{await storeFile(id,file)}catch{}const meta=db.documents.find(x=>Number(x.id)===Number(id));if(meta){meta.name=file.name;meta.type=file.type;meta.size=`${Math.max(1,Math.round(file.size/1024))} KB`;save()}render();setTimeout(()=>viewDocument(id),0)}
async function viewDocument(id){let item=memoryFiles.get(Number(id));if(!item)try{item=await readFile(Number(id))}catch{}if(!item?.blob){toast('برای اولین نمایش، فایل را دوباره انتخاب کن');setTimeout(()=>document.getElementById(`replace-${id}`)?.click(),100);return}viewerScale=1;viewerUrl=URL.createObjectURL(item.blob);const isPdf=item.type==='application/pdf'||/\.pdf$/i.test(item.name);document.body.insertAdjacentHTML('beforeend',`<div class="viewer" id="docViewer"><div class="viewer-head"><strong>${esc(item.name)}</strong><button type="button" class="viewer-close" onclick="closeViewer()">×</button></div><div class="viewer-stage" id="viewerStage">${isPdf?`<object data="${viewerUrl}" type="application/pdf" width="100%" height="100%"><a href="${viewerUrl}" target="_blank">بازکردن PDF</a></object>`:`<img id="viewerImage" src="${viewerUrl}" alt="${esc(item.name)}">`}</div><div class="viewer-controls">${isPdf?'':`<button type="button" onclick="zoomDocument(-.25)">−</button><span class="viewer-zoom" id="zoomValue">۱۰۰٪</span><button type="button" onclick="zoomDocument(.25)">＋</button>`}<a href="${viewerUrl}" target="_blank" rel="noopener">بازکردن در گوشی</a></div></div>`);if(!isPdf)enablePinchZoom()}
function zoomDocument(delta){viewerScale=Math.max(.5,Math.min(4,viewerScale+delta));const img=document.getElementById('viewerImage');if(img)img.style.transform=`scale(${viewerScale})`;const label=document.getElementById('zoomValue');if(label)label.textContent=`${fa(Math.round(viewerScale*100))}٪`}
function touchDistance(t){return Math.hypot(t[0].clientX-t[1].clientX,t[0].clientY-t[1].clientY)}
function enablePinchZoom(){const stage=document.getElementById('viewerStage');stage.addEventListener('touchstart',e=>{if(e.touches.length===2){pinchStart=touchDistance(e.touches);pinchScale=viewerScale}},{passive:true});stage.addEventListener('touchmove',e=>{if(e.touches.length===2&&pinchStart){e.preventDefault();viewerScale=Math.max(.5,Math.min(4,pinchScale*touchDistance(e.touches)/pinchStart));const img=document.getElementById('viewerImage');if(img)img.style.transform=`scale(${viewerScale})`;const label=document.getElementById('zoomValue');if(label)label.textContent=`${fa(Math.round(viewerScale*100))}٪`}},{passive:false})}
function closeViewer(){document.getElementById('docViewer')?.remove();if(viewerUrl)URL.revokeObjectURL(viewerUrl);viewerUrl=''}
documents=function(){return layout(`<div class="section-head"><div><h2>اسناد و فاکتورها</h2><p>عکس یا PDF را تمام‌صفحه باز کن و زوم کن</p></div></div><div class="card"><label class="file-zone"><input type="file" accept="image/*,.pdf,application/pdf" onchange="addDocument(this)"><strong>انتخاب عکس، فاکتور یا PDF</strong><p style="color:var(--muted)">بعد از انتخاب، فایل همان لحظه باز می‌شود.</p><span class="btn gold">انتخاب و نمایش فایل</span></label></div><div class="project-list" style="margin-top:14px">${db.documents.map(x=>`<article class="card"><div class="row-top"><div><strong>${esc(x.name)}</strong><div style="color:var(--muted);margin-top:5px">${esc(x.project)} • ${esc(x.date)} • ${esc(x.size)}</div></div><div class="doc-actions"><button type="button" class="doc-open" onclick="viewDocument(${Number(x.id)})">بازکردن</button><input id="replace-${Number(x.id)}" type="file" accept="image/*,.pdf,application/pdf" hidden onchange="reattachDocument(${Number(x.id)},this)"></div></div></article>`).join('')||empty()}</div>`,'اسناد و فاکتورها')}
function phoneNavButton(p,label){return `<button type="button" class="${page===p?'active':''}" onclick="go('${p}')"><span>${icon(p)}</span><span>${label}</span></button>`}
layout=function(body,title){return `<div class="phone-shell"><header class="phone-header"><div class="phone-title"><strong>${esc(title)}</strong><small>پیمان‌یار</small></div><div class="phone-head-actions"><button type="button" onclick="openQuick()" aria-label="ثبت سریع">＋</button><button type="button" onclick="go('settings')" aria-label="تنظیمات">⚙</button></div></header><main class="phone-content">${body}</main><button type="button" class="phone-fab" onclick="openQuick()" aria-label="ثبت سریع">＋</button><nav class="phone-nav">${[['dashboard','خانه'],['projects','پروژه'],['finance','مالی'],['people','افراد'],['daily','گزارش']].map(x=>phoneNavButton(x[0],x[1])).join('')}</nav></div>`}
finance=function(){const t=totals(),rows=db.transactions.filter(x=>[x.project,x.party,x.category].some(v=>(v||'').includes(filter)));return layout(`<div class="section-head"><div><h2>امور مالی</h2><p>پرداخت‌ها، هزینه‌ها و دریافتی‌ها</p></div><div class="toolbar"><input class="search" placeholder="جست‌وجوی مالی" value="${esc(filter)}" oninput="filter=this.value;render()"><button type="button" class="btn primary" onclick="openForm('transaction')">ثبت تراکنش</button></div></div><div class="kpi-row" style="grid-template-columns:1fr;margin-bottom:10px"><div class="kpi"><small>دریافتی</small><strong>${money(t.income)}</strong></div><div class="kpi"><small>پرداختی</small><strong>${money(t.expense)}</strong></div><div class="kpi"><small>تراز</small><strong>${money(t.income-t.expense)}</strong></div></div><div class="phone-list">${rows.slice().reverse().map(x=>`<article class="phone-row"><div class="phone-row-head"><strong>${esc(x.category)}</strong><span class="pill ${x.kind==='expense'?'paused':''}">${x.kind==='income'?'دریافت':'پرداخت'}</span></div><div class="phone-row-meta">${esc(x.project)}<br>${esc(x.party)} • ${esc(x.date)}</div><div class="phone-amount ${x.kind==='expense'?'out':''}">${x.kind==='income'?'+':'−'} ${money(x.amount)}</div></article>`).join('')||empty()}</div>`,'امور مالی')}
contracts=function(){return layout(`<div class="section-head"><div><h2>قراردادها</h2><p>قراردادهای کارفرما و پیمانکاران</p></div><button type="button" class="btn primary" onclick="openForm('contract')">قرارداد جدید</button></div><div class="phone-list">${db.contracts.map(x=>`<article class="phone-row"><div class="phone-row-head"><strong>${esc(x.title)}</strong><span class="pill">${esc(x.status)}</span></div><div class="phone-row-meta">${esc(x.project)}<br>${esc(x.party)} • ${esc(x.date)}</div><div class="phone-amount">${money(x.amount)}</div></article>`).join('')||empty()}</div>`,'قراردادها')}
let selectedProjectId=null,selectedPersonId=null,activeReport={title:'گزارش مالی',rows:[],project:'',person:'',dateFrom:'',dateTo:''};
function normalizeDateValue(value){const p=normalizeDigits(String(value||'')).match(/(1[34]\d{2})[\/-](\d{1,2})[\/-](\d{1,2})/);return p?`${p[1]}/${p[2].padStart(2,'0')}/${p[3].padStart(2,'0')}`:''}
function reportRows({project='',person='',dateFrom='',dateTo=''}={}){const from=normalizeDateValue(dateFrom),to=normalizeDateValue(dateTo);return db.transactions.filter(x=>{const d=normalizeDateValue(x.date);return(!project||x.project===project)&&(!person||x.party===person)&&(!from||d>=from)&&(!to||d<=to)})}
function reportSummary(rows){return{paid:rows.filter(x=>x.kind==='expense').reduce((s,x)=>s+x.amount,0),received:rows.filter(x=>x.kind==='income').reduce((s,x)=>s+x.amount,0)}}
function contractAccount(project,person){const contract=db.contracts.filter(x=>(!project||x.project===project)&&(!person||x.party===person)).reduce((s,x)=>s+Number(x.amount||0),0),paid=db.transactions.filter(x=>x.kind==='expense'&&(!project||x.project===project)&&(!person||x.party===person)).reduce((s,x)=>s+Number(x.amount||0),0);return{contract,paid,remain:contract-paid}}
function openProject(id){selectedProjectId=Number(id);page='projectDetail';filter='';window.scrollTo(0,0);render()}
function openPerson(id){selectedPersonId=Number(id);page='personDetail';filter='';window.scrollTo(0,0);render()}
function projectDetail(){const p=db.projects.find(x=>Number(x.id)===selectedProjectId);if(!p)return projects();const tx=reportRows({project:p.name}),sum=reportSummary(tx),peopleRows=db.people.filter(x=>x.project===p.name),contractsRows=db.contracts.filter(x=>x.project===p.name),dailyRows=db.daily.filter(x=>x.project===p.name);return layout(`<button class="back-btn" onclick="go('projects')">← همه پروژه‌ها</button><section class="project-hero"><div><h2>${esc(p.name)}</h2><p>${esc(p.client||'کارفرما ثبت نشده')} • ${esc(p.location||'موقعیت ثبت نشده')}</p></div><span class="pill">${esc(p.status)}</span></section><section class="detail-kpis"><div><small>دریافتی</small><strong>${money(sum.received)}</strong></div><div><small>هزینه و پرداخت</small><strong>${money(sum.paid)}</strong></div><div><small>تراز</small><strong>${money(sum.received-sum.paid)}</strong></div><div><small>پیشرفت</small><strong>${fa(p.progress)}٪</strong></div></section><div class="report-actions"><button onclick="prepareReport('${esc(p.name)}','')">گزارش کامل</button><button onclick="prepareReport('${esc(p.name)}','');exportActiveCSV()">Excel</button><button onclick="prepareReport('${esc(p.name)}','');exportActiveWord()">Word</button><button onclick="prepareReport('${esc(p.name)}','');printActiveReport()">PDF / چاپ</button></div><section class="detail-section"><h3>پیمانکاران و نیروها</h3><div class="phone-list">${peopleRows.map(x=>{const a=contractAccount(p.name,x.name);return `<button class="entity-row" onclick="openPerson(${Number(x.id)})"><span><strong>${esc(x.name)}</strong><small>${esc(x.role)}</small></span><span><small>پرداخت</small><strong>${money(a.paid)}</strong></span></button>`}).join('')||empty()}</div></section><section class="detail-section"><h3>قراردادها و مانده</h3><div class="phone-list">${contractsRows.map(x=>{const a=contractAccount(p.name,x.party);return `<article class="phone-row"><div class="phone-row-head"><strong>${esc(x.title)}</strong><span>${esc(x.party)}</span></div><div class="contract-grid"><span>قرارداد: ${money(x.amount)}</span><span>پرداخت: ${money(a.paid)}</span><strong>مانده: ${money(Number(x.amount)-a.paid)}</strong></div></article>`}).join('')||empty()}</div></section><section class="detail-section"><h3>گردش مالی</h3>${transactionReportTable(tx)}</section><section class="detail-section"><h3>گزارش‌های روزانه</h3><div class="phone-list">${dailyRows.map(x=>`<article class="phone-row"><strong>${esc(x.date)} • ${fa(x.workers)} نفر</strong><p>${esc(x.text)}</p></article>`).join('')||empty()}</div></section>`,'جزئیات پروژه')}
function personDetail(){const p=db.people.find(x=>Number(x.id)===selectedPersonId);if(!p)return people();const tx=reportRows({project:p.project,person:p.name}),sum=reportSummary(tx),a=contractAccount(p.project,p.name),contractsRows=db.contracts.filter(x=>x.party===p.name&&(!p.project||x.project===p.project));return layout(`<button class="back-btn" onclick="${p.project?`openProject(${Number(db.projects.find(x=>x.name===p.project)?.id||0)})`:`go('people')`}">← بازگشت</button><section class="project-hero"><div><h2>${esc(p.name)}</h2><p>${esc(p.role)} • ${esc(p.project||'همه پروژه‌ها')}</p></div></section><section class="detail-kpis"><div><small>مبلغ قرارداد</small><strong>${money(a.contract)}</strong></div><div><small>پرداخت‌شده</small><strong>${money(a.paid)}</strong></div><div><small>مانده قرارداد</small><strong>${money(a.remain)}</strong></div><div><small>تعداد پرداخت</small><strong>${fa(tx.length)}</strong></div></section><div class="report-actions"><button onclick="prepareReport('${esc(p.project)}','${esc(p.name)}')">نمایش گزارش</button><button onclick="prepareReport('${esc(p.project)}','${esc(p.name)}');exportActiveCSV()">Excel</button><button onclick="prepareReport('${esc(p.project)}','${esc(p.name)}');exportActiveWord()">Word</button><button onclick="prepareReport('${esc(p.project)}','${esc(p.name)}');printActiveReport()">PDF / چاپ</button></div><section class="detail-section"><h3>قراردادها</h3>${contractsRows.map(x=>`<article class="phone-row"><strong>${esc(x.title)}</strong><div class="contract-grid"><span>${money(x.amount)}</span><span>${esc(x.date)}</span></div></article>`).join('')||empty()}</section><section class="detail-section"><h3>ریز حساب</h3>${transactionReportTable(tx)}</section>`,'حساب پیمانکار')}
function transactionReportTable(rows){return `<div class="report-table">${rows.slice().reverse().map(x=>`<article><div><strong>${esc(x.category)}</strong><small>${esc(x.date)} • ${esc(x.party)}</small></div><span class="${x.kind==='expense'?'out':''}">${x.kind==='income'?'+':'−'} ${money(x.amount)}</span></article>`).join('')||empty()}</div>`}
projects=function(){const rows=db.projects.filter(x=>x.name.includes(filter)||x.client.includes(filter));return layout(`<div class="section-head"><div><h2>پروژه‌ها</h2><p>برای دیدن مالی، پیمانکاران و گزارش‌ها روی پروژه بزن</p></div><div class="toolbar"><input class="search" placeholder="جست‌وجوی پروژه" value="${esc(filter)}" oninput="filter=this.value;render()"><button class="btn primary" onclick="openForm('project')">پروژه جدید</button></div></div><div class="cards-grid">${rows.map(p=>`<button class="card project-card-button" onclick="openProject(${Number(p.id)})"><div class="row-top"><h3>${esc(p.name)}</h3><span class="pill">${esc(p.status)}</span></div><p>${esc(p.client)} • ${esc(p.location||'بدون موقعیت')}</p><div class="progress"><i style="width:${Math.min(Number(p.progress)||0,100)}%"></i></div><div class="split"><span>${fa(p.progress)}٪</span><strong>مشاهده جزئیات ←</strong></div></button>`).join('')||empty()}</div>`,'پروژه‌ها')}
people=function(){const rows=db.people.filter(x=>[x.name,x.role,x.project].some(v=>(v||'').includes(filter)));return layout(`<div class="section-head"><div><h2>افراد و پیمانکاران</h2><p>برای مشاهده قرارداد، پرداخت و مانده روی شخص بزن</p></div><div class="toolbar"><input class="search" placeholder="نام یا تخصص" value="${esc(filter)}" oninput="filter=this.value;render()"><button class="btn primary" onclick="openForm('person')">افزودن فرد</button></div></div><div class="cards-grid">${rows.map(p=>{const a=contractAccount(p.project,p.name);return `<button class="card project-card-button" onclick="openPerson(${Number(p.id)})"><div class="person-head"><div class="person-avatar">${esc(p.name[0])}</div><div><h3>${esc(p.name)}</h3><p>${esc(p.role)} • ${esc(p.project||'همه پروژه‌ها')}</p></div></div><div class="contract-grid"><span>پرداخت ${money(a.paid)}</span><strong>مانده ${money(a.remain)}</strong></div></button>`}).join('')||empty()}</div>`,'افراد و پیمانکاران')}
function prepareReport(project='',person='',dateFrom='',dateTo=''){const rows=reportRows({project,person,dateFrom,dateTo});activeReport={title:`گزارش مالی${project?' پروژه '+project:''}${person?' - '+person:''}`,rows,project,person,dateFrom,dateTo};showReportModal();return activeReport}
function showReportModal(){const sum=reportSummary(activeReport.rows),a=contractAccount(activeReport.project,activeReport.person);document.getElementById('reportModal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="reportModal"><div class="dialog report-dialog"><div class="dialog-head"><h2>${esc(activeReport.title)}</h2><button class="close" onclick="document.getElementById('reportModal').remove()">×</button></div><div class="detail-kpis"><div><small>دریافتی</small><strong>${money(sum.received)}</strong></div><div><small>پرداخت</small><strong>${money(sum.paid)}</strong></div><div><small>قرارداد</small><strong>${money(a.contract)}</strong></div><div><small>مانده</small><strong>${money(a.remain)}</strong></div></div>${transactionReportTable(activeReport.rows)}<div class="report-actions"><button onclick="exportActiveCSV()">Excel</button><button onclick="exportActiveWord()">Word</button><button onclick="printActiveReport()">PDF / چاپ</button></div></div></div>`)}
function reportMatrix(){return [['تاریخ','پروژه','طرف حساب','دسته‌بندی','نوع','مبلغ'],...activeReport.rows.map(x=>[x.date,x.project,x.party,x.category,x.kind==='income'?'دریافت':'پرداخت',x.amount])]}
function safeFileName(){return activeReport.title.replace(/[\\/:*?"<>|]/g,'-')}
function exportActiveCSV(){const rows=reportMatrix();download(`${safeFileName()}.csv`,'\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv;charset=utf-8')}
function exportActiveWord(){const sum=reportSummary(activeReport.rows),rows=reportMatrix().map((r,i)=>`<tr>${r.map(v=>`<${i?'td':'th'}>${esc(v)}</${i?'td':'th'}>`).join('')}</tr>`).join(''),html=`<html dir="rtl"><meta charset="utf-8"><body><h1>${esc(activeReport.title)}</h1><p>دریافتی: ${money(sum.received)} | پرداخت: ${money(sum.paid)}</p><table border="1" cellspacing="0" cellpadding="6">${rows}</table></body></html>`;download(`${safeFileName()}.doc`,html,'application/msword;charset=utf-8')}
function printActiveReport(){const sum=reportSummary(activeReport.rows),w=window.open('','_blank');if(!w)return toast('اجازه بازشدن پنجره را فعال کن');w.document.write(`<html dir="rtl"><meta charset="utf-8"><title>${esc(activeReport.title)}</title><style>body{font-family:Tahoma;padding:24px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #bbb;padding:7px;text-align:right}</style><body><h1>${esc(activeReport.title)}</h1><p>دریافتی: ${money(sum.received)} | پرداخت: ${money(sum.paid)}</p><table>${reportMatrix().map((r,i)=>`<tr>${r.map(v=>`<${i?'td':'th'}>${esc(v)}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</table><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
let pendingSmartFile=null;
function smartInboxPanel(project=''){return `<section class="smart-inbox"><div><span class="smart-badge">صندوق ورودی هوشمند</span><h3>هر سندی را همین‌جا بسپار</h3><p>قرارداد، فاکتور، رسید یا عکس را انتخاب کن و با یک جمله بگو مربوط به چه پروژه و چه کسی است.</p></div><button type="button" onclick="openSmartUpload('${esc(project)}')">＋ آپلود و دسته‌بندی</button></section>`}
function closeSmartUpload(){document.getElementById('smartUploadModal')?.remove();pendingSmartFile=null}
function openSmartUpload(project=''){pendingSmartFile=null;document.getElementById('smartUploadModal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="smartUploadModal"><div class="dialog smart-upload-dialog"><div class="dialog-head"><h2>ثبت هوشمند سند</h2><button class="close" onclick="closeSmartUpload()">×</button></div><label class="file-zone smart-file-zone"><input id="smartFile" type="file" accept="image/*,.pdf,application/pdf,.doc,.docx" onchange="smartFileSelected(this)"><strong id="smartFileName">ابتدا فایل را انتخاب کن</strong><span class="btn gold">انتخاب فایل</span></label><div class="field full"><label>این سند چیست و متعلق به کیست؟</label><textarea id="smartDocCommand" rows="3" placeholder="مثلاً: این قرارداد جوشکاری پیمانکار نمونه برای پروژه نمونه است" oninput="scheduleSmartDocAnalysis()"></textarea><button type="button" class="btn primary" onclick="analyzeSmartDocument()">تحلیل توضیح</button></div><div id="smartQuestions" class="smart-questions">بعد از انتخاب فایل، توضیح کوتاه را بنویس یا با میکروفن کیبورد بگو.</div><div class="form-grid smart-meta"><div class="field"><label>نوع سند</label><select id="smartType"><option value="">انتخاب کن</option><option>قرارداد پیمانکار</option><option>قرارداد کارفرما</option><option>فاکتور خرید</option><option>رسید پرداخت</option><option>گزارش کارگاه</option><option>تصویر پروژه</option><option>سایر</option></select></div><div class="field"><label>پروژه</label><select id="smartProject"><option value="">انتخاب کن</option>${db.projects.map(x=>`<option ${x.name===project?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>پیمانکار / طرف سند</label><select id="smartPerson"><option value="">انتخاب کن</option>${db.people.map(x=>`<option>${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>تاریخ شمسی</label><input id="smartDate" value="${todayFa()}"></div><div class="field"><label>مبلغ</label><input id="smartAmount" inputmode="numeric" placeholder="در صورت وجود"></div><div class="field"><label>عنوان</label><input id="smartTitle" placeholder="مثلاً قرارداد اجرای جوشکاری"></div></div><div class="dialog-actions"><button class="btn primary" onclick="saveSmartDocument()">بررسی و بایگانی</button><button class="btn" onclick="closeSmartUpload()">انصراف</button></div></div></div>`)}
function smartFileSelected(input){pendingSmartFile=input.files?.[0]||null;const label=document.getElementById('smartFileName');if(label&&pendingSmartFile)label.textContent=pendingSmartFile.name;analyzeSmartDocument()}
function scheduleSmartDocAnalysis(){clearTimeout(window.smartDocTimer);window.smartDocTimer=setTimeout(analyzeSmartDocument,700)}
function setSelectValue(id,value){const el=document.getElementById(id);if(!el||!value)return;const option=[...el.options].find(o=>o.value===value||o.textContent===value);if(option)el.value=option.value}
function analyzeSmartDocument(){const text=document.getElementById('smartDocCommand')?.value.trim()||'',project=db.projects.find(x=>text.includes(x.name)),person=db.people.find(x=>text.includes(x.name));const type=/قرارداد/.test(text)?(/کارفرما/.test(text)?'قرارداد کارفرما':'قرارداد پیمانکار'):/فاکتور|خرید/.test(text)?'فاکتور خرید':/رسید|پرداخت|واریز/.test(text)?'رسید پرداخت':/گزارش/.test(text)?'گزارش کارگاه':/عکس|تصویر/.test(text)?'تصویر پروژه':'';if(project)setSelectValue('smartProject',project.name);if(person)setSelectValue('smartPerson',person.name);if(type)setSelectValue('smartType',type);const amount=PeymanyarCommand.amountOf(text);if(amount)document.getElementById('smartAmount').value=fa(amount);const detectedDate=PeymanyarCommand.dateOf(text,'');if(detectedDate)document.getElementById('smartDate').value=detectedDate;const title=document.getElementById('smartTitle');if(title&&!title.value&&type)title.value=`${type}${person?' - '+person.name:''}`;updateSmartQuestions()}
function updateSmartQuestions(){const missing=[];if(!pendingSmartFile)missing.push('فایل را انتخاب کن');if(!v('smartType'))missing.push('این فایل قرارداد است، فاکتور، رسید یا عکس؟');if(!v('smartProject'))missing.push('مربوط به کدام پروژه است؟');if(/قرارداد|رسید/.test(v('smartType'))&&!v('smartPerson'))missing.push('طرف قرارداد یا دریافت‌کننده چه کسی است؟');if(/قرارداد/.test(v('smartType'))&&!n('smartAmount'))missing.push('مبلغ قرارداد چقدر است؟');if(!v('smartDate'))missing.push('تاریخ سند چه زمانی است؟');const box=document.getElementById('smartQuestions');if(box)box.innerHTML=missing.length?`<strong>برای کامل‌شدن:</strong><ul>${missing.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<strong class="ready">اطلاعات اصلی کامل است؛ حالا بایگانی را بزن.</strong>';return missing}
async function saveSmartDocument(){analyzeSmartDocument();const missing=updateSmartQuestions();if(missing.length)return toast('اطلاعات سند هنوز کامل نیست');const file=pendingSmartFile,id=uid(),meta={id,name:file.name,title:v('smartTitle')||v('smartType'),project:v('smartProject'),party:v('smartPerson'),docType:v('smartType'),date:v('smartDate'),amount:n('smartAmount'),size:`${Math.max(1,Math.round(file.size/1024))} KB`,type:file.type||''};const summary=`${meta.docType} «${meta.title}» برای پروژه ${meta.project}${meta.party?'، طرف سند '+meta.party:''}${meta.amount?'، مبلغ '+money(meta.amount):''}`;if(!confirm(`${summary}\n\nبایگانی شود؟`))return;memoryFiles.set(id,{id,blob:file,type:file.type,name:file.name});try{await storeFile(id,file)}catch{}db.documents.unshift(meta);if(meta.docType==='قرارداد پیمانکار'&&meta.party&&meta.amount)db.contracts.push({id:uid(),title:meta.title,project:meta.project,party:meta.party,amount:meta.amount,status:'در حال اجرا',date:meta.date});save();closeSmartUpload();toast('سند در پروژه بایگانی شد');render()}
const dashboardBeforeInbox=dashboard;dashboard=function(){return dashboardBeforeInbox().replace('</main>',`${smartInboxPanel()}</main>`)}
const projectDetailBeforeInbox=projectDetail;projectDetail=function(){const p=db.projects.find(x=>Number(x.id)===selectedProjectId),html=projectDetailBeforeInbox();return p?html.replace('<section class="detail-section"><h3>پیمانکاران',`${smartInboxPanel(p.name)}<section class="detail-section"><h3>پیمانکاران`):html}
const dashboardWithInboxAtBottom=dashboard;dashboard=function(){let html=dashboardWithInboxAtBottom(),panel=smartInboxPanel();html=html.replace(panel,'');html=html.replace('<main class="phone-content">',`<main class="phone-content">${panel}`);html=html.replace('<main class="content">',`<main class="content">${panel}`);return html}
const smartUploadBase=openSmartUpload;openSmartUpload=function(project=''){smartUploadBase(project);const type=document.getElementById('smartType');if(type){type.innerHTML='<option value="">انتخاب کن</option><option>قرارداد پیمانکار</option><option>قرارداد کارفرما</option><option>فاکتور خرید</option><option>رسید پرداخت</option><option>رسید واریزی</option><option>سند مالی</option><option>گزارش کارگاه</option><option>تصویر پروژه</option><option>سایر</option>'}const command=document.getElementById('smartDocCommand');if(command)command.placeholder='مثلاً: این فاکتور خرید مصالح برای پروژه نمونه، مبلغ سی میلیون تومان است'}
const smartAnalyzeBase=analyzeSmartDocument;analyzeSmartDocument=function(){smartAnalyzeBase();const text=document.getElementById('smartDocCommand')?.value||'';if(/واریزی|دریافت|واریز.*کارفرما/.test(text))setSelectValue('smartType','رسید واریزی');else if(/سند مالی/.test(text))setSelectValue('smartType','سند مالی');updateSmartQuestions()}
const smartQuestionsBase=updateSmartQuestions;updateSmartQuestions=function(){const missing=smartQuestionsBase(),type=v('smartType');if(/فاکتور|رسید|سند مالی/.test(type)&&!n('smartAmount')&&!missing.includes('مبلغ سند چقدر است؟'))missing.push('مبلغ سند چقدر است؟');const box=document.getElementById('smartQuestions');if(box)box.innerHTML=missing.length?`<strong>برای کامل‌شدن:</strong><ul>${missing.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<strong class="ready">اطلاعات اصلی کامل است؛ حالا بایگانی را بزن.</strong>';return missing}
saveSmartDocument=async function(){analyzeSmartDocument();const missing=updateSmartQuestions();if(missing.length)return toast('اطلاعات سند هنوز کامل نیست');const file=pendingSmartFile,id=uid(),meta={id,name:file.name,title:v('smartTitle')||v('smartType'),project:v('smartProject'),party:v('smartPerson'),docType:v('smartType'),date:v('smartDate'),amount:n('smartAmount'),size:`${Math.max(1,Math.round(file.size/1024))} KB`,type:file.type||''};const summary=`${meta.docType} «${meta.title}» برای پروژه ${meta.project}${meta.party?'، طرف سند '+meta.party:''}${meta.amount?'، مبلغ '+money(meta.amount)+' ('+numberToPersianWords(meta.amount)+' تومان)':''}`;if(!confirm(`${summary}\n\nاطلاعات درست است و ثبت شود؟`))return;memoryFiles.set(id,{id,blob:file,type:file.type,name:file.name});try{await storeFile(id,file)}catch{}db.documents.unshift(meta);if(meta.docType==='قرارداد پیمانکار'&&meta.party&&meta.amount)db.contracts.push({id:uid(),title:meta.title,project:meta.project,party:meta.party,amount:meta.amount,status:'در حال اجرا',date:meta.date});if(/فاکتور خرید|رسید پرداخت|رسید واریزی|سند مالی/.test(meta.docType)&&meta.amount){const income=meta.docType==='رسید واریزی';db.transactions.push({id:uid(),project:meta.project,party:meta.party||meta.title,category:meta.docType,amount:meta.amount,date:meta.date,kind:income?'income':'expense',note:`ثبت از سند: ${meta.name}`})}save();closeSmartUpload();toast('سند و اطلاعات مالی ثبت شد');render()}
function numberToPersianWords(value){const n=Math.round(Number(value)||0);if(!n)return'صفر';const ones=['','یک','دو','سه','چهار','پنج','شش','هفت','هشت','نه','ده','یازده','دوازده','سیزده','چهارده','پانزده','شانزده','هفده','هجده','نوزده'],tens=['','','بیست','سی','چهل','پنجاه','شصت','هفتاد','هشتاد','نود'],hundreds=['','صد','دویست','سیصد','چهارصد','پانصد','ششصد','هفتصد','هشتصد','نهصد'],scales=['','هزار','میلیون','میلیارد','تریلیون'];function under1000(x){const a=[];if(x>=100){a.push(hundreds[Math.floor(x/100)]);x%=100}if(x<20){if(x)a.push(ones[x])}else{a.push(tens[Math.floor(x/10)]);if(x%10)a.push(ones[x%10])}return a.join(' و ')}let x=n,i=0,parts=[];while(x>0){const chunk=x%1000;if(chunk)parts.unshift(`${under1000(chunk)}${scales[i]?' '+scales[i]:''}`);x=Math.floor(x/1000);i++}return parts.join(' و ')}
function formatAmountInput(input){const raw=normalizeDigits(input.value).replace(/[^0-9]/g,''),num=Number(raw||0);input.value=raw?new Intl.NumberFormat('fa-IR').format(num):'';let hint=input.parentElement.querySelector('.amount-words');if(!hint){hint=document.createElement('small');hint.className='amount-words';input.insertAdjacentElement('afterend',hint)}hint.textContent=raw?`${numberToPersianWords(num)} تومان`:''}
document.addEventListener('input',e=>{if(e.target.matches('input[inputmode="numeric"]'))formatAmountInput(e.target)});document.addEventListener('focusin',e=>{if(e.target.matches('input[inputmode="numeric"]'))formatAmountInput(e.target)});
function openAmountEditor(kind,id){const row=(kind==='transaction'?db.transactions:db.contracts).find(x=>Number(x.id)===Number(id));if(!row)return;document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="amountEditor"><div class="dialog"><div class="dialog-head"><h2>اصلاح مبلغ</h2><button class="close" onclick="document.getElementById('amountEditor').remove()">×</button></div><div class="field"><label>مبلغ صحیح به تومان</label><input id="editAmountValue" inputmode="numeric" value="${fa(row.amount)}"></div><div class="dialog-actions"><button class="btn primary" onclick="saveEditedAmount('${kind}',${Number(id)})">ذخیره مبلغ</button><button class="btn" onclick="document.getElementById('amountEditor').remove()">انصراف</button></div></div></div>`);formatAmountInput(document.getElementById('editAmountValue'))}
function saveEditedAmount(kind,id){const row=(kind==='transaction'?db.transactions:db.contracts).find(x=>Number(x.id)===Number(id)),amount=n('editAmountValue');if(!row||!amount)return toast('مبلغ صحیح را وارد کن');if(!confirm(`مبلغ جدید: ${money(amount)}\n${numberToPersianWords(amount)} تومان\n\nذخیره شود؟`))return;row.amount=amount;save();document.getElementById('amountEditor')?.remove();toast('مبلغ اصلاح شد');render()}
transactionReportTable=function(rows){return `<div class="report-table">${rows.slice().reverse().map(x=>`<article><div><strong>${esc(x.category)}</strong><small>${esc(x.date)} • ${esc(x.party)}</small><button class="edit-amount" onclick="openAmountEditor('transaction',${Number(x.id)})">✎ اصلاح مبلغ</button></div><span class="${x.kind==='expense'?'out':''}">${x.kind==='income'?'+':'−'} ${money(x.amount)}</span></article>`).join('')||empty()}</div>`}
finance=function(){const t=totals(),rows=db.transactions.filter(x=>[x.project,x.party,x.category].some(v=>(v||'').includes(filter)));return layout(`<div class="section-head"><div><h2>امور مالی</h2><p>برای اصلاح هر مبلغ روی «اصلاح مبلغ» بزن</p></div><div class="toolbar"><input class="search" placeholder="جست‌وجوی مالی" value="${esc(filter)}" oninput="filter=this.value;render()"><button type="button" class="btn primary" onclick="openForm('transaction')">ثبت تراکنش</button></div></div><div class="detail-kpis"><div><small>دریافتی</small><strong>${money(t.income)}</strong></div><div><small>پرداختی</small><strong>${money(t.expense)}</strong></div><div><small>تراز</small><strong>${money(t.income-t.expense)}</strong></div></div>${transactionReportTable(rows)}`,'امور مالی')}
contracts=function(){return layout(`<div class="section-head"><div><h2>قراردادها</h2><p>مبلغ قرارداد و امکان اصلاح مستقیم</p></div><button class="btn primary" onclick="openForm('contract')">قرارداد جدید</button></div><div class="phone-list">${db.contracts.map(x=>`<article class="phone-row"><div class="phone-row-head"><strong>${esc(x.title)}</strong><span class="pill">${esc(x.status)}</span></div><div class="phone-row-meta">${esc(x.project)}<br>${esc(x.party)} • ${esc(x.date)}</div><div class="phone-amount">${money(x.amount)}</div><button class="edit-amount" onclick="openAmountEditor('contract',${Number(x.id)})">✎ اصلاح مبلغ قرارداد</button></article>`).join('')||empty()}</div>`,'قراردادها')}
let pendingEntities={project:null,person:null};
const smartUploadEntityBase=openSmartUpload;openSmartUpload=function(project=''){smartUploadEntityBase(project);pendingEntities={project:null,person:null};const projectSelect=document.getElementById('smartProject'),personSelect=document.getElementById('smartPerson');if(projectSelect){const input=document.createElement('input');input.id='smartProject';input.setAttribute('list','smartProjectList');input.placeholder='پروژه موجود یا نام پروژه جدید';input.value=projectSelect.value||project;input.insertAdjacentHTML('afterend',`<datalist id="smartProjectList">${db.projects.map(x=>`<option value="${esc(x.name)}">`).join('')}</datalist>`);projectSelect.replaceWith(input)}if(personSelect){const input=document.createElement('input');input.id='smartPerson';input.setAttribute('list','smartPersonList');input.placeholder='شخص موجود یا نام شخص جدید';input.insertAdjacentHTML('afterend',`<datalist id="smartPersonList">${db.people.map(x=>`<option value="${esc(x.name)}">`).join('')}</datalist>`);personSelect.replaceWith(input)}}
setSelectValue=function(id,value){const el=document.getElementById(id);if(!el||!value)return;if(el.tagName==='SELECT'){const option=[...el.options].find(o=>o.value===value||o.textContent===value);if(option)el.value=option.value}else el.value=value}
function extractNamedEntity(text,words){const marker=words.join('|'),patterns=[new RegExp(`(?:${marker})(?:\\s+جدید)?(?:\\s+(?:ایجاد|ثبت|تعریف|اضافه|بساز)(?:\\s+کن)?)?(?:\\s+(?:به نام|بنام|اسمش|نام))\\s+([^،,.]+)`),new RegExp(`(?:به نام|بنام|اسمش)\\s+([^،,.]+?)\\s+(?:را|برای|به عنوان|${marker})`)];for(const re of patterns){const m=text.match(re);if(m)return m[1].replace(/\\s+(?:برای|در)\\s+پروژه.*$/,'').replace(/\\s+(?:جوشکار|بنا|برقکار|فروشنده|مسئول فروش|نگهبان|کارگر).*$/,'').trim()}return''}
function inferPartyRole(text){return ['مسئول فروش','فروشنده','جوشکار','بنا','برقکار','لوله‌کش','نگهبان','کارگر','نقاش','گچ‌کار','سرامیک‌کار','پیمانکار'].find(x=>text.includes(x))||'طرف حساب'}
const smartAnalyzeEntitiesBase=analyzeSmartDocument;analyzeSmartDocument=function(){smartAnalyzeEntitiesBase();const text=document.getElementById('smartDocCommand')?.value.trim()||'';let project=db.projects.find(x=>text.includes(x.name)),person=db.people.find(x=>text.includes(x.name));const parsed=PeymanyarCommand.parse(text,db,todayFa());let projectName=project?.name||'',personName=person?.name||'';if(!projectName&&parsed.intent==='project_create'&&parsed.name)projectName=parsed.name;if(!projectName)projectName=extractNamedEntity(text,['پروژه']);if(!personName)personName=extractNamedEntity(text,['پیمانکار','فروشنده','مسئول فروش','طرف حساب','نیرو','فرد']);if(projectName){setSelectValue('smartProject',projectName);if(!db.projects.some(x=>x.name===projectName))pendingEntities.project={name:projectName}}if(personName){setSelectValue('smartPerson',personName);if(!db.people.some(x=>x.name===personName))pendingEntities.person={name:personName,role:inferPartyRole(text)}}updateSmartQuestions();showPendingEntities()}
const analyzeSmartEntitiesFinal=analyzeSmartDocument;analyzeSmartDocument=function(){pendingEntities={project:null,person:null};return analyzeSmartEntitiesFinal()}
function showPendingEntities(){const box=document.getElementById('smartQuestions');if(!box)return;const items=[];if(pendingEntities.project)items.push(`پروژه جدید «${esc(pendingEntities.project.name)}» ساخته می‌شود.`);if(pendingEntities.person)items.push(`${esc(pendingEntities.person.role)} جدید «${esc(pendingEntities.person.name)}» ساخته می‌شود.`);if(items.length)box.insertAdjacentHTML('afterbegin',`<div class="entity-preview"><strong>ایجاد هم‌زمان:</strong>${items.map(x=>`<div>＋ ${x}</div>`).join('')}</div>`)}
const smartUploadCategoryBase=openSmartUpload;openSmartUpload=function(project=''){smartUploadCategoryBase(project);const meta=document.querySelector('.smart-meta'),title=document.getElementById('smartTitle')?.closest('.field');if(meta&&!document.getElementById('smartCategory')){const field=document.createElement('div');field.className='field';field.innerHTML='<label>بابت / دسته مالی</label><input id="smartCategory" list="smartCategoryList" placeholder="مثلاً کرایه جرثقیل"><datalist id="smartCategoryList"><option value="خرید مصالح"><option value="خرید ابزار"><option value="خرید لوازم"><option value="کرایه جرثقیل"><option value="کرایه وانت"><option value="کرایه ابزارآلات"><option value="حمل‌ونقل"><option value="دستمزد"><option value="سوخت"></datalist>';meta.insertBefore(field,title||null)}}
function categoryFromDescription(text){const known=['کرایه جرثقیل','کرایه وانت','کرایه ابزارآلات','کرایه ابزار','خرید مصالح','خرید ابزار','خرید لوازم','حمل و نقل','حمل‌ونقل','دستمزد','سوخت','هزینه غذا','تعمیرات'];const direct=known.find(x=>text.includes(x));if(direct)return direct;const m=text.match(/(?:بابت|برای هزینه|هزینه(?:‌ی| ی)?)\s+([^،,.]+?)(?=\s+(?:برای|در)\s+پروژه|\s+به مبلغ|\s+مبلغ|\s+تومان|$)/);return m?m[1].trim():''}
const smartAnalyzeCategoryBase=analyzeSmartDocument;analyzeSmartDocument=function(){smartAnalyzeCategoryBase();const text=document.getElementById('smartDocCommand')?.value.trim()||'',category=categoryFromDescription(text),field=document.getElementById('smartCategory'),title=document.getElementById('smartTitle');if(category&&field)field.value=category;if(category&&title&&(!title.value||/^(?:فاکتور خرید|رسید پرداخت|رسید واریزی|سند مالی)$/.test(title.value)))title.value=category;updateSmartQuestions();showPendingEntities()}
updateSmartQuestions=function(){const missing=[],type=v('smartType');if(!pendingSmartFile)missing.push('فایل را انتخاب کن');if(!type)missing.push('نوع سند چیست؟');if(!v('smartProject'))missing.push('مربوط به کدام پروژه است؟');if(/قرارداد/.test(type)&&!v('smartPerson'))missing.push('طرف قرارداد چه کسی است؟');if(/قرارداد|فاکتور|رسید|سند مالی/.test(type)&&!n('smartAmount'))missing.push('مبلغ سند چقدر است؟');if(/فاکتور|رسید|سند مالی/.test(type)&&!v('smartCategory'))missing.push('این مبلغ بابت چه چیزی است؟');if(!v('smartDate'))missing.push('تاریخ سند چه زمانی است؟');const box=document.getElementById('smartQuestions');if(box)box.innerHTML=missing.length?`<strong>برای کامل‌شدن:</strong><ul>${missing.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<strong class="ready">اطلاعات اصلی کامل است؛ حالا بایگانی را بزن.</strong>';return missing}
saveSmartDocument=async function(){analyzeSmartDocument();const missing=updateSmartQuestions();showPendingEntities();if(missing.length)return toast('اطلاعات سند هنوز کامل نیست');const file=pendingSmartFile,id=uid(),projectName=v('smartProject'),personName=v('smartPerson'),category=v('smartCategory')||v('smartTitle')||v('smartType'),projectExists=db.projects.some(x=>x.name===projectName),personExists=!personName||db.people.some(x=>x.name===personName),role=pendingEntities.person?.role||'طرف حساب',meta={id,name:file.name,title:v('smartTitle')||category,category,project:projectName,party:personName,docType:v('smartType'),date:v('smartDate'),amount:n('smartAmount'),size:`${Math.max(1,Math.round(file.size/1024))} KB`,type:file.type||''};const creations=[!projectExists&&`پروژه جدید «${projectName}»`,personName&&!personExists&&`${role} جدید «${personName}»`,category&&`دسته مالی «${category}»`].filter(Boolean);const summary=`${creations.length?'ایجاد/استفاده: '+creations.join('، ')+'\n':''}${meta.docType} برای پروژه ${meta.project}${meta.party?'، طرف سند '+meta.party:''}\nبابت: ${meta.category}${meta.amount?'\nمبلغ '+money(meta.amount)+' ('+numberToPersianWords(meta.amount)+' تومان)':''}`;if(!confirm(`${summary}\n\nاطلاعات درست است و ثبت شود؟`))return;if(!projectExists)db.projects.push({id:uid(),name:projectName,client:'ثبت نشده',location:'',budget:0,progress:0,status:'فعال',start:meta.date});if(personName&&!personExists)db.people.push({id:uid(),name:personName,role,phone:'',project:projectName});memoryFiles.set(id,{id,blob:file,type:file.type,name:file.name});try{await storeFile(id,file)}catch{}db.documents.unshift(meta);if(meta.docType==='قرارداد پیمانکار'&&meta.party&&meta.amount)db.contracts.push({id:uid(),title:meta.title,project:meta.project,party:meta.party,amount:meta.amount,status:'در حال اجرا',date:meta.date});if(/فاکتور خرید|رسید پرداخت|رسید واریزی|سند مالی/.test(meta.docType)&&meta.amount){const income=meta.docType==='رسید واریزی';db.transactions.push({id:uid(),project:meta.project,party:meta.party||meta.category,category:meta.category,amount:meta.amount,date:meta.date,kind:income?'income':'expense',note:`ثبت از سند: ${meta.name}`})}save();closeSmartUpload();toast('سند و دسته مالی ثبت شد');render()}

// v16: expense descriptions are complete documents even without a contractor or amount.
function expenseCategoryFromText(text){const cleaned=(text||'').replace(/[،,.]/g,' ').replace(/\s+/g,' ').trim();const known=['نگهبانی کارگاه','نگهبانی و کارگاه','نگهبانی','کرایه جرثقیل','کرایه وانت','کرایه ابزارآلات','کرایه ابزار','خرید مصالح','خرید ابزار','خرید لوازم','حمل و نقل','حمل‌ونقل','دستمزد','سوخت','هزینه غذا','تعمیرات'];const direct=known.find(x=>cleaned.includes(x));if(direct)return direct;const match=cleaned.match(/(?:هزینه(?:‌ی| ی)?|بابت)\s+(.+?)(?=\s+(?:برای\s+)?پروژه\s+|\s+به مبلغ|\s+مبلغ|\s+تومان|$)/)||cleaned.match(/((?:کرایه|جریمه|نگهبانی|خرید|دستمزد|حمل)\s*.+?)(?=\s+(?:برای\s+)?پروژه\s+|\s+به مبلغ|\s+مبلغ|\s+تومان|$)/);return match?match[1].replace(/^(?:کرد|کردِ)\s+/,'').trim():''}
const smartAnalyzeExpenseBase=analyzeSmartDocument;analyzeSmartDocument=function(){smartAnalyzeExpenseBase();const text=document.getElementById('smartDocCommand')?.value.trim()||'';if(/هزینه|کرایه|نگهبان|نگهبانی|دستمزد|خرید|فاکتور/.test(text)&&!v('smartType'))setSelectValue('smartType',/فاکتور|خرید/.test(text)?'فاکتور خرید':'سند مالی');const category=expenseCategoryFromText(text)||categoryFromDescription(text);if(category){const categoryField=document.getElementById('smartCategory'),title=document.getElementById('smartTitle');if(categoryField)categoryField.value=category;if(title&&(!title.value||/^(?:سند مالی|فاکتور خرید)$/.test(title.value)))title.value=category}updateSmartQuestions();showPendingEntities()}
updateSmartQuestions=function(){const missing=[],type=v('smartType');if(!pendingSmartFile)missing.push('فایل را انتخاب کن');if(!type)missing.push('نوع سند چیست؟');if(!v('smartProject'))missing.push('مربوط به کدام پروژه است؟');if(/قرارداد/.test(type)&&!v('smartPerson'))missing.push('طرف قرارداد چه کسی است؟');if(/قرارداد/.test(type)&&!n('smartAmount'))missing.push('مبلغ قرارداد چقدر است؟');if(/فاکتور|رسید|سند مالی/.test(type)&&!v('smartCategory'))missing.push('این سند بابت چه چیزی است؟');if(!v('smartDate'))missing.push('تاریخ سند چه زمانی است؟');const box=document.getElementById('smartQuestions');if(box)box.innerHTML=missing.length?`<strong>برای کامل‌شدن:</strong><ul>${missing.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<strong class="ready">اطلاعات اصلی کامل است؛ حالا بایگانی را بزن.</strong>';return missing}

// v17: persistent, visible financial categories and on-device OCR for bank screenshots.
function allFinancialCategories(){return[...new Set([...(db.categories||[]),...db.transactions.map(x=>x.category),...db.documents.map(x=>x.category)].filter(Boolean))]}
const financeCategoryBase=finance;finance=function(){const html=financeCategoryBase(),cats=allFinancialCategories();if(!cats.length)return html;const bar=`<section class="category-strip"><strong>دسته‌های مالی</strong><div>${cats.map(x=>`<button type="button" onclick="filter='${esc(x)}';render()">${esc(x)}</button>`).join('')}</div></section>`;return html.replace('<div class="detail-kpis">',bar+'<div class="detail-kpis">')}
const smartSaveCategoryBase=saveSmartDocument;saveSmartDocument=async function(){analyzeSmartDocument();const category=v('smartCategory');if(category&&!db.categories.includes(category)){db.categories.push(category);save()}return smartSaveCategoryBase()}
let smartOcrBusy=false;
function loadTesseract(){if(window.Tesseract)return Promise.resolve(window.Tesseract);return new Promise((resolve,reject)=>{const old=document.getElementById('tesseractLoader');if(old){old.addEventListener('load',()=>resolve(window.Tesseract),{once:true});old.addEventListener('error',reject,{once:true});return}const script=document.createElement('script');script.id='tesseractLoader';script.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';script.onload=()=>resolve(window.Tesseract);script.onerror=reject;document.head.appendChild(script)})}
function ocrDigits(text){return normalizeDigits((text||'').replace(/[٬,]/g,''))}
function extractReceiptFields(text){const raw=ocrDigits(text),amountMatches=[...raw.matchAll(/(?:مبلغ|جمع|برداشت|واریز|انتقال)[^\d]{0,25}(\d{4,15})\s*(ریال|تومان)?/g)],fallback=[...raw.matchAll(/\b(\d{5,15})\s*(ریال|تومان)\b/g)],candidate=(amountMatches.at(-1)||fallback.at(-1)),amount=candidate?Number(candidate[1])/(candidate[2]==='ریال'?10:1):0,dateMatch=raw.match(/(1[34]\d{2})[\/\-.](\d{1,2})[\/\-.](\d{1,2})/),tracking=(raw.match(/(?:پیگیری|مرجع|رهگیری)[^\d]{0,12}(\d{5,30})/)||[])[1]||'';return{amount,date:dateMatch?`${dateMatch[1]}/${dateMatch[2].padStart(2,'0')}/${dateMatch[3].padStart(2,'0')}`:'',tracking}}
async function readSmartReceiptImage(){if(smartOcrBusy||!pendingSmartFile||!pendingSmartFile.type.startsWith('image/'))return;smartOcrBusy=true;const box=document.getElementById('smartQuestions');if(box)box.innerHTML='<strong>در حال خواندن مبلغ و تاریخ از تصویر…</strong><p>بار اول ممکن است کمی طول بکشد.</p>';try{const OCR=await loadTesseract();if(!OCR)throw new Error('ocr-unavailable');const worker=await OCR.createWorker('fas+eng',1,{logger:m=>{if(box&&m.status==='recognizing text')box.innerHTML=`<strong>در حال خواندن تصویر… ${fa(Math.round((m.progress||0)*100))}٪</strong>`}}),result=await worker.recognize(pendingSmartFile);await worker.terminate();const text=result.data.text||'',fields=extractReceiptFields(text);if(fields.amount){const amount=document.getElementById('smartAmount');amount.value=fa(Math.round(fields.amount));amount.dispatchEvent(new Event('input',{bubbles:true}))}if(fields.date)document.getElementById('smartDate').value=fields.date;if(!v('smartType'))setSelectValue('smartType',/واریز|دریافت/.test(text)?'رسید واریزی':'رسید پرداخت');const command=document.getElementById('smartDocCommand');if(command&&!command.value.trim())command.value=`رسید بانکی${fields.tracking?' شماره پیگیری '+fields.tracking:''}`;analyzeSmartDocument();toast(fields.amount||fields.date?'اطلاعات رسید از تصویر خوانده شد':'متن تصویر خوانده شد؛ موارد نامشخص را تکمیل کن')}catch(e){updateSmartQuestions();toast('خواندن خودکار تصویر انجام نشد؛ توضیح سند را بنویس')}finally{smartOcrBusy=false}}
const smartFileOcrBase=smartFileSelected;smartFileSelected=function(input){smartFileOcrBase(input);if(pendingSmartFile?.type.startsWith('image/'))readSmartReceiptImage()}
const baseParseQuick=parseQuick;parseQuick=function(){const input=document.getElementById('quickText'),box=document.getElementById('parsedResult');if(!input||!box)return;const text=input.value.trim();if(!text)return toast('ابتدا فرمان را بگو یا بنویس');const cmd=PeymanyarCommand.parse(text,db,todayFa());if(cmd.intent!=='financial_query')return baseParseQuick();const rows=reportRows({project:cmd.project,person:cmd.person,dateFrom:cmd.dateFrom,dateTo:cmd.dateTo}),sum=reportSummary(rows),a=contractAccount(cmd.project,cmd.person);activeReport={title:`گزارش مالی${cmd.project?' پروژه '+cmd.project:''}${cmd.person?' - '+cmd.person:''}`,rows,project:cmd.project,person:cmd.person,dateFrom:cmd.dateFrom,dateTo:cmd.dateTo};box.innerHTML=`<div class="parsed"><div class="command-title"><strong>${esc(activeReport.title)}</strong><span class="command-badge">${fa(rows.length)} ردیف</span></div><div class="parsed-grid"><div><small>دریافتی</small>${money(sum.received)}</div><div><small>پرداخت</small>${money(sum.paid)}</div><div><small>قرارداد</small>${money(a.contract)}</div><div><small>مانده قرارداد</small>${money(a.remain)}</div></div><div class="report-actions"><button onclick="showReportModal()">نمایش ریز گزارش</button><button onclick="exportActiveCSV()">Excel</button><button onclick="exportActiveWord()">Word</button><button onclick="printActiveReport()">PDF</button></div></div>`}
const oldRender=render;render=function(){const view={dashboard,projects,projectDetail,people,personDetail,finance,contracts,daily,documents,settings}[page];if(view)document.getElementById('app').innerHTML=view();else oldRender()}
function applyDeviceMode(){const phone=/iPhone|iPod|Android.*Mobile|Windows Phone/i.test(navigator.userAgent||'')||Math.min(screen.width||9999,screen.height||9999)<=600||matchMedia('(pointer:coarse) and (max-device-width: 900px)').matches;document.documentElement.classList.toggle('mobile-device',phone)}
applyDeviceMode();window.addEventListener('resize',applyDeviceMode);window.addEventListener('orientationchange',applyDeviceMode);
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.getRegistrations().then(rows=>rows.forEach(r=>r.unregister())).catch(()=>{}));
if('caches'in window)window.addEventListener('load',()=>caches.keys().then(keys=>Promise.all(keys.map(k=>caches.delete(k)))).catch(()=>{}));
render();
