(function(){
 'use strict';let rows=[];
 const fresh=()=>({project:v('bulkDefaultProject'),party:'',category:'تنخواه',amount:'',date:v('bulkEntryDate'),note:'',kind:'expense',selected:true,ack:false});
 const oldOpen=openBulkCash;openBulkCash=function(project=''){oldOpen(project);rows=[];const box=document.getElementById('bulkReview');box.insertAdjacentHTML('beforebegin',`<section class="bulk-entry-controls"><label>تاریخ پیش‌فرض (اختیاری)<input id="bulkEntryDate" placeholder="۱۴۰۵/۰۷/۰۱" inputmode="numeric"></label><button class="btn" onclick="bulkAddRow()">＋ سطر دستی</button><p>هر خانه را لمس کن و ویرایش کن. تاریخ نامشخص باید تأیید شود؛ نام جدید با تأیید تو ساخته می‌شود.</p></section><datalist id="bulkPeople">${db.people.map(p=>`<option value="${esc(p.name)}">`).join('')}</datalist><datalist id="bulkProjects">${db.projects.map(p=>`<option value="${esc(p.name)}">`).join('')}</datalist>`);document.querySelector('#bulkCashModal .dialog-actions button')?.setAttribute('onclick','reviewBulkCash()');bulkAddRow()};
 function amount(value){const s=normalizeDigits(String(value)).replace(/[٬,\s]/g,'');return /^\d+$/.test(s)?Number(s):PeymanyarCommand.amountOf(String(value)+' تومان')}
 function duplicate(row,index){const key=r=>[normalizedProjectName(r.project),personIdentityKey(r.party),normalizeDateValue(r.date),amount(r.amount),r.kind].join('|');return db.transactions.some(r=>key(r)===key(row))||rows.some((r,i)=>i<index&&key(r)===key(row)&&amount(r.amount)>0)}
 function findProject(name){return db.projects.find(p=>[p.name,...(p.aliases||[])].some(n=>normalizedProjectName(n)===normalizedProjectName(name)))}
 function errors(row){return [!row.project.trim()&&'پروژه را انتخاب یا وارد کن',!row.party.trim()&&'طرف حساب را وارد کن',!(amount(row.amount)>0)&&'مبلغ معتبر وارد کن',!normalizeDateValue(row.date)&&'تاریخ را وارد یا تأیید کن'].filter(Boolean)}
 function warnings(row,i){return [...errors(row),row.project.trim()&&!findProject(row.project)&&'پروژه جدید با تأیید هنگام ثبت ساخته می‌شود',!knownPerson(row.party)&&row.party.trim()&&'شخص جدید با ثبت نهایی ساخته می‌شود',duplicate(row,i)&&'احتمال تکراری؛ تأیید کن'].filter(Boolean)}
 window.bulkPicker=function(input,i,key,filter=false){document.querySelectorAll('.bulk-picker').forEach(el=>el.remove());const choices=key==='project'?db.projects:db.people;const query=personIdentityKey(input.value);const items=filter?choices.filter(p=>[p.name,...(p.aliases||[])].some(n=>personIdentityKey(n).includes(query))):choices;const panel=document.createElement('div');panel.className='bulk-picker';panel.setAttribute('role','group');panel.setAttribute('aria-label',key==='project'?'انتخاب پروژه':'انتخاب طرف حساب');const hint=document.createElement('small');hint.textContent='انتخاب کن یا نام جدید را در خانه تایپ کن';panel.appendChild(hint);for(const item of items){const button=document.createElement('button');button.type='button';button.className='btn';button.textContent=item.name;button.onpointerdown=e=>e.preventDefault();button.onmousedown=e=>e.preventDefault();button.onclick=()=>bulkCell(i,key,item.name);panel.appendChild(button)}if(!items.length){const empty=document.createElement('small');empty.textContent='نامی پیدا نشد؛ می‌توانی نام جدید وارد کنی';panel.appendChild(empty)}input.after(panel)};
 function draw(){const box=document.getElementById('bulkReview');if(!box)return;box.innerHTML=`<div class="ledger-scroll"><table class="ledger-table bulk-edit-table"><thead><tr>${['انتخاب','ردیف','تاریخ شمسی','پروژه','طرف حساب','شرح / بابت','مبلغ (تومان)','نوع','توضیح','کنترل'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr><td><input type="checkbox" ${r.selected?'checked':''} onchange="bulkCell(${i},'selected',this.checked)"></td><td>${fa(i+1)}<button onclick="bulkRemoveRow(${i})" aria-label="حذف سطر ${i+1}">×</button></td>${['date','project','party','category','amount','kind','note'].map(k=>`<td>${k==='kind'?`<select onchange="bulkCell(${i},'kind',this.value)"><option value="expense" ${r.kind==='expense'?'selected':''}>پرداخت</option><option value="income" ${r.kind==='income'?'selected':''}>دریافت</option></select>`:`<input aria-label="${k} ردیف ${i+1}" value="${esc(r[k])}" ${k==='date'?'data-persian-calendar="1" onclick="PeymanyarCalendar.open(this)"':k==='party'||k==='project'?`onfocus="bulkPicker(this,${i},'${k}')" oninput="bulkPicker(this,${i},'${k}',true)" autocomplete="off"`:''} ${k==='amount'||k==='date'?'inputmode="numeric"':''} onchange="bulkCell(${i},'${k}',this.value)" onkeydown="bulkNext(event,${i},'${k}')">${k==='date'&&!r.date&&i&&normalizeDateValue(rows[i-1].date)?`<button onclick="bulkCell(${i},'date',${esc(JSON.stringify(rows[i-1].date))})">تاریخ سطر قبل: ${esc(rows[i-1].date)}</button>`:''}`}</td>`).join('')}<td>${warnings(r,i).map(m=>`<small>${esc(m)}</small>`).join('')||'آماده'}${duplicate(r,i)?`<label><input type="checkbox" ${r.ack?'checked':''} onchange="bulkCell(${i},'ack',this.checked)"> تأیید تکرار</label>`:''}</td></tr>`).join('')}</tbody></table></div><p>جمع انتخاب‌شده: ${money(rows.filter(r=>r.selected).reduce((s,r)=>s+amount(r.amount),0))} • ${fa(rows.filter(r=>r.selected&&!errors(r).length).length)} سطر کامل</p><button class="btn" onclick="bulkAddRow()">＋ سطر بعدی</button><button class="btn primary" onclick="saveBulkCash()">بررسی و ثبت نهایی</button>`}
 window.bulkCell=function(i,key,value){if(!rows[i])return;rows[i][key]=value;if(key!=='ack')rows[i].ack=false;draw()};
 window.bulkAddRow=function(){rows.push(fresh());draw()};window.bulkRemoveRow=function(i){rows.splice(i,1);draw()};
 window.bulkNext=function(e,i,key){if(e.key==='Enter'){e.preventDefault();e.target.dispatchEvent(new Event('change',{bubbles:true}));if(key==='note'&&i===rows.length-1)bulkAddRow();const keys=['date','project','party','category','amount','note'],at=keys.indexOf(key),next=at===keys.length-1?`date ردیف ${i+2}`:`${keys[at+1]} ردیف ${i+1}`;document.querySelector(`[aria-label="${next}"]`)?.focus()}};
 reviewBulkCash=function(){const text=v('quickText');if(!text)return toast('متن صوتی یا تایپی را وارد کن');const parsed=splitBulkCash(text.replace(/\s*ردیف بعدی?\s*/g,'\n')).map(line=>{const plan=PeymanyarCommand.parse(line,db,todayFa()),date=PeymanyarCommand.dateInfo(line,todayFa());return {...fresh(),project:plan.project||v('bulkDefaultProject'),party:plan.party||plan.person||'',category:plan.category||'تنخواه',amount:plan.amount||PeymanyarCommand.amountOf(line)||'',date:date.explicit?date.date:v('bulkEntryDate'),kind:plan.kind||'expense',note:line}});rows=rows.filter(r=>r.party||r.amount||r.note).concat(parsed);document.getElementById('quickText').value='';if(bulkVoiceSession&&!bulkVoiceSession.recording&&!bulkVoiceSession.pending)bulkVoiceSession=null;draw();toast('متن به جدول آمد؛ خانه‌های ناقص را کامل کن')};
 saveBulkCash=function(){if(bulkVoiceSession?.recording||bulkVoiceSession?.pending)return toast('ابتدا ضبط و تبدیل صدا را تمام کن');const chosen=rows.map((r,i)=>({r,i})).filter(x=>x.r.selected);if(!chosen.length)return toast('سطر انتخاب کن');if(chosen.some(({r,i})=>errors(r).length||duplicate(r,i)&&!r.ack))return toast('سطرهای ناقص یا تکراری را بررسی کن');const newNames=[...new Set(chosen.map(x=>x.r.party.trim()).filter(n=>!knownPerson(n)))];if(newNames.length&&!confirm('این افراد جدید ساخته شوند؟\n'+newNames.join('\n')))return;const newProjects=[...new Map(chosen.map(x=>x.r.project.trim()).filter(n=>!findProject(n)).map(n=>[normalizedProjectName(n),n])).values()];if(newProjects.length&&!confirm('این پروژه‌های جدید ساخته شوند؟\n'+newProjects.join('\n')))return;for(const {r}of chosen){let project=findProject(r.project);if(!project){project={id:uid(),name:r.project.trim(),client:'ثبت نشده',location:'',budget:0,progress:0,status:'فعال',start:normalizeDateValue(r.date),completeness:'draft'};db.projects.push(project)}let person=knownPerson(r.party);if(!person){person={id:uid(),name:r.party.trim(),role:'',project:project.name,projects:[project.name]};db.people.push(person)}person.projects=[...new Set([...(person.projects||[]),person.project,project.name].filter(Boolean))];db.transactions.push({id:uid(),personId:person.id,project:project.name,party:person.name,category:r.category||'تنخواه',amount:amount(r.amount),date:normalizeDateValue(r.date),dateSource:'explicit',kind:r.kind,note:r.note,source:'bulk-grid',status:'ثبت اولیه'});if(r.category&&!db.categories.includes(r.category))db.categories.push(r.category)}save();rows=[];closeBulkCash();render();toast(`${fa(chosen.length)} سطر ثبت و به حساب افراد و پروژه وصل شد`)};
 const commit=saveBulkCash;saveBulkCash=function(){if(bulkVoiceSession?.failed?.length)return toast('بخش صوتی ناموفق را دوباره تبدیل کن');if(v('quickText'))return toast('متن باقی‌مانده را با «بررسی فهرست» به جدول منتقل کن');return commit()};
})();
