(function(){
 'use strict';let rows=[];
 const fresh=()=>({_initialProject:v('bulkDefaultProject'),_initialDate:v('bulkEntryDate'),project:v('bulkDefaultProject'),party:'',category:'تنخواه',amount:'',date:v('bulkEntryDate'),note:'',kind:'expense',selected:true,ack:false});
 const oldOpen=openBulkCash;openBulkCash=function(project=''){oldOpen(project);rows=[];document.getElementById('bulkDefaultProject')?.addEventListener('change',()=>{const project=v('bulkDefaultProject');for(const row of rows){if(!row._projectEdited&&row.project===row._initialProject){row.project=project;row._initialProject=project}}draw()});const box=document.getElementById('bulkReview');box.insertAdjacentHTML('beforebegin',`<section class="bulk-entry-controls"><label>تاریخ پیش‌فرض (اختیاری)<input id="bulkEntryDate" placeholder="۱۴۰۵/۰۷/۰۱" inputmode="numeric"></label><button class="btn" onclick="bulkAddRow()">＋ سطر دستی</button><p>هر خانه را لمس کن و ویرایش کن. نام جدید خودکار ساخته می‌شود؛ سطر ناقص یا مشکوک هم ثبت می‌شود تا بعداً بررسی کنی.</p></section><datalist id="bulkPeople">${db.people.map(p=>`<option value="${esc(p.name)}">`).join('')}</datalist><datalist id="bulkProjects">${db.projects.map(p=>`<option value="${esc(p.name)}">`).join('')}</datalist>`);document.querySelector('#bulkCashModal .dialog-actions button')?.setAttribute('onclick','reviewBulkCash()');bulkAddRow()};
 function amount(value){const s=normalizeDigits(String(value)).replace(/[٬,\s]/g,'');return /^\d+$/.test(s)?Number(s):PeymanyarCommand.amountOf(String(value)+' تومان')}
 function dateValue(value){let text=normalizeDigits(String(value||'')).trim();if(/^\d{1,2}[\/-]\d{1,2}$/.test(text))text=normalizeDigits(todayFa()).match(/1[34]\d{2}/)[0]+'/'+text;const date=normalizeDateValue(text);if(!date)return '';const [,m,d]=date.split('/').map(Number);return m>=1&&m<=12&&d>=1&&d<=(m<=6?31:30)?date:''}
 function rowKey(r){const project=findProject(r.project),person=knownPerson(r.party);return [normalizedProjectName(project?.name||r.project),person?String(person.id):personIdentityKey(r.party),dateValue(r.date),amount(r.amount),r.kind].join('|')}
 function duplicate(row,index){if(!(amount(row.amount)>0)||!dateValue(row.date)||!row.party.trim())return false;return db.transactions.some(r=>rowKey(r)===rowKey(row))||rows.some((r,i)=>i<index&&rowKey(r)===rowKey(row))}
 function findProject(name){return db.projects.find(p=>[p.name,...(p.aliases||[])].some(n=>normalizedProjectName(n)===normalizedProjectName(name)))}
 function errors(row){return [!row.project.trim()&&'پروژه را انتخاب یا وارد کن',!row.party.trim()&&'طرف حساب را وارد کن',!(amount(row.amount)>0)&&'مبلغ معتبر وارد کن',!dateValue(row.date)&&'تاریخ را وارد یا تأیید کن'].filter(Boolean)}
 function warnings(row,i){return [...errors(row),row.project.trim()&&!findProject(row.project)&&'پروژه جدید خودکار ساخته می‌شود',!knownPerson(row.party)&&row.party.trim()&&'شخص جدید با ثبت نهایی ساخته می‌شود',duplicate(row,i)&&'مشکوک به تکرار؛ ثبت و بررسی بعدی'].filter(Boolean)}
 window.bulkPicker=function(input,i,key,filter=false){document.querySelectorAll('.bulk-picker').forEach(el=>el.remove());const choices=key==='project'?db.projects:db.people;const query=personIdentityKey(input.value);const items=filter?choices.filter(p=>[p.name,...(p.aliases||[])].some(n=>personIdentityKey(n).includes(query))):choices;const panel=document.createElement('div');panel.className='bulk-picker';panel.setAttribute('role','group');panel.setAttribute('aria-label',key==='project'?'انتخاب پروژه':'انتخاب طرف حساب');const hint=document.createElement('small');hint.textContent='انتخاب کن یا نام جدید را در خانه تایپ کن';panel.appendChild(hint);for(const item of items){const button=document.createElement('button');button.type='button';button.className='btn';button.textContent=item.name;button.onpointerdown=e=>e.preventDefault();button.onmousedown=e=>e.preventDefault();button.onclick=()=>{bulkCell(i,key,item.name);bulkAdvance(i,key)};panel.appendChild(button)}if(!items.length){const empty=document.createElement('small');empty.textContent='نامی پیدا نشد؛ می‌توانی نام جدید وارد کنی';panel.appendChild(empty)}input.after(panel)};
 function draw(){const box=document.getElementById('bulkReview');if(!box)return;const position=window.PeymanyarBulkGrid?.capture(box);box.innerHTML=`<div class="ledger-scroll"><table class="ledger-table bulk-edit-table"><thead><tr>${['انتخاب','ردیف','تاریخ شمسی','پروژه','طرف حساب','شرح / بابت','مبلغ (تومان)','نوع','توضیح','کنترل'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr><td><input type="checkbox" ${r.selected?'checked':''} onchange="bulkCell(${i},'selected',this.checked)"></td><td>${fa(i+1)}<button onclick="bulkRemoveRow(${i})" aria-label="حذف سطر ${i+1}">×</button></td>${['date','project','party','category','amount','kind','note'].map(k=>`<td>${k==='kind'?`<select aria-label="kind ردیف ${i+1}" onchange="bulkInput(this,${i},'kind')" onkeydown="bulkNext(event,${i},'kind')"><option value="expense" ${r.kind==='expense'?'selected':''}>پرداخت</option><option value="income" ${r.kind==='income'?'selected':''}>دریافت</option></select>`:`<input aria-label="${k} ردیف ${i+1}" value="${esc(k==='amount'&&r[k]?new Intl.NumberFormat('fa-IR').format(amount(r[k])):r[k])}" ${k==='date'?'data-persian-calendar="1" onclick="PeymanyarCalendar.open(this)"':k==='party'||k==='project'?`onfocus="bulkPicker(this,${i},'${k}')" oninput="bulkInput(this,${i},'${k}');bulkPicker(this,${i},'${k}',true)" autocomplete="off"`:''} ${k==='amount'||k==='date'?'inputmode="numeric"':''} ${k==='amount'?`oninput="bulkInput(this,${i},'amount')"`:''} enterkeyhint="next" onchange="bulkInput(this,${i},'${k}');${k==='date'?`queueMicrotask(()=>bulkAdvance(${i},'date'))`:''}" onkeydown="bulkNext(event,${i},'${k}')">${k==='amount'?`<small class="amount-words">${r.amount?numberToPersianWords(amount(r.amount))+' تومان':''}</small>`:''}${k==='date'&&!r.date&&i&&normalizeDateValue(rows[i-1].date)?`<button onclick="bulkCell(${i},'date',${esc(JSON.stringify(rows[i-1].date))})">تاریخ سطر قبل: ${esc(rows[i-1].date)}</button>`:''}`}</td>`).join('')}<td data-bulk-control="${i}">${warnings(r,i).map(m=>`<small>${esc(m)}</small>`).join('')||'آماده'}</td></tr>`).join('')}</tbody></table></div><p id="bulkTotals">جمع انتخاب‌شده: ${money(rows.filter(r=>r.selected).reduce((s,r)=>s+amount(r.amount),0))} • ${fa(rows.filter(r=>r.selected&&!errors(r).length).length)} سطر کامل</p><button class="btn" onclick="bulkAddRow()">＋ سطر بعدی</button><button class="btn primary" onclick="saveBulkCash()">ثبت سطرها</button>`;window.PeymanyarBulkGrid?.mount(box,position)}
 window.bulkCell=function(i,key,value){if(!rows[i])return;if(key==='project')rows[i]._projectEdited=true;rows[i][key]=key==='date'&&dateValue(value)?dateValue(value).replace(/[0-9]/g,d=>'۰۱۲۳۴۵۶۷۸۹'[Number(d)]):value;if(key!=='ack')rows[i].ack=false;draw()};
 window.bulkAddRow=function(){rows.push(fresh());draw()};window.bulkRemoveRow=function(i){rows.splice(i,1);draw()};
 const keys=['date','project','party','category','amount','kind','note'];
 window.bulkAdvance=function(i,key,back=false){let at=keys.indexOf(key)+(back?-1:1);if(at<0){if(!i)return;i--;at=keys.length-1}if(at===keys.length){i++;at=0;if(i===rows.length)bulkAddRow()}document.querySelectorAll('.bulk-picker').forEach(el=>el.remove());const input=document.querySelector(`[aria-label="${keys[at]} ردیف ${i+1}"]`);input?.focus();input?.scrollIntoView?.({block:'nearest',inline:'nearest'})};
 window.bulkInput=function(input,i,key){if(!rows[i])return;if(key==='project'&&input.value!==rows[i].project)rows[i]._projectEdited=true;if(key==='amount'){const position=input.selectionStart,raw=normalizeDigits(input.value),digitsBefore=raw.slice(0,position??raw.length).replace(/[^0-9]/g,'').length;formatAmountInput(input);if(position!==null){let at=0,count=0;while(at<input.value.length&&count<digitsBefore){if(/[0-9]/.test(normalizeDigits(input.value[at])))count++;at++}input.setSelectionRange(at,at)}}if(key==='date'&&dateValue(input.value))input.value=dateValue(input.value).replace(/[0-9]/g,d=>'۰۱۲۳۴۵۶۷۸۹'[Number(d)]);rows[i][key]=input.value;rows[i].ack=false;const control=document.querySelector(`[data-bulk-control="${i}"]`);if(control)control.innerHTML=warnings(rows[i],i).map(m=>`<small>${esc(m)}</small>`).join('')||'آماده';const total=document.getElementById('bulkTotals');if(total)total.textContent=`جمع انتخاب‌شده: ${money(rows.filter(r=>r.selected).reduce((s,r)=>s+amount(r.amount),0))} • ${fa(rows.filter(r=>r.selected&&!errors(r).length).length)} سطر کامل`};
 window.bulkNext=function(e,i,key){if(e.isComposing)return;const panel=e.target.parentElement?.querySelector('.bulk-picker');const buttons=panel?[...panel.querySelectorAll('button')]:[];if((e.key==='ArrowDown'||e.key==='ArrowUp')&&buttons.length){e.preventDefault();const current=Number(panel.dataset.active??-1);const next=current<0?(e.key==='ArrowDown'?0:buttons.length-1):(current+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length;panel.dataset.active=String(next);buttons.forEach((button,index)=>{button.style.outline=index===next?'3px solid #d8a64e':'';button.setAttribute('aria-selected',String(index===next))});buttons[next].scrollIntoView?.({block:'nearest',inline:'nearest'});return}if(e.key==='Enter'&&buttons.length&&panel.dataset.active!==undefined){e.preventDefault();buttons[Number(panel.dataset.active)]?.click();return}if(e.key==='Escape'&&panel){e.preventDefault();panel.remove();return}if((e.key==='ArrowLeft'||e.key==='ArrowRight')&&e.target.tagName==='INPUT'&&e.target.selectionStart===e.target.selectionEnd){const at=e.target.selectionStart;if(e.key==='ArrowLeft'&&at===e.target.value.length||e.key==='ArrowRight'&&at===0){e.preventDefault();bulkInput(e.target,i,key);bulkAdvance(i,key,e.key==='ArrowRight');return}}if(e.key==='Enter'||e.key==='Tab'){e.preventDefault();bulkInput(e.target,i,key);bulkAdvance(i,key,e.key==='Tab'&&e.shiftKey)}};

 reviewBulkCash=function(){const text=v('quickText');if(!text)return toast('متن صوتی یا تایپی را وارد کن');const parsed=splitBulkCash(text.replace(/\s*ردیف بعدی?\s*/g,'\n')).map(line=>{const plan=PeymanyarCommand.parse(line,db,todayFa()),date=PeymanyarCommand.dateInfo(line,todayFa());return {...fresh(),_projectEdited:!!plan.project,project:plan.project||v('bulkDefaultProject'),party:plan.party||plan.person||'',category:plan.category||'تنخواه',amount:plan.amount||PeymanyarCommand.amountOf(line)||'',date:date.explicit?date.date:v('bulkEntryDate'),kind:plan.kind||'expense',note:line}});rows=rows.filter(r=>r.party||r.amount||r.note).concat(parsed);document.getElementById('quickText').value='';if(bulkVoiceSession&&!bulkVoiceSession.recording&&!bulkVoiceSession.pending)bulkVoiceSession=null;draw();toast('متن به جدول آمد؛ خانه‌های ناقص را کامل کن')};
 window.bulkImportPhotoRows=function(items){const imported=items.slice(0,100).map(item=>{const r=fresh();r.project=String(item.project||r.project);r._projectEdited=!!item.project;r.party=String(item.party||'');r.category=String(item.description||'تنخواه');r.amount=Number.isFinite(item.amount_toman)&&item.amount_toman>0?item.amount_toman:'';r.date=String(item.date||'');r.kind=item.kind==='income'?'income':'expense';r.note=[String(item.raw_text||''),Array.isArray(item.uncertain)?item.uncertain.map(String).join('؛ '):''].filter(Boolean).join(' | ');return r});rows=rows.filter(hasInput).concat(imported);draw();return imported.length};
 // Blank trailing grid rows are placeholders, not financial records.
 function hasInput(r){return !!(r.party.trim()||String(r.amount).trim()||(r.date.trim()&&r.date!==r._initialDate)||(r.project.trim()&&r.project!==r._initialProject)||r.note.trim()||r.category!=='تنخواه')}
 function linkPerson(name,project){let person=name?knownPerson(name):null;if(name&&!person){person={id:uid(),name,role:'',project:project||'',projects:project?[project]:[]};db.people.push(person)}if(person&&project)person.projects=[...new Set([...(person.projects||[]),person.project,project].filter(Boolean))];return person}
 window.bulkRecordNeedsCompletion=function(r){return r.source==='bulk-grid'&&(!r.project||r.project==='بدون پروژه'||!r.party||r.party==='طرف حساب نامشخص'||!(Number(r.amount)>0)||!dateValue(r.date))};
 saveBulkCash=function(){
  if(bulkVoiceSession?.recording||bulkVoiceSession?.pending)return toast('ابتدا ضبط و تبدیل صدا را تمام کن');
  if(bulkVoiceSession?.failed?.length)return toast('بخش صوتی ناموفق را دوباره تبدیل کن');
  if(v('quickText'))reviewBulkCash();
  const chosen=rows.filter(r=>r.selected&&hasInput(r));if(!chosen.length)return toast('حداقل یک سطر را وارد کن');
  let incomplete=0,suspicious=0;
  for(const r of chosen){
   const date=dateValue(r.date),name=r.project.trim();let project=name?findProject(name):null;
   if(name&&!project){project={id:uid(),name,client:'ثبت نشده',location:'',budget:0,progress:0,status:'فعال',start:date,completeness:'draft'};db.projects.push(project)}
   const person=linkPerson(r.party.trim(),project?.name),value=amount(r.amount);
   const record={id:uid(),personId:person?.id||null,project:project?.name||'بدون پروژه',party:person?.name||'',category:r.category||'تنخواه',amount:Number.isFinite(value)&&value>0?value:0,date,dateSource:date?'explicit':'missing',kind:r.kind,note:r.note,source:'bulk-grid',status:'ثبت اولیه',rawEntry:{...r}};
   if(bulkRecordNeedsCompletion(record)){record.status='نیازمند تکمیل';incomplete++;addCompletionTask('transaction.review','تکمیل سطر تنخواه',{entityId:record.id,project:record.project,eventDate:date,key:`transaction.review:${record.id}`})}
   const matches=date&&record.amount>0&&record.party?db.transactions.filter(t=>rowKey(t)===rowKey(record)):[];
   if(matches.length){for(const t of [...matches,record]){t.mergeReview='مشکوک به تکرار';t.mergeReviewReason='تاریخ، مبلغ و طرف حساب مشابه است؛ بررسی و در صورت نیاز حذف کن'}suspicious++}
   db.transactions.push(record);if(r.category&&!db.categories.includes(r.category))db.categories.push(r.category);
  }
  save();rows=[];closeBulkCash();render();toast(`${fa(chosen.length)} سطر ثبت شد${incomplete?'؛ '+fa(incomplete)+' سطر نیازمند تکمیل':''}${suspicious?'؛ موارد مشابه برای بررسی علامت خوردند':''}`)
 };
 // Incomplete records remain editable and visible in the existing completion inbox.
 const satisfiedBase=taskSatisfied;taskSatisfied=function(task){if(task.type==='transaction.review'){const r=taskRecord(task);return !!r&&!bulkRecordNeedsCompletion(r)}return satisfiedBase(task)};
 const hintBase=completionTaskHint;completionTaskHint=function(task){return task.type==='transaction.review'?'طرف حساب، پروژه، مبلغ و تاریخ این سطر را تکمیل کن.':hintBase(task)};
 const actionBase=completionAction;completionAction=function(id){const task=completionOpen().find(x=>String(x.id)===String(id));if(task?.type==='transaction.review'){document.getElementById('completionInbox')?.remove();return openRecordEditor('transaction',Number(task.entityId))}return actionBase(id)};
 const editorBase=openRecordEditor;openRecordEditor=function(kind,id){editorBase(kind,id);const r=kind==='transaction'?db.transactions.find(x=>Number(x.id)===Number(id)):null;if(r?.source==='bulk-grid'){const date=document.getElementById('reDate');if(date)date.value=r.date||r.rawEntry?.date||'';const amountInput=document.getElementById('reAmount');if(amountInput&&!r.amount)amountInput.value=r.rawEntry?.amount||''}};
 const saveEditorBase=saveRecordEditor;saveRecordEditor=function(kind,id){const r=kind==='transaction'?db.transactions.find(x=>Number(x.id)===Number(id)):null;const party=v('reParty');if(r?.source==='bulk-grid'){const date=document.getElementById('reDate');if(date&&dateValue(date.value))date.value=dateValue(date.value)}saveEditorBase(kind,id);if(r?.source==='bulk-grid'&&!document.getElementById('recordEditor')){const p=linkPerson(party.trim(),r.project==='بدون پروژه'?'':r.project);r.party=p?.name||'';r.personId=p?.id||null;r.status=bulkRecordNeedsCompletion(r)?'نیازمند تکمیل':'ثبت اولیه';r.dateSource=dateValue(r.date)?'explicit':'missing';save();render()}};
 const tableBase=transactionReportTable;transactionReportTable=function(records){const holder=document.createElement('div');holder.innerHTML=tableBase(records);holder.querySelectorAll('tbody tr').forEach((tr,i)=>{if(records[i]&&bulkRecordNeedsCompletion(records[i])){tr.style.background='#fff1d6';tr.title='سطر ثبت شده؛ نیازمند تکمیل';const cell=tr.querySelector('.ledger-actions');cell?.insertAdjacentHTML('afterbegin','<small>نیازمند تکمیل</small>')}});return holder.innerHTML};
})();
