/* Personal cloud bridge. Accounts stay isolated; migration is explicit, never automatic. */
(function(){
 const URL='https://egmvpbrqmbbwhkbyvahp.supabase.co',KEY='sb_publishable_QL-cqYgnsjiuuyp6kELUiw_Mob8hLKQ';
 const BIND=STORAGE+':cloud-binding',OWNER=STORAGE+':cloud-owner',BUCKET='peymanyar-private',BASE=STORAGE+':cloud-baseline';
 const client=window.PeymanyarSupabase?.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'peymanyar-auth'}});
 let user=null,busy=false,note='ورود حساب برای ذخیرهٔ مرکزی',timer=null,lastJSON='',epoch=0;
 const getBinding=()=>{try{return JSON.parse(localStorage.getItem(BIND)||'null')}catch{return null}};
 const fail=e=>{const m=e?.message||String(e);return /revision_conflict/.test(m)?'نسخهٔ سرور در دستگاه دیگری تغییر کرده است. ابتدا پشتیبان کامل بگیر، سپس نسخهٔ سرور را بررسی و بازگردانی کن.':/schema cache|does not exist|PGRST202|PGRST205/.test(m)?'راه‌اندازی دیتابیس هنوز تکمیل نشده است؛ فایل SQL اتصال باید در Supabase اجرا شود.':/Failed to fetch|network|fetch/i.test(m)?'ارتباط با سرور برقرار نشد. اطلاعات در این مرورگر محفوظ است؛ دوباره تلاش کن.':/email.*rate|rate.*limit/i.test(m)?'محدودیت ارسال ایمیل؛ کمی بعد دوباره تلاش کن.':m};
 function status(text){note=text;const el=document.getElementById('cloudStatus');if(el)el.textContent=text;const badge=document.getElementById('cloudBadge');if(badge)badge.textContent=text}
 function card(){const binding=getBinding(),active=user&&binding?.userId===user.id;return `<section class="card" id="cloudAccount" style="margin-bottom:16px"><h3>حساب و ذخیرهٔ مرکزی</h3><details style="margin-bottom:12px"><summary>راه‌اندازی اولیهٔ اتصال</summary><p>فایل راه‌اندازی را در SQL Editor پروژهٔ Supabase اجرا کن؛ سپس وارد حساب شو.</p><button class="btn" onclick="openCloudSetup()">نمایش کد راه‌اندازی</button></details><p id="cloudStatus" role="status" style="line-height:1.9">${esc(note)}</p>${!client?'<p>کتابخانهٔ اتصال بارگذاری نشده است؛ صفحه را تازه‌سازی کن.</p>':!user?`<label>ایمیل حساب<input id="cloudEmail" type="email" dir="ltr" autocomplete="email" placeholder="name@example.com" style="width:100%;margin:10px 0"></label><button class="btn primary" onclick="cloudSendEmail()">دریافت لینک ورود</button><details style="margin-top:12px"><summary>ورود با کد ایمیل</summary><input id="cloudCode" inputmode="numeric" autocomplete="one-time-code" placeholder="کد دریافتی"><button class="btn" onclick="cloudVerifyCode()">تأیید کد</button></details>`:`<p dir="ltr">${esc(user.email||'')}</p><p>${active?'همگام‌سازی گوشی و دسکتاپ فعال است؛ تغییرات دستگاه دیگر هر ۱۵ ثانیه بررسی می‌شود.':'اطلاعات فعلی هنوز به این حساب منتقل نشده است.'}</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn primary" onclick="cloudUploadPersonal()" ${busy?'disabled':''}>${active?'ذخیرهٔ تغییرات در سرور':'انتقال اطلاعات این مرورگر به حساب'}</button><button class="btn" onclick="cloudRestorePersonal()" ${busy?'disabled':''}>دریافت اطلاعات از حساب</button><button class="btn" onclick="PeymanyarCloud.sync()">همگام‌سازی اکنون</button><button class="btn" onclick="cloudSignOut()">خروج حساب</button></div>`}<p style="font-size:13px;line-height:1.9">این مرحله دفتر خصوصی هر حساب است؛ اشتراک دفتر بین همکاران هنوز فعال نیست. فایل رسیدها خصوصی ذخیره می‌شوند. تا پیام موفقیت سرور نمایش داده نشود، پشتیبان محلی را نگه دار.</p></section>`}
 function refresh(){if(page==='settings')render();else status(note)}
 async function identity(){if(!client)throw Error('کتابخانهٔ اتصال در دسترس نیست');const {data,error}=await client.auth.getUser();if(error||!data.user)throw error||Error('ابتدا وارد حساب شو');if(user?.id!==data.user.id){epoch++;user=data.user;}return data.user}
 async function remote(id){const {data,error}=await client.from('peymanyar_personal_snapshots').select('revision,payload,files,updated_at').eq('user_id',id).maybeSingle();if(error)throw error;return data}
 async function hash(blob){const bytes=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsArrayBuffer(blob)});return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('')}
 function blobOf(r){return new Blob([Uint8Array.from(atob(r.data),c=>c.charCodeAt(0))],{type:r.type||'application/octet-stream'})}
 function encode(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(r.error);r.readAsDataURL(blob)})}
 async function push(confirmed=false){if(busy)return false;busy=true;let token;try{const u=await identity();token=epoch;const owner=localStorage.getItem(OWNER);if(owner&&owner!==u.id)throw Error('اطلاعات این مرورگر متعلق به حساب دیگری است. برای این حساب ابتدا «دریافت اطلاعات از حساب» را انجام بده.');const binding=getBinding();if(!confirmed&&binding?.userId!==u.id)return false;
 const existing=await remote(u.id),expected=binding?.userId===u.id?Number(binding.revision):0;if(Number(existing?.revision||0)!==expected)throw Error('revision_conflict');if(confirmed&&!binding&&!confirm('اطلاعات و فایل‌های این مرورگر به حساب خودت در Supabase منتقل شود؟'))return false;
 status('در حال ذخیرهٔ اطلاعات و فایل‌ها…');const pack=await PeymanyarBackup.pack();if(pack.missingFiles.length)throw Error('این فایل‌ها در مرورگر پیدا نشدند؛ انتقال کامل انجام نشد: '+pack.missingFiles.join('، '));const manifest=[],known=new Set((existing?.files||[]).map(r=>r.path));for(const r of pack.files){const blob=blobOf(r),path=u.id+'/'+await hash(blob);if(blob.size>52428800)throw Error('اندازهٔ فایل بیش از ۵۰ مگابایت است: '+r.name);if(!known.has(path)){const {error}=await client.storage.from(BUCKET).upload(path,blob,{contentType:r.type||'application/octet-stream',upsert:false});if(error&&!/already exists|Duplicate|409/i.test(error.message||''))throw error;known.add(path)}manifest.push({id:r.id,name:r.name,type:r.type,path})}
 if(token!==epoch)throw Error('حساب هنگام ذخیره تغییر کرده است.');const {data,error}=await client.rpc('peymanyar_save_personal_snapshot',{expected_user_id:u.id,expected_revision:expected,new_payload:pack.data,new_files:manifest});if(error)throw error;if(token!==epoch)return false;localStorage.setItem(BIND,JSON.stringify({userId:u.id,revision:Number(data)}));localStorage.setItem(OWNER,u.id);lastJSON=JSON.stringify(pack.data);localStorage.setItem(BASE,lastJSON);status('ذخیره در سرور موفق بود • '+new Date().toLocaleTimeString('fa-IR'));return true
 }catch(e){status(fail(e));return false}finally{busy=false;refresh()}}
 async function pull(automatic=false){if(busy)return false;busy=true;try{const u=await identity(),token=epoch,localBefore=localStorage.getItem(STORAGE),row=await remote(u.id);if(!row||!row.revision)throw Error('این حساب هنوز اطلاعاتی در سرور ندارد.');PeymanyarBackup.validate(row.payload);if(!automatic&&!confirm(`نسخهٔ سرور شامل ${fa(row.payload.projects.length)} پروژه و ${fa(row.payload.transactions.length)} تراکنش است. اطلاعات فعلی این مرورگر جایگزین می‌شود؛ ابتدا پشتیبان کامل گرفته‌ای؟`))return false;
 status('در حال دریافت اطلاعات و فایل‌ها…');const files=[];for(const r of row.files||[]){if(typeof r.path!=='string'||!r.path.startsWith(u.id+'/'))throw Error('مسیر فایل حساب معتبر نیست.');const {data,error}=await client.storage.from(BUCKET).download(r.path);if(error)throw error;files.push({...r,data:await encode(data)})}const latest=await remote(u.id);if(token!==epoch||latest?.revision!==row.revision)throw Error('revision_conflict');if(token!==epoch||localStorage.getItem(STORAGE)!==localBefore)throw Error('هنگام دریافت، اطلاعات محلی تغییر کرد؛ دریافت متوقف شد و تغییراتت حفظ شد.');if(automatic&&editing())return false;await PeymanyarBackup.restore({format:'peymanyar-portable',version:1,data:row.payload,files},false,()=>{if(token!==epoch||localStorage.getItem(STORAGE)!==localBefore||(automatic&&editing()))throw Error('هنگام دریافت، ویرایش یا حساب تغییر کرد؛ اطلاعات محلی حفظ شد.')});localStorage.setItem(BIND,JSON.stringify({userId:u.id,revision:Number(row.revision)}));localStorage.setItem(OWNER,u.id);lastJSON=JSON.stringify(db);localStorage.setItem(BASE,lastJSON);status('اطلاعات و فایل‌های حساب دریافت شد • '+new Date().toLocaleTimeString('fa-IR'));return true
 }catch(e){status(fail(e));return false}finally{busy=false;refresh()}}
 window.openCloudSetup=async function(){try{const response=await fetch('./supabase/004_personal_cloud.sql');if(!response.ok)throw Error('فایل راه‌اندازی دریافت نشد');const sql=await response.text();document.getElementById('cloudSetup')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="cloudSetup"><div class="dialog" role="dialog" aria-modal="true" aria-label="راه‌اندازی ذخیرهٔ مرکزی"><div class="dialog-head"><h2>راه‌اندازی ذخیرهٔ مرکزی</h2><button class="close" onclick="document.getElementById('cloudSetup').remove()">×</button></div><p>در Supabase وارد SQL Editor شو، یک Query جدید باز کن، این کد را بچسبان و Run بزن. این کد جدول خصوصی جدید می‌سازد و اطلاعات جدول‌های قبلی را پاک نمی‌کند.</p><textarea id="cloudSetupCode" readonly dir="ltr" style="width:100%;height:240px">${esc(sql)}</textarea><button class="btn primary" onclick="copyCloudSetup()">کپی کد</button></div></div>`)}catch(e){status(fail(e))}};
 window.copyCloudSetup=async function(){const field=document.getElementById('cloudSetupCode');try{await navigator.clipboard.writeText(field.value);toast('کد کپی شد')}catch{field.focus();field.select();toast('متن انتخاب شد؛ گزینهٔ Copy را بزن')}};
 window.cloudUploadPersonal=()=>push(true);window.cloudRestorePersonal=()=>pull(false);
 window.cloudSendEmail=async function(){if(!client)return;const email=document.getElementById('cloudEmail')?.value.trim();if(!email||!/^\S+@\S+\.\S+$/.test(email))return status('ایمیل معتبر بنویس.');status('در حال درخواست لینک ورود…');const {error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:'https://alvandi111.github.io/mehdi/'}});status(error?fail(error):'لینک ورود به ایمیلت ارسال شد؛ آن را در همین مرورگر باز کن. اگر کد دریافت کردی، کد را همین‌جا وارد کن.')};
 window.cloudVerifyCode=async function(){const email=document.getElementById('cloudEmail')?.value.trim(),token=document.getElementById('cloudCode')?.value.trim().replace(/[۰-۹]/g,c=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(c));if(!email||!token||!client)return;const {error}=await client.auth.verifyOtp({email,token,type:'email'});if(error)status(fail(error));else await boot()};
 window.cloudSignOut=async function(){if(busy)return status('ذخیره یا دریافت در حال انجام است؛ پس از پایان خارج شو.');const {error}=await client.auth.signOut();if(error)return status(fail(error));epoch++;user=null;localStorage.removeItem(BIND);status('از حساب خارج شدی. نسخهٔ محلی روی این مرورگر باقی است.');refresh()};
 function canonical(value){return JSON.stringify(value,function(key,item){return item&&typeof item==='object'&&!Array.isArray(item)?Object.keys(item).sort().reduce((out,k)=>(out[k]=item[k],out),{}):item})}
 function editing(){return !!document.querySelector('.modal,.voice-fullscreen')||/^(INPUT|TEXTAREA|SELECT)$/.test(document.activeElement?.tagName||'')}
 let checking=false;
 async function sync(){
  if(!user||busy||checking||getBinding()?.userId!==user.id||document.visibilityState==='hidden')return false;
  checking=true;try{
   const id=user.id,token=epoch,binding=getBinding(),row=await remote(id);
   if(token!==epoch)return false;
   const local=localStorage.getItem(STORAGE),baseline=localStorage.getItem(BASE);
   if(!baseline){
    if(row&&canonical(row.payload)===canonical(JSON.parse(local))){lastJSON=local;localStorage.setItem(BASE,local);localStorage.setItem(BIND,JSON.stringify({userId:id,revision:Number(row.revision)}));status('گوشی و دسکتاپ به حساب متصل‌اند؛ همگام‌سازی فعال است.');return true}
    status('برای شروع همگام‌سازی، نسخهٔ حساب را دریافت کن یا اطلاعات فعلی را بررسی و به حساب منتقل کن.');return false;
   }
   lastJSON=baseline;
   if(Number(row?.revision||0)>Number(binding.revision)){
    if(local!==baseline){status('در هر دو دستگاه تغییر وجود دارد؛ تغییرات محلی حفظ شد. ابتدا پشتیبان بگیر و نسخهٔ حساب را بررسی کن.');return false}
    if(editing()){status('تغییرات دستگاه دیگر آمادهٔ دریافت است؛ پس از پایان ویرایش دریافت می‌شود.');return false}
    return await pull(true);
   }
   if(Number(row?.revision||0)!==Number(binding.revision))throw Error('revision_conflict');
   if(local!==baseline)return await push();
   status('همگام‌سازی فعال • آخرین بررسی '+new Date().toLocaleTimeString('fa-IR'));return true;
  }catch(e){status(fail(e));return false}finally{checking=false}
 }
 async function boot(){try{const {data,error}=await client.auth.getSession();if(error)throw error;if(data.session){await identity();status(getBinding()?.userId===user.id?'حساب متصل است؛ در حال بررسی همگام‌سازی…':'وارد حساب شدی؛ برای این دستگاه ابتدا «دریافت اطلاعات از حساب» را بزن.');if(getBinding()?.userId===user.id)await sync()}else{user=null;status('ورود حساب برای ذخیرهٔ مرکزی')}}catch(e){status(fail(e))}refresh()}
 const oldSettings=settings;settings=function(){return oldSettings().replace('ذخیرهٔ مرکزی و ورود کاربران هنوز فعال نیست.','برای ذخیرهٔ مرکزی از بخش حساب همین صفحه استفاده کن؛ اشتراک دفتر بین همکاران هنوز فعال نیست.').replace('<main class="phone-content">','<main class="phone-content">'+card())};
 const oldDashboard=dashboard;dashboard=function(){return oldDashboard().replace('اطلاعات فعلاً در همین مرورگر است. برای انتقال، پشتیبان کامل بگیر و در مرورگر جدید بازگردانی کن.',user&&getBinding()?.userId===user.id?'اطلاعات این مرورگر به حساب متصل است؛ وضعیت ذخیرهٔ سرور را بررسی کن و پشتیبان کامل را هم نگه دار.':'اطلاعات فعلاً در همین مرورگر است. برای انتقال، پشتیبان کامل بگیر و در مرورگر جدید بازگردانی کن.').replace('<strong>حفظ اطلاعات و انتقال به گوشی</strong>','<strong>حفظ اطلاعات و انتقال به گوشی</strong><p id="cloudBadge" role="status">'+esc(note)+'</p>')};
 const oldSave=save;save=function(){oldSave();if(user&&getBinding()?.userId===user.id){clearTimeout(timer);timer=setTimeout(()=>sync(),1500)}};
 const interval=setInterval(sync,15000);
 window.addEventListener('online',sync);window.addEventListener('focus',sync);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')sync()});
 window.PeymanyarCloud={push,pull:()=>pull(false),sync,boot,getBinding,card,client,stop:()=>{clearInterval(interval);clearTimeout(timer)}};
 if(client){client.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){epoch++;user=null;status('حساب وارد نشده است');refresh()}else if(event==='SIGNED_IN'){epoch++;setTimeout(boot,0)}});boot()}else render();
})();
