/* Personal cloud bridge. Accounts stay isolated; migration is explicit, never automatic. */
(function(){
 const URL='https://egmvpbrqmbbwhkbyvahp.supabase.co',KEY='sb_publishable_QL-cqYgnsjiuuyp6kELUiw_Mob8hLKQ';
 const BIND=STORAGE+':cloud-binding',OWNER=STORAGE+':cloud-owner',BUCKET='peymanyar-private',BASE=STORAGE+':cloud-baseline';
 const client=window.PeymanyarSupabase?.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'peymanyar-auth'}});
 let user=null,busy=false,note='ورود حساب برای ذخیرهٔ مرکزی',timer=null,lastJSON='',epoch=0,authPhase='loading',booting=null;
 const getBinding=()=>{try{return JSON.parse(localStorage.getItem(BIND)||'null')}catch{return null}};
 const fail=e=>{const m=e?.message||String(e);return /revision_conflict/.test(m)?'نسخهٔ سرور در دستگاه دیگری تغییر کرده است. ابتدا پشتیبان کامل بگیر، سپس نسخهٔ سرور را بررسی و بازگردانی کن.':/schema cache|does not exist|PGRST202|PGRST205/.test(m)?'راه‌اندازی دیتابیس هنوز تکمیل نشده است؛ فایل SQL اتصال باید در Supabase اجرا شود.':/Failed to fetch|network|fetch/i.test(m)?'ارتباط با سرور برقرار نشد. اطلاعات در این مرورگر محفوظ است؛ دوباره تلاش کن.':/email.*rate|rate.*limit/i.test(m)?'محدودیت ارسال ایمیل؛ کمی بعد دوباره تلاش کن.':m};
 function status(text){note=text;document.querySelectorAll('#cloudStatus,#cloudLoginStatus,#cloudAccountStatus').forEach(el=>el.textContent=text);const badge=document.getElementById('cloudBadge');if(badge)badge.textContent=text}
 function card(){const binding=getBinding(),active=user&&binding?.userId===user.id;return `<section class="card" id="cloudAccount" style="margin-bottom:16px"><h3>حساب و ذخیرهٔ مرکزی</h3><details style="margin-bottom:12px"><summary>راه‌اندازی اولیهٔ اتصال</summary><p>فایل راه‌اندازی را در SQL Editor پروژهٔ Supabase اجرا کن؛ سپس وارد حساب شو.</p><button class="btn" onclick="openCloudSetup()">نمایش کد راه‌اندازی</button><button class="btn" onclick="openCloudOTPSetup()">راه‌اندازی کد ایمیل</button></details><p id="cloudStatus" role="status" style="line-height:1.9">${esc(note)}</p><button class="btn primary" id="cloudUploadButton" onclick="cloudUploadPersonal()" ${busy?'disabled':''}>ذخیرهٔ اطلاعات این دستگاه در حساب</button><p class="muted">این دکمه را در همان گوشی یا مرورگری بزن که پروژه‌ها و پرداخت‌هایت در آن دیده می‌شوند. برای انتقال، باید وارد حساب خودت باشی.</p>${!client?'<p>کتابخانهٔ اتصال بارگذاری نشده است؛ صفحه را تازه‌سازی کن.</p>':!user?`<p>برای دسترسی به دفتر خودت روی گوشی و دسکتاپ، با ایمیل تأییدشده وارد شو.</p><button class="btn primary" onclick="openCloudLogin()">ورود / Sign In</button>`:`<p dir="ltr">${esc(user.email||'')}</p><p>${active?'همگام‌سازی گوشی و دسکتاپ فعال است؛ تغییرات دستگاه دیگر هر ۱۵ ثانیه بررسی می‌شود.':'اتصال اولیه در حال بررسی است؛ اطلاعات ذخیره‌شدهٔ حساب روی دستگاه خالی خودکار دریافت می‌شود.'}</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" onclick="cloudRestorePersonal()" ${busy?'disabled':''}>دریافت اطلاعات از حساب</button><button class="btn" onclick="PeymanyarCloud.sync()">همگام‌سازی اکنون</button><button class="btn" onclick="openCloudPassword()">تعیین رمز عبور</button><button class="btn" onclick="cloudSignOut()">خروج حساب</button><button class="btn" onclick="cloudSwitchAccount()">ورود با ایمیل دیگر</button></div>`}<p style="font-size:13px;line-height:1.9">این مرحله دفتر خصوصی هر حساب است؛ اشتراک دفتر بین همکاران هنوز فعال نیست. فایل رسیدها خصوصی ذخیره می‌شوند. تا پیام موفقیت سرور نمایش داده نشود، پشتیبان محلی را نگه دار.</p></section>`}
 function accountLabel(){return authPhase==='loading'?'بررسی حساب…':user?'حساب من':'ورود / Sign In'}
 function refresh(){if(page==='settings')render();else status(note);document.querySelectorAll('[data-cloud-login]').forEach(el=>{el.textContent=accountLabel();el.disabled=authPhase==='loading';el.setAttribute('onclick',user?'openCloudAccountMenu()':'openCloudLogin()');el.setAttribute('aria-label',user?'حساب من، خروج و تغییر حساب':'ورود به حساب')})}
 function sessionUI(session){const next=session?.user||null;if(next?.id!==user?.id)epoch++;user=next;authPhase=next?'signed-in':'signed-out';if(next)document.getElementById('cloudLoginModal')?.remove();else{document.getElementById('cloudAccountModal')?.remove();document.getElementById('cloudPasswordModal')?.remove()}refresh()}
 window.openCloudAccountMenu=function(){if(!user)return openCloudLogin();document.getElementById('cloudAccountModal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="cloudAccountModal"><div class="dialog cloud-login-dialog" role="dialog" aria-modal="true" aria-labelledby="cloudAccountTitle"><div class="dialog-head"><h2 id="cloudAccountTitle">حساب من</h2><button class="close" aria-label="بستن" onclick="document.getElementById('cloudAccountModal').remove()">×</button></div><p>وارد این حساب شده‌ای:</p><p id="cloudAccountStatus" role="status"></p><p dir="ltr">${esc(user.email||'')}</p><div style="display:grid;gap:12px"><button class="btn" onclick="document.getElementById('cloudAccountModal').remove();go('settings')">تنظیمات و پشتیبان</button><button class="btn" onclick="document.getElementById('cloudAccountModal').remove();openCloudPassword()">تعیین یا تغییر رمز</button><button class="btn" onclick="cloudSignOut()">خروج از حساب</button><button class="btn" onclick="cloudSwitchAccount()">خروج و ورود با ایمیل دیگر</button></div><p class="muted">برای استفاده از همین حساب، نیازی به دریافت کد یا ورود دوباره نیست.</p></div></div>`)};
 window.cloudSwitchAccount=async function(){if(await cloudSignOut())openCloudLogin()};
 let authBusy=false,passwordAfterOTP=false,requestedEmail='',otpType='email';
 function authNote(text){status(text);const el=document.getElementById('cloudPasswordStatus');if(el)el.textContent=text}
 function authModal(body){document.getElementById('cloudLoginModal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="cloudLoginModal"><div class="dialog cloud-login-dialog" role="dialog" aria-modal="true" aria-labelledby="cloudLoginTitle"><div class="dialog-head"><h2 id="cloudLoginTitle">ورود به پیمان‌یار</h2><button class="close" aria-label="بستن" onclick="document.getElementById('cloudLoginModal').remove()">×</button></div>${body}<p id="cloudLoginStatus" role="status" aria-live="polite"></p></div></div>`)}
 window.openCloudLogin=async function(){if(authPhase==='loading')await boot();if(user){openCloudAccountMenu();return}passwordAfterOTP=false;authModal(`<form onsubmit="event.preventDefault();cloudPasswordLogin()"><label for="cloudEmail">ایمیل</label><input id="cloudEmail" type="email" dir="ltr" autocomplete="username" required placeholder="name@example.com"><label for="cloudPassword">رمز عبور</label><input id="cloudPassword" type="password" autocomplete="current-password" required><button class="btn primary" type="submit">ورود</button></form><button class="btn" onclick="openCloudRegister()">ثبت‌نام حساب جدید</button><button class="btn" onclick="openCloudOTP(true)">فراموشی رمز عبور</button><button class="btn" onclick="openCloudOTP(false)">ورود با کد ایمیل</button><p class="muted">با همان ایمیل وارد شو تا دفتر ذخیره‌شدهٔ خودت روی گوشی و دسکتاپ دریافت شود.</p>`);document.getElementById('cloudEmail').focus()};
 window.openCloudOTP=function(setPassword=true){if(user)return openCloudAccountMenu();const email=document.getElementById('cloudEmail')?.value.trim()||requestedEmail;passwordAfterOTP=setPassword;otpType=setPassword?'recovery':'email';authModal(`<p>${setPassword?'ایمیل حساب فعلی را بنویس؛ کد بازیابی را وارد کن و رمز جدید تعیین کن.':'کد تأیید ایمیل را اینجا وارد کن.'}</p><form onsubmit="event.preventDefault();cloudSendEmail()"><label for="cloudEmail">ایمیل</label><input id="cloudEmail" type="email" dir="ltr" autocomplete="email" required value="${esc(email)}"><button class="btn primary" data-auth-mail type="submit">ارسال کد تأیید</button></form><form onsubmit="event.preventDefault();cloudVerifyCode()"><label for="cloudCode">کد ۶ رقمی ایمیل</label><input id="cloudCode" dir="ltr" inputmode="numeric" autocomplete="one-time-code" required maxlength="10"><button class="btn primary" type="submit">تأیید کد</button></form><p class="muted">آخرین کد دریافتی را بنویس؛ نیازی به باز کردن لینک نیست.</p>`)};
 const MAIL_WAIT=STORAGE+':auth-mail-retry';
 function emailError(e){if(e?.code==='over_email_send_rate_limit'||/email.*rate.*limit/i.test(e?.message||''))return 'سهمیهٔ ارسال ایمیل سرور تمام شده است. تکرار درخواست مشکل را حل نمی‌کند؛ تنظیمات سرویس ایمیل و سهمیهٔ ارسال باید در Supabase بررسی شود.';if(e?.status===429||/rate.*limit/i.test(e?.message||''))return 'سرور درخواست‌های بیش از حد دریافت کرده است؛ بعداً دوباره تلاش کن.';return fail(e)}
 function mailAllowed(){const seconds=Math.ceil((Number(localStorage.getItem(MAIL_WAIT)||0)-Date.now())/1000);if(seconds>0){authNote('برای درخواست دوباره '+fa(seconds)+' ثانیه صبر کن.');return false}return true}
 function mailWait(){localStorage.setItem(MAIL_WAIT,String(Date.now()+60000))}
 window.openCloudRegister=function(){if(user)return openCloudAccountMenu();const email=document.getElementById('cloudEmail')?.value.trim()||'';authModal(`<p>حساب جدید بساز؛ بعد از تأیید ایمیل، با همین ایمیل و رمز روی گوشی و دسکتاپ وارد شو.</p><form onsubmit="event.preventDefault();cloudRegister()"><label for="cloudEmail">ایمیل</label><input id="cloudEmail" type="email" dir="ltr" autocomplete="email" required value="${esc(email)}"><label for="cloudSignupPassword">رمز عبور؛ حداقل ۸ نویسه</label><input id="cloudSignupPassword" type="password" autocomplete="new-password" minlength="8" required><label for="cloudSignupRepeat">تکرار رمز</label><input id="cloudSignupRepeat" type="password" autocomplete="new-password" minlength="8" required><button class="btn primary" data-auth-mail type="submit">ثبت‌نام و ارسال کد تأیید</button></form><button class="btn" onclick="openCloudLogin()">حساب دارم؛ ورود</button>`)};
 function signupCodeForm(email){passwordAfterOTP=false;otpType='signup';requestedEmail=email;authModal(`<p>کد تأیید ثبت‌نام را از ایمیل در این فرم وارد کن.</p><label for="cloudEmail">ایمیل</label><input id="cloudEmail" type="email" dir="ltr" value="${esc(email)}" readonly><form onsubmit="event.preventDefault();cloudVerifyCode()"><label for="cloudCode">کد ایمیل</label><input id="cloudCode" dir="ltr" inputmode="numeric" autocomplete="one-time-code" required maxlength="10"><button class="btn primary" type="submit">تأیید و ورود</button></form><button class="btn" data-auth-mail onclick="cloudSendEmail()">ارسال مجدد کد ثبت‌نام</button>`)}
 window.cloudRegister=async function(){if(!client||authBusy)return;if(user)return openCloudAccountMenu();const email=document.getElementById('cloudEmail')?.value.trim(),password=document.getElementById('cloudSignupPassword')?.value,repeat=document.getElementById('cloudSignupRepeat')?.value;if(!email||!/^\S+@\S+\.\S+$/.test(email))return authNote('ایمیل معتبر بنویس.');if(!password||password.length<8)return authNote('رمز حداقل ۸ نویسه داشته باشد.');if(password!==repeat)return authNote('تکرار رمز یکسان نیست.');if(!mailAllowed())return;authBusy=true;try{authNote('در حال ثبت‌نام…');const {data,error}=await client.auth.signUp({email,password,options:{emailRedirectTo:'https://alvandi111.github.io/mehdi/'}});if(error)throw error;mailWait();if(data?.session){await boot()}else{signupCodeForm(email);authNote('درخواست ثبت‌نام پذیرفته شد. اگر این ایمیل از قبل حساب دارد، از ورود یا فراموشی رمز استفاده کن.')}}catch(e){authNote(emailError(e))}finally{authBusy=false}};

 window.openCloudPassword=function(){if(!user)return openCloudOTP(true);document.getElementById('cloudPasswordModal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="cloudPasswordModal"><div class="dialog cloud-login-dialog" role="dialog" aria-modal="true" aria-labelledby="cloudPasswordTitle"><div class="dialog-head"><h2 id="cloudPasswordTitle">تعیین رمز عبور</h2><button class="close" aria-label="بستن" onclick="document.getElementById('cloudPasswordModal').remove()">×</button></div><p dir="ltr">${esc(user.email||'')}</p><form onsubmit="event.preventDefault();cloudSetPassword()"><label for="cloudNewPassword">رمز جدید؛ حداقل ۸ نویسه</label><input id="cloudNewPassword" type="password" autocomplete="new-password" minlength="8" required><label for="cloudRepeatPassword">تکرار رمز</label><input id="cloudRepeatPassword" type="password" autocomplete="new-password" minlength="8" required><button class="btn primary" type="submit">ذخیرهٔ رمز</button></form><p id="cloudPasswordStatus" role="status" aria-live="polite"></p></div></div>`)};
 window.cloudPasswordLogin=async function(){if(!client||authBusy)return;const email=document.getElementById('cloudEmail')?.value.trim(),password=document.getElementById('cloudPassword')?.value;if(!email||!/^\S+@\S+\.\S+$/.test(email)||!password)return authNote('ایمیل و رمز را وارد کن.');authBusy=true;try{authNote('در حال ورود…');const {error}=await client.auth.signInWithPassword({email,password});if(error)throw error;await boot()}catch(e){authNote(/invalid.*credentials/i.test(e.message||'')?'ایمیل یا رمز صحیح نیست. برای حساب جدید «ثبت‌نام» و برای حساب فعلی «فراموشی رمز عبور» را بزن.':fail(e))}finally{authBusy=false}};
 window.cloudSetPassword=async function(){if(!client||authBusy)return;const password=document.getElementById('cloudNewPassword')?.value,repeat=document.getElementById('cloudRepeatPassword')?.value;if(!password||password.length<8)return authNote('رمز حداقل ۸ نویسه داشته باشد.');if(password!==repeat)return authNote('تکرار رمز با رمز جدید یکسان نیست.');authBusy=true;try{await identity();const {error}=await client.auth.updateUser({password});if(error)throw error;document.getElementById('cloudPasswordModal')?.remove();status('رمز ذخیره شد؛ از این پس با ایمیل و رمز وارد شو.');refresh();toast('رمز عبور ذخیره شد')}catch(e){authNote(fail(e))}finally{authBusy=false}};
 window.openCloudOTPSetup=async function(){try{const r=await fetch('./supabase/email-otp.html');if(!r.ok)throw Error('قالب ایمیل دریافت نشد');const html=await r.text();document.getElementById('cloudOTPSetup')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="cloudOTPSetup"><div class="dialog cloud-login-dialog"><div class="dialog-head"><h2>راه‌اندازی ارسال کد ایمیل</h2><button class="close" onclick="document.getElementById('cloudOTPSetup').remove()">×</button></div><p>مالک برنامه ابتدا SMTP اختصاصی و سهمیهٔ ایمیل را در Authentication ← Email تنظیم کند؛ سپس این قالب را ذخیره کند. در Supabase، بخش Authentication ← Email Templates، متن قالب Confirm Signup، Reset Password و Magic Link را با این کد جایگزین و ذخیره کن. کاربران این تنظیم را انجام نمی‌دهند.</p><a class="btn" href="https://supabase.com/dashboard/project/egmvpbrqmbbwhkbyvahp/auth/templates" target="_blank" rel="noopener">باز کردن قالب‌های ایمیل</a><textarea id="cloudOTPTemplate" readonly dir="ltr" style="width:100%;height:180px">${esc(html)}</textarea><button class="btn" onclick="copyCloudOTPTemplate()">کپی قالب</button></div></div>`)}catch(e){authNote(fail(e))}};
 window.copyCloudOTPTemplate=async function(){const field=document.getElementById('cloudOTPTemplate');try{await navigator.clipboard.writeText(field.value);toast('قالب کپی شد')}catch{field.focus();field.select();toast('متن انتخاب شد؛ Copy را بزن')}};

 async function identity(){if(!client)throw Error('کتابخانهٔ اتصال در دسترس نیست');const {data,error}=await client.auth.getUser();if(error||!data.user)throw error||Error('ابتدا وارد حساب شو');if(user?.id!==data.user.id)epoch++;user=data.user;return data.user}
 async function remote(id){const {data,error}=await client.from('peymanyar_personal_snapshots').select('revision,payload,files,updated_at').eq('user_id',id).maybeSingle();if(error)throw error;return data}
 async function hash(blob){const bytes=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsArrayBuffer(blob)});return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('')}
 function blobOf(r){return new Blob([Uint8Array.from(atob(r.data),c=>c.charCodeAt(0))],{type:r.type||'application/octet-stream'})}
 function encode(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(r.error);r.readAsDataURL(blob)})}
 const recordCollections=['projects','people','transactions','contracts','daily','documents'];
 function emptyRecords(data){return !!data&&recordCollections.every(k=>Array.isArray(data[k])&&data[k].length===0)}
 function emptySnapshot(row){return !!row&&emptyRecords(row.payload)&&Array.isArray(row.files)&&row.files.length===0}
 async function push(confirmed=false){if(busy)return false;busy=true;let token;try{const u=await identity();token=epoch;const owner=localStorage.getItem(OWNER);if(owner&&owner!==u.id)throw Error('اطلاعات این مرورگر متعلق به حساب دیگری است. برای این حساب ابتدا «دریافت اطلاعات از حساب» را انجام بده.');const binding=getBinding();if(!confirmed&&binding?.userId!==u.id)return false;
 const existing=await remote(u.id);let expected=binding?.userId===u.id?Number(binding.revision):0;const seedEmpty=confirmed&&binding?.userId!==u.id&&emptySnapshot(existing)&&!emptyRecords(db);if(seedEmpty){if(!confirm('نسخهٔ حساب خالی است. اطلاعات و فایل‌های موجود این گوشی در حساب ذخیره شود؟'))return false;expected=Number(existing.revision)}if(Number(existing?.revision||0)!==expected)throw Error('revision_conflict');if(confirmed&&!binding&&!seedEmpty&&!confirm('اطلاعات و فایل‌های این مرورگر به حساب خودت در Supabase منتقل شود؟'))return false;
 status('در حال ذخیرهٔ اطلاعات و فایل‌ها…');const pack=await PeymanyarBackup.pack();if(pack.missingFiles.length)throw Error('این فایل‌ها در مرورگر پیدا نشدند؛ انتقال کامل انجام نشد: '+pack.missingFiles.join('، '));const manifest=[],known=new Set((existing?.files||[]).map(r=>r.path));for(const r of pack.files){const blob=blobOf(r),path=u.id+'/'+await hash(blob);if(blob.size>52428800)throw Error('اندازهٔ فایل بیش از ۵۰ مگابایت است: '+r.name);if(!known.has(path)){const {error}=await client.storage.from(BUCKET).upload(path,blob,{contentType:r.type||'application/octet-stream',upsert:false});if(error&&!/already exists|Duplicate|409/i.test(error.message||''))throw error;known.add(path)}manifest.push({id:r.id,name:r.name,type:r.type,path})}
 if(token!==epoch)throw Error('حساب هنگام ذخیره تغییر کرده است.');const {data,error}=await client.rpc('peymanyar_save_personal_snapshot',{expected_user_id:u.id,expected_revision:expected,new_payload:pack.data,new_files:manifest});if(error)throw error;if(token!==epoch)return false;localStorage.setItem(BIND,JSON.stringify({userId:u.id,revision:Number(data)}));localStorage.setItem(OWNER,u.id);lastJSON=JSON.stringify(pack.data);localStorage.setItem(BASE,lastJSON);status('ذخیره در سرور موفق بود • '+new Date().toLocaleTimeString('fa-IR'));return true
 }catch(e){status(fail(e));return false}finally{busy=false;refresh()}}
 async function pull(automatic=false,expectedLocal,expectedUser){if(busy)return false;busy=true;try{const u=await identity(),token=epoch,localBefore=localStorage.getItem(STORAGE);if(automatic&&((expectedLocal!==undefined&&localBefore!==expectedLocal)||(expectedUser&&u.id!==expectedUser)))throw Error('اطلاعات یا حساب هنگام دریافت تغییر کرد؛ تغییرات محلی حفظ شد.');const row=await remote(u.id);if(!row||!row.revision)throw Error('این حساب هنوز اطلاعاتی در سرور ندارد.');PeymanyarBackup.validate(row.payload);if(emptyRecords(row.payload)&&!emptyRecords(db))throw Error('نسخهٔ حساب خالی است؛ دریافت متوقف شد تا اطلاعات این دستگاه حفظ شود. برای انتقال اطلاعات این دستگاه، دکمهٔ ذخیره در حساب را بزن.');if(!automatic&&!confirm(`نسخهٔ سرور شامل ${fa(row.payload.projects.length)} پروژه و ${fa(row.payload.transactions.length)} تراکنش است. اطلاعات فعلی این مرورگر جایگزین می‌شود؛ ابتدا پشتیبان کامل گرفته‌ای؟`))return false;
 status('در حال دریافت اطلاعات و فایل‌ها…');const files=[];for(const r of row.files||[]){if(typeof r.path!=='string'||!r.path.startsWith(u.id+'/'))throw Error('مسیر فایل حساب معتبر نیست.');const {data,error}=await client.storage.from(BUCKET).download(r.path);if(error)throw error;files.push({...r,data:await encode(data)})}const latest=await remote(u.id);if(token!==epoch||latest?.revision!==row.revision)throw Error('revision_conflict');if(token!==epoch||localStorage.getItem(STORAGE)!==localBefore)throw Error('هنگام دریافت، اطلاعات محلی تغییر کرد؛ دریافت متوقف شد و تغییراتت حفظ شد.');if(automatic&&editing())return false;await PeymanyarBackup.restore({format:'peymanyar-portable',version:1,data:row.payload,files},false,()=>{if(token!==epoch||localStorage.getItem(STORAGE)!==localBefore||(automatic&&editing()))throw Error('هنگام دریافت، ویرایش یا حساب تغییر کرد؛ اطلاعات محلی حفظ شد.')});localStorage.setItem(BIND,JSON.stringify({userId:u.id,revision:Number(row.revision)}));localStorage.setItem(OWNER,u.id);lastJSON=JSON.stringify(db);localStorage.setItem(BASE,lastJSON);status('اطلاعات و فایل‌های حساب دریافت شد • '+new Date().toLocaleTimeString('fa-IR'));return true
 }catch(e){status(fail(e));return false}finally{busy=false;refresh()}}
 window.openCloudSetup=async function(){try{const response=await fetch('./supabase/004_personal_cloud.sql');if(!response.ok)throw Error('فایل راه‌اندازی دریافت نشد');const sql=await response.text();document.getElementById('cloudSetup')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="cloudSetup"><div class="dialog" role="dialog" aria-modal="true" aria-label="راه‌اندازی ذخیرهٔ مرکزی"><div class="dialog-head"><h2>راه‌اندازی ذخیرهٔ مرکزی</h2><button class="close" onclick="document.getElementById('cloudSetup').remove()">×</button></div><p>در Supabase وارد SQL Editor شو، یک Query جدید باز کن، این کد را بچسبان و Run بزن. این کد جدول خصوصی جدید می‌سازد و اطلاعات جدول‌های قبلی را پاک نمی‌کند.</p><textarea id="cloudSetupCode" readonly dir="ltr" style="width:100%;height:240px">${esc(sql)}</textarea><button class="btn primary" onclick="copyCloudSetup()">کپی کد</button></div></div>`)}catch(e){status(fail(e))}};
 window.copyCloudSetup=async function(){const field=document.getElementById('cloudSetupCode');try{await navigator.clipboard.writeText(field.value);toast('کد کپی شد')}catch{field.focus();field.select();toast('متن انتخاب شد؛ گزینهٔ Copy را بزن')}};
 window.cloudUploadPersonal=async function(){if(!user){await openCloudLogin();authNote('ابتدا با حساب خودت وارد شو؛ سپس در تنظیمات «ذخیرهٔ اطلاعات این دستگاه در حساب» را بزن.');return false}return push(true)};window.cloudRestorePersonal=()=>pull(false);
 window.cloudSendEmail=async function(){if(user)return openCloudAccountMenu();if(!client||authBusy)return;const email=document.getElementById('cloudEmail')?.value.trim();if(!email||!/^\S+@\S+\.\S+$/.test(email))return authNote('ایمیل معتبر بنویس.');if(!mailAllowed())return;authBusy=true;try{authNote('در حال درخواست کد…');let result;if(otpType==='recovery')result=await client.auth.resetPasswordForEmail(email,{redirectTo:'https://alvandi111.github.io/mehdi/'});else if(otpType==='signup')result=await client.auth.resend({type:'signup',email});else result=await client.auth.signInWithOtp({email,options:{shouldCreateUser:false,emailRedirectTo:'https://alvandi111.github.io/mehdi/'}});if(result.error)throw result.error;mailWait();requestedEmail=email;authNote(otpType==='recovery'?'اگر این ایمیل حساب داشته باشد، درخواست بازیابی ارسال می‌شود. کد آخرین ایمیل را وارد کن؛ اگر ایمیل فقط لینک دارد، قالب Reset Password باید تنظیم شود.':'درخواست کد ارسال شد؛ کد آخرین ایمیل را وارد کن. اگر ایمیل فقط لینک دارد، قالب ارسال کد باید در Supabase تنظیم شود.');document.getElementById('cloudCode')?.focus()}catch(e){authNote(emailError(e))}finally{authBusy=false}};

 window.cloudVerifyCode=async function(){if(!client||authBusy)return;const email=document.getElementById('cloudEmail')?.value.trim(),token=document.getElementById('cloudCode')?.value.trim().replace(/[۰-۹]/g,c=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(c)).replace(/[٠-٩]/g,c=>'٠١٢٣٤٥٦٧٨٩'.indexOf(c));if(!email||!/^\d{6,10}$/.test(token||''))return authNote('کد کامل ایمیل را وارد کن؛ کد معمولاً ۶ رقمی است.');if(requestedEmail&&email!==requestedEmail)return authNote('ایمیل تغییر کرده است؛ برای این ایمیل کد تازه درخواست کن.');const wantsPassword=passwordAfterOTP;authBusy=true;try{const {error}=await client.auth.verifyOtp({email,token,type:otpType});if(error)throw error;await boot();if(user&&wantsPassword)openCloudPassword()}catch(e){authNote(/expired|invalid.*otp|token/i.test(e.message||'')?'کد نامعتبر یا منقضی است؛ آخرین کد را وارد کن یا کد جدید بگیر.':fail(e))}finally{authBusy=false}};

 window.cloudSignOut=async function(){if(busy){status('ذخیره یا دریافت در حال انجام است؛ پس از پایان خارج شو.');return false}try{const {error}=await client.auth.signOut();if(error)throw error;sessionUI(null);document.getElementById('cloudAccountModal')?.remove();document.getElementById('cloudPasswordModal')?.remove();requestedEmail='';status('از حساب خارج شدی؛ اطلاعات محلی روی این مرورگر باقی است و به ایمیل دیگری منتقل نمی‌شود.');refresh();return true}catch(e){status(fail(e));return false}};

 function canonical(value){return JSON.stringify(value,function(key,item){return item&&typeof item==='object'&&!Array.isArray(item)?Object.keys(item).sort().reduce((out,k)=>(out[k]=item[k],out),{}):item})}
 function editing(){return !!document.querySelector('.modal,.voice-fullscreen')||/^(INPUT|TEXTAREA|SELECT)$/.test(document.activeElement?.tagName||'')}
 let checking=false;
 async function sync(){
  if(!user||busy||checking||document.visibilityState==='hidden')return false;
  checking=true;try{
   const id=user.id,token=epoch,binding=getBinding(),row=await remote(id);
   if(token!==epoch)return false;
   const local=localStorage.getItem(STORAGE),baseline=localStorage.getItem(BASE);
   if(binding?.userId!==id){
    const empty=['projects','people','transactions','contracts','daily','documents'].every(k=>Array.isArray(db[k])&&db[k].length===0);
    const owner=localStorage.getItem(OWNER);
    if(owner&&owner!==id&&!empty){status('اطلاعات محلی متعلق به حساب دیگری است؛ برای جایگزینی از «دریافت اطلاعات از حساب» استفاده کن.');return false}
    if(row&&empty){if(editing())return false;return await pull(true,local,id)}
    if(row&&canonical(row.payload)===canonical(JSON.parse(local))){localStorage.setItem(BIND,JSON.stringify({userId:id,revision:Number(row.revision)}));localStorage.setItem(OWNER,id);localStorage.setItem(BASE,local);lastJSON=local;status('اطلاعات این دستگاه با حساب یکسان است؛ همگام‌سازی فعال شد.');return true}
    status(row?(emptySnapshot(row)?'نسخهٔ حساب خالی است؛ اطلاعات این گوشی محفوظ است. برای انتقال، «ذخیرهٔ اطلاعات این دستگاه در حساب» را بزن.':'این دستگاه و حساب اطلاعات متفاوت دارند؛ اطلاعات محلی حفظ شد. ابتدا پشتیبان بگیر، سپس نسخهٔ حساب را دریافت کن.'):empty?'حساب هنوز اطلاعاتی ندارد؛ در گوشیِ دارای اطلاعات، «انتقال اطلاعات این مرورگر به حساب» را بزن.':'اطلاعات این گوشی هنوز فقط محلی است؛ یک‌بار «انتقال اطلاعات این مرورگر به حساب» را بزن تا روی دستگاه‌های دیگر هم بیاید.');return false;
   }
   if(!baseline){
    if(row&&canonical(row.payload)===canonical(JSON.parse(local))){lastJSON=local;localStorage.setItem(BASE,local);localStorage.setItem(BIND,JSON.stringify({userId:id,revision:Number(row.revision)}));status('گوشی و دسکتاپ به حساب متصل‌اند؛ همگام‌سازی فعال است.');return true}
    status('برای شروع همگام‌سازی، نسخهٔ حساب را دریافت کن یا اطلاعات فعلی را بررسی و به حساب منتقل کن.');return false;
   }
   lastJSON=baseline;
   if(Number(row?.revision||0)>Number(binding.revision)){
    if(local!==baseline){status('در هر دو دستگاه تغییر وجود دارد؛ تغییرات محلی حفظ شد. ابتدا پشتیبان بگیر و نسخهٔ حساب را بررسی کن.');return false}
    if(editing()){status('تغییرات دستگاه دیگر آمادهٔ دریافت است؛ پس از پایان ویرایش دریافت می‌شود.');return false}
    return await pull(true,local,id);
   }
   if(Number(row?.revision||0)!==Number(binding.revision))throw Error('revision_conflict');
   if(local!==baseline)return await push();
   status('همگام‌سازی فعال • آخرین بررسی '+new Date().toLocaleTimeString('fa-IR'));return true;
  }catch(e){status(fail(e));return false}finally{checking=false}
 }
 async function boot(){if(booting)return booting;booting=(async()=>{try{const {data,error}=await client.auth.getSession();if(error)throw error;sessionUI(data.session);if(data.session){status('وارد حساب '+(user.email||'خودت')+' شده‌ای؛ در حال بررسی همگام‌سازی…');try{await identity()}catch(e){if(e.status===401||/invalid.*jwt|session.*missing|refresh.*token.*invalid/i.test(e.message||''))sessionUI(null);throw e}await sync()}else status('وارد حساب نشده‌ای؛ پروژه‌های قابل مشاهده ممکن است فقط در همین مرورگر ذخیره باشند.')}catch(e){if(authPhase==='loading')authPhase='signed-out';status(fail(e))}finally{refresh()}})();try{return await booting}finally{booting=null}}

 const oldSettings=settings;settings=function(){return oldSettings().replace('ذخیرهٔ مرکزی و ورود کاربران هنوز فعال نیست.','برای ذخیرهٔ مرکزی از بخش حساب همین صفحه استفاده کن؛ اشتراک دفتر بین همکاران هنوز فعال نیست.').replace('<main class="phone-content">','<main class="phone-content">'+card())};
 const oldDashboard=dashboard;dashboard=function(){return oldDashboard().replace(/<div class="card" style="margin-bottom:14px"><strong>حفظ اطلاعات و انتقال به گوشی<\/strong>[\s\S]*?<\/div>/,'').replace('<div class="phone-head-actions">','<div class="phone-head-actions"><button type="button" class="cloud-login-button" data-cloud-login onclick="'+(user?'openCloudAccountMenu()':'openCloudLogin()')+'">'+accountLabel()+'</button>').replace('<main class="phone-content">','<main class="phone-content">'+(user?'<p id="cloudBadge" class="cloud-sync-note" role="status">'+esc(note)+'</p>':''))};

 const oldSave=save;save=function(){oldSave();if(user&&getBinding()?.userId===user.id){clearTimeout(timer);timer=setTimeout(()=>sync(),1500)}};
 const interval=setInterval(sync,15000);
 window.addEventListener('online',sync);window.addEventListener('focus',sync);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')sync()});
 window.PeymanyarCloud={push,pull:()=>pull(false),sync,boot,getBinding,card,client,stop:()=>{clearInterval(interval);clearTimeout(timer)}};
 if(client){client.auth.onAuthStateChange((event,session)=>{if(['INITIAL_SESSION','SIGNED_IN','TOKEN_REFRESHED','USER_UPDATED','PASSWORD_RECOVERY'].includes(event)){sessionUI(session);if(event==='SIGNED_IN')setTimeout(boot,0)}else if(event==='SIGNED_OUT'){sessionUI(null);status('از حساب خارج شده‌ای؛ اطلاعات محلی همچنان در مرورگر است.');refresh()}});boot()}else{authPhase='signed-out';render()}
 if(new URLSearchParams(location.search).get('settings')==='1')setTimeout(()=>{go('settings');document.getElementById('cloudAccount')?.scrollIntoView?.({block:'start'})},0);
})();
