(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PeymanyarCommand=api})(typeof self!=='undefined'?self:this,function(){
 const faDigits='۰۱۲۳۴۵۶۷۸۹',arDigits='٠١٢٣٤٥٦٧٨٩';
 const clean=s=>String(s||'').replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/[‌]/g,' ').replace(/[؛،]/g,' ').replace(/\s+/g,' ').trim();
 const digits=s=>clean(s).replace(/[۰-۹]/g,d=>faDigits.indexOf(d)).replace(/[٠-٩]/g,d=>arDigits.indexOf(d)).replace(/[٬,]/g,'');
 const wordValues={صفر:0,یک:1,یه:1,دو:2,سه:3,چهار:4,پنج:5,شش:6,شیش:6,هفت:7,هشت:8,نه:9,ده:10,یازده:11,دوازده:12,سیزده:13,چهارده:14,پانزده:15,شانزده:16,هفده:17,هجده:18,نوزده:19,بیست:20,سی:30,چهل:40,پنجاه:50,شصت:60,هفتاد:70,هشتاد:80,نود:90,صد:100,یکصد:100,دویست:200,سیصد:300,چهارصد:400,پانصد:500,ششصد:600,هفتصد:700,هشتصد:800,نهصد:900};
 const scales={هزار:1e3,میلیون:1e6,میلیارد:1e9};
 const numericWord=w=>w==='و'||Object.hasOwn(wordValues,w)||Object.hasOwn(scales,w)||/^\d+(?:\.\d+)?$/.test(w);
 function wordsNumber(words){let total=0,current=0,used=false;for(const word of words){if(word==='و')continue;if(/^\d+(?:\.\d+)?$/.test(word)){current+=Number(word);used=true;continue}if(Object.hasOwn(wordValues,word)){current+=wordValues[word];used=true;continue}if(Object.hasOwn(scales,word)){current=(current||1)*scales[word];total+=current;current=0;used=true;continue}return null}return used?total+current:null}
 function amountOf(text){const s=digits(text);let m=s.match(/(\d+(?:\.\d+)?)\s*(میلیارد|میلیون|هزار)?\s*(?:تومان|تومن|ریال)/);if(!m)m=s.match(/(\d+(?:\.\d+)?)\s*(میلیارد|میلیون|هزار)(?=\s|$)/);if(m){let n=Number(m[1]);if(m[2]==='هزار')n*=1e3;if(m[2]==='میلیون')n*=1e6;if(m[2]==='میلیارد')n*=1e9;if(/ریال/.test(m[0]))n/=10;return Math.round(n)}
  const tokens=s.split(' ');let end=tokens.findIndex(w=>/^(?:تومان|تومن|ریال)$/.test(w));if(end<0){for(let i=tokens.length-1;i>=0;i--)if(Object.hasOwn(scales,tokens[i])){end=i+1;break}}if(end<0)return 0;let start=end-1;while(start>=0&&numericWord(tokens[start]))start--;const value=wordsNumber(tokens.slice(start+1,end));if(value===null)return 0;return Math.round(/ریال/.test(tokens[end]||'')?value/10:value)}
 const monthNames={فروردین:1,اردیبهشت:2,خرداد:3,تیر:4,مرداد:5,شهریور:6,مهر:7,آبان:8,آذر:9,دی:10,بهمن:11,اسفند:12};
 const pad=n=>String(Number(n)||0).padStart(2,'0');
 const validDate=(year,month,day)=>{year=Number(year);month=Number(month);day=Number(day);const max=month<=6?31:month<=11?30:30;return year>=1300&&year<=1499&&month>=1&&month<=12&&day>=1&&day<=max?`${year}/${pad(month)}/${pad(day)}`:''};
 function persianToday(offset=0){try{const d=new Date();d.setDate(d.getDate()+offset);const parts=new Intl.DateTimeFormat('fa-IR-u-ca-persian-nu-latn',{year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d),get=t=>parts.find(x=>x.type===t)?.value;return validDate(get('year'),get('month'),get('day'))}catch{return''}}
 function shiftPersianDate(value,offset){const p=String(value||'').replace(/-/g,'/').split('/').map(Number);if(p.length!==3||!p.every(Number.isFinite))return persianToday(offset);let[year,month,day]=p,step=offset<0?-1:1;for(let i=0;i<Math.abs(offset);i++){day+=step;if(step<0&&day<1){month--;if(month<1){month=12;year--}day=month<=6?31:month<=11?30:29}else{const max=month<=6?31:month<=11?30:29;if(step>0&&day>max){day=1;month++;if(month>12){month=1;year++}}}}return validDate(year,month,day)}
 function relativeDate(text,fallback){const s=digits(text),base=digits(fallback||persianToday()).replace(/-/g,'/');if(/پریروز|پس پریروز/.test(s))return shiftPersianDate(base,-2);if(/دیروز/.test(s))return shiftPersianDate(base,-1);if(/امروز/.test(s))return shiftPersianDate(base,0);const m=s.match(/(\d+|یک|یه|دو|سه|چهار|پنج|شش|شیش|هفت|هشت|نه|ده)\s+روز\s+پیش/);if(m){const n=/^\d+$/.test(m[1])?Number(m[1]):wordsNumber([m[1]]);return shiftPersianDate(base,-(n||0))}return''}
 function dateInfo(text,fallback){const s=digits(text),fallbackDate=digits(fallback||persianToday()).replace(/-/g,'/'),fallbackYear=Number((fallbackDate.match(/1[34]\d{2}/)||[])[0])||Number((persianToday().match(/1[34]\d{2}/)||[])[0]);let m=s.match(/(1[34]\d{2})[\/-](\d{1,2})[\/-](\d{1,2})/);if(m)return{date:validDate(m[1],m[2],m[3])||fallbackDate,source:'explicit-full',explicit:true};m=s.match(/(\d{1,2})[\/-](\d{1,2})[\/-](1[34]\d{2})/);if(m)return{date:validDate(m[3],m[2],m[1])||fallbackDate,source:'explicit-full',explicit:true};for(const[name,month]of Object.entries(monthNames)){if(!s.includes(name))continue;const year=Number((s.match(/1[34]\d{2}/)||[])[0])||fallbackYear;const around=s.match(new RegExp(`(?:روز\\s*)?(\\d{1,2})\\s*${name}|${name}\\s*(?:ماه\\s*)?(\\d{1,2})`));if(around){const day=Number(around[1]||around[2]);return{date:validDate(year,month,day)||fallbackDate,source:'explicit-named',explicit:true}}}m=s.match(/(?:تاریخ|مورخ|روز)\s*(\d{1,2})[\/-](\d{1,2})(?![\/-]\d)/);if(!m)m=s.match(/\b(\d{1,2})[\/-](\d{1,2})\b(?![\/-])/);if(m)return{date:validDate(fallbackYear,m[2],m[1])||fallbackDate,source:'explicit-short',explicit:true};const relative=relativeDate(s,fallbackDate);if(relative)return{date:relative,source:'relative',explicit:true};return{date:fallbackDate,source:'default',explicit:false}}
 function dateOf(text,fallback){return dateInfo(text,fallback).date}
 const between=(s,re,stops)=>{const m=s.match(re);if(!m)return'';return clean(m[1].split(new RegExp(`\\s+(?:${stops.join('|')})\\s*`))[0]).replace(/^(?:به نام|بنام|اسم)\s+/,'').replace(/^(?:بساز|ایجاد(?: کن| شود)?|تعریف کن|ثبت کن)$/,'')};
 function entity(text,list){const source=clean(text),direct=list.find(x=>source.includes(clean(x.name)));if(direct)return direct;const sourceWords=new Set(source.split(' ').filter(w=>w.length>2));const scored=list.map(item=>({item,hits:clean(item.name).split(' ').filter(w=>sourceWords.has(w)).length})).filter(x=>x.hits);if(!scored.length)return null;scored.sort((a,b)=>b.hits-a.hits);return scored.length===1||scored[0].hits>scored[1].hits?scored[0].item:null}
 function datesOf(text,fallback){const s=digits(text),matches=s.match(/(?:1[34]\d{2}[\/-]\d{1,2}[\/-]\d{1,2}|\d{1,2}[\/-]\d{1,2}[\/-]1[34]\d{2})/g)||[];return matches.map(raw=>dateInfo(raw,fallback).date)}
 function monthRange(text,fallback){const s=digits(text),entry=Object.entries(monthNames).find(([name])=>s.includes(name));if(!entry)return null;const year=Number((s.match(/1[34]\d{2}/)||[])[0])||Number((String(fallback||persianToday()).match(/1[34]\d{2}/)||[])[0]),month=entry[1],last=month<=6?31:month<=11?30:29;return{from:validDate(year,month,1),to:validDate(year,month,last),label:entry[0]}}
 function parse(input,db,today){const text=clean(input),normalized=digits(text);const projects=db.projects||[],people=db.people||[];const project=entity(text,projects);let person=entity(text,people);if(!person&&project){const byRole=people.filter(p=>(!p.project||p.project===project.name)&&p.role&&text.includes(clean(p.role)));if(byRole.length===1)person=byRole[0]}const dateMeta=dateInfo(text,today),date=dateMeta.date;
  if(/(?:^|\s)(?:یک\s+)?پروژه(?:\s+جدید)?(?:\s+به نام)?[^.]{0,100}(?:بساز|ایجاد|تعریف)/.test(text)){
   const name=between(text,/(?:به نام|بنام|اسم)\s+(.+)/,['کارفرما','با کارفرما','در','واقع در','بودجه','مبلغ','شروع','بساز','ایجاد','تعریف','ثبت'])||between(text,/پروژه(?: جدید)?\s+(.+)/,['بساز','ایجاد کن','ایجاد شود','تعریف کن','ثبت کن','کارفرما','در','بودجه']);
   const client=between(text,/(?:کارفرما(?:ی آن)?|با کارفرما)\s+(.+)/,['در','واقع در','بودجه','مبلغ','شروع','بساز','ایجاد','تعریف','ثبت']);
   const location=between(text,/(?:واقع در|موقعیت|آدرس)\s+(.+)/,['بودجه','مبلغ','شروع','بساز','ایجاد','تعریف','ثبت']);
   const progress=Number((normalized.match(/(\d+)\s*(?:درصد|٪)\s*(?:پیشرفت)?/)||[])[1]||0),duplicate=name&&projects.some(p=>clean(p.name)===clean(name));
   return {intent:'project_create',label:'ساخت پروژه جدید',name,client,location,budget:amountOf(text),progress,date,missing:[!name&&'نام پروژه',duplicate&&'این پروژه قبلاً ثبت شده است'].filter(Boolean)};
  }
  if(/(?:(?:پیمانکار|استادکار|کارگر|نیرو|فرد).*(?:جدید|اضافه|تعریف|ثبت|بساز|ایجاد)|به عنوان\s+(?:پیمانکار|استادکار|کارگر|نیرو).*(?:ثبت|اضافه|تعریف|بساز|ایجاد))/.test(text)||(/(?:با\s+(?:تخصص|عنوان|نقش)|به\s+عنوان)\s+.+?(?:\s+(?:در|برای)\s+پروژه\s+.+?)?\s+(?:ثبت|اضافه|تعریف|ایجاد|بساز)(?:\s|$)/.test(text)&&!/پرداخت|هزینه|واریز|دریافت/.test(text))){
   const roles=['جوشکار','بنا','برقکار','لوله کش','لوله‌کش','نگهبان','کارگر','کابینت کار','کابینت‌کار','نقاش','گچ کار','گچ‌کار','سرامیک کار','سرامیک‌کار','تاسیسات کار','تأسیسات کار','تأسیسات‌کار'];
   const specialty=text.match(/(?:با\s+(?:تخصص|عنوان|نقش)|تخصص(?:ش|ِ او)?|به\s+عنوان)\s+(.+?)(?=\s+(?:به\s+(?:عنوان\s+)?پیمانکار(?:ان|ها|ا)?|در|برای)\s+پروژه|\s+به\s+پیمانکار(?:ان|ها|ا)?|\s+(?:ثبت|اضافه|تعریف|بساز|ایجاد)(?:\s|$)|$)/);
   const role=clean(specialty?.[1]||'').replace(/^(?:پیمانکار|نیرو|کارگر)\s+/,'')||roles.find(r=>text.includes(r))||'';
   let name=between(text,/(?:به نام|بنام|اسم)\s+(.+)/,[...roles,'با تخصص','با عنوان','با نقش','تخصص','به عنوان','برای پروژه','در پروژه','شماره','موبایل','اضافه','تعریف','ثبت','بساز','ایجاد']);
   if(!name){const byTitle=text.match(/^(.*?)\s+(?:با\s+(?:تخصص|عنوان|نقش)|به\s+عنوان|به\s+پیمانکار(?:ان|ها|ا)?\s+اضافه)/);name=clean(byTitle?.[1]||'').replace(/^(?:آقای|خانم|مهندس|استاد)\s+/,'')}
   if(!name)name=between(text,/(?:پیمانکار|استادکار|کارگر|نیرو|فرد)(?: جدید)?\s+(.+)/,[...roles,'برای پروژه','در پروژه','شماره','موبایل','اضافه','تعریف','ثبت','بساز','ایجاد']);
   name=clean(name).replace(/\s+(?:را|رو)$/,'');
   const phone=(normalized.match(/09\d{9}/)||[])[0]||'',duplicate=name&&people.some(p=>clean(p.name)===clean(name));
   return {intent:'person_create',label:'تعریف پیمانکار یا نیرو',name,role,project:project?.name||'',phone,date,dateSource:dateMeta.source,missing:[!name&&'نام شخص'].filter(Boolean),duplicate:!!duplicate};
  }
  if(/(?:گزارش روزانه|گزارش کارگاه|امروز).*(?:ثبت|بنویس|کار|انجام|شد)/.test(text)){
   const workers=Number((normalized.match(/(\d+)\s*(?:نفر|کارگر|نیرو)/)||[])[1]||0),weather=(text.match(/(?:هوا|وضعیت هوا)\s+(آفتابی|بارانی|برفی|ابری|گرم|سرد)/)||[])[1]||'';
   return {intent:'daily_create',label:'ثبت گزارش روزانه',project:project?.name||'',date,dateSource:dateMeta.source,workers,weather,text,missing:[!project&&'نام پروژه'].filter(Boolean)};
  }
  if(/(?:چقدر|جمع|مجموع|مانده|گزارش(?: مالی)?|ریز پرداخت|صورت حساب|حساب\s+(?:فلانی|پیمانکار|پروژه).*(?:نشان|بگو|می خواهم|میخوام))/.test(text)){const range=datesOf(text,today),month=monthRange(text,today);return {intent:'financial_query',label:'گزارش مالی',person:person?.name||'',project:project?.name||'',role:person?.role||'',dateFrom:month?.from||range[0]||'',dateTo:month?.to||range[1]||range[0]||'',periodLabel:month?.label||'',missing:[]}}
  if(/(?:پرداخت|واریز|هزینه|خرید|دریافت|گرفتم|دادم|خریدم|تنخواه)/.test(text)){
   const kind=/(?:دریافت|گرفتم|واریز شد|از کارفرما گرفتم)/.test(text)?'income':'expense';
   const contractorPayment=kind==='expense'&&(/(?:پرداخت|دادم|واریز)/.test(text)||!!person);
   const category=/ماسه|سیمان|گچ|آجر|بلوک|بتن|سنگ|کاشی|سرامیک|مصالح/.test(text)?'خرید مصالح':/یراق|لولا|دستگیره|پیچ/.test(text)?'خرید یراق‌آلات':/ابزار|دریل|فرز|مته/.test(text)?'خرید ابزار':/وانت/.test(text)?'کرایه وانت':/اسنپ|تاکسی/.test(text)?'کرایه اسنپ':/جرثقیل/.test(text)?'کرایه جرثقیل':/نگهبان|نگهبانی/.test(text)?'هزینه نگهبانی':/جریمه|عوارض/.test(text)?'عوارض و جریمه':/(?:خرید|فاکتور|خریدم)/.test(text)?'خرید لوازم':/تنخواه/.test(text)?'تنخواه':/حقوق|دستمزد|کارگر|کارگری/.test(text)?'حقوق و دستمزد':kind==='income'?'دریافت از کارفرما':contractorPayment?'پرداخت پیمانکار':'هزینه عمومی';
   const amount=amountOf(text),candidate=between(text,/(?:به|از)\s+(.+)/,['برای پروژه','در پروژه','پروژه','مبلغ','به مبلغ','پرداخت','واریز','دادم','گرفتم','تومان','تومن','ریال']).replace(/^(?:حساب\s+)?(?:آقای|خانم|مهندس|استاد)\s+/,'')||'';
   return {intent:'transaction_create',label:kind==='income'?'ثبت دریافت':'ثبت پرداخت یا هزینه',project:project?.name||'',party:person?.name||candidate||(category==='هزینه عمومی'?'هزینه پروژه':''),amount,date,dateSource:dateMeta.source,kind,category,note:text,missing:[!project&&'نام پروژه',!amount&&'مبلغ'].filter(Boolean)};
  }
  return {intent:'unknown',label:'فرمان نامشخص',missing:['نوع عملیات']};
 }
 return {parse,amountOf,dateOf,dateInfo,datesOf,monthRange,clean};
});
