/* Editable reports and explicit daily labour counts. Existing audio and IDs stay intact. */
(function(){
'use strict';
const arg=x=>esc(JSON.stringify(x));
const num=s=>Number(String(s).replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d)).replace(/٫/g,'.').replace(/[٬,\s]/g,''));
const norm=s=>PeymanyarCommand.clean(s).replace(/آ/g,'ا');
function projectFor(r){const linked=db.projects.find(p=>String(p.id)===String(r.projectId));if(linked)return linked;const matches=db.projects.filter(p=>[p.name,...(p.aliases||[])].some(n=>norm(n)===norm(r.project)));return matches.length===1?matches[0]:null}
function labourFields(prefix,row={}){return field('تعداد کارگر روزمزد (از کل نیروها)',`<input id="${prefix}Labour" inputmode="numeric" value="${esc(row.labourWorkers??'')}" placeholder="مثلاً ۷؛ خالی یعنی مشخص نشده">`)+field('سهم روز کارگری',`<input id="${prefix}Days" inputmode="decimal" value="${esc(row.workDays??1)}" placeholder="۱ یا ۰٫۵">`)+`<p class="full">۷ کارگر × یک روز = ۷ نفرـروز؛ تعداد نیرو می‌تواند شامل استادکار و پیمانکار هم باشد.</p>`}
function values(prefix){const raw=v(prefix+'Labour'),labour=raw===''?null:num(raw),days=num(v(prefix+'Days'));if(labour!==null&&(!Number.isInteger(labour)||labour<0))throw Error('تعداد کارگر روزمزد باید عدد صحیح و غیرمنفی باشد');if(!Number.isFinite(days)||days<=0||days>1)throw Error('سهم روز را بین صفر و یک وارد کن؛ مثلاً ۱ یا ۰٫۵');return{labourWorkers:labour,workDays:days}}
function read(prefix,projectId){const p=db.projects.find(p=>String(p.id)===String(projectId));if(!p)throw Error('پروژه را از فهرست انتخاب کن');const date=PeymanyarCalendar.parse(v(prefix+'Date'));if(!date)throw Error('تاریخ شمسی معتبر وارد کن');const workers=num(v(prefix+'Workers'));if(!Number.isInteger(workers)||workers<0)throw Error('تعداد نیرو باید عدد صحیح و غیرمنفی باشد');const text=v(prefix+'Text');if(!text)throw Error('شرح گزارش را وارد کن');const labour=values(prefix);if(labour.labourWorkers!==null&&labour.labourWorkers>workers)throw Error('تعداد کارگر روزمزد نمی‌تواند از کل نیروها بیشتر باشد');return{projectId:p.id,project:p.name,date:PeymanyarCalendar.key(date.y,date.m,date.d),workers,weather:v(prefix+'Weather'),text,...labour}}
function totals(rows){const days=new Map();let unknown=0;for(const r of rows){if(r.labourWorkers==null){unknown++;continue}const date=PeymanyarCalendar.parse(r.date);if(!date){unknown++;continue}const count=Number(r.labourWorkers),share=Number(r.workDays??1);if(!Number.isInteger(count)||count<0||!Number.isFinite(share)||share<=0||share>1){unknown++;continue}const k=PeymanyarCalendar.key(date.y,date.m,date.d);days.set(k,Math.max(days.get(k)||0,count*share))}return{personDays:[...days.values()].reduce((a,b)=>a+b,0),days:days.size,unknown}}
function summary(rows){const t=totals(rows);return `<section class="project-hub-summary"><div class="project-hub-summary-head"><h3>کارکرد کارگران روزمزد</h3><span>براساس گزارش‌های روزانه</span></div><table aria-label="کارکرد کارگری"><thead><tr><th>جمع نفرـروز</th><th>روزهای دارای ثبت</th><th>گزارش بدون تعداد کارگر</th></tr></thead><tbody><tr><td>${fa(t.personDays)}</td><td>${fa(t.days)}</td><td>${fa(t.unknown)}</td></tr></tbody></table><p>این جمع تعداد افراد یکتا نیست. برای جلوگیری از دوباره‌شماری، در هر تاریخ بیشترین کارکرد ثبت‌شده حساب می‌شود. گزارش‌های قدیمی تا تعیین تعداد کارگر در جمع وارد نمی‌شوند.</p></section>`}
function card(r){const p=projectFor(r);return `<article class="phone-row"><div class="phone-row-head"><strong>${esc(p?.name||r.project||'پروژه مشخص نشده')} • ${esc(r.date||'تاریخ مشخص نشده')}</strong><span>${fa(r.workers||0)} نفر</span></div><p class="project-report-text">${esc(r.text||r.note||'')}</p><small>هوا: ${esc(r.weather||'ثبت نشده')} • کارگر روزمزد: ${r.labourWorkers==null?'مشخص نشده':fa(r.labourWorkers)}${r.labourWorkers!=null?' • '+fa(r.workDays??1)+' روز':''}</small><div class="project-section-actions"><button class="btn" onclick="openLongDailyDetail(${arg(r.id)})">مشاهده و صوت</button><button class="btn" onclick="openDailyEditor(${arg(r.id)})">✎ ویرایش گزارش</button>${p?`<button class="btn" onclick="openProjectSection(${arg(p.id)},'daily')">رفتن به پروژه</button>`:''}</div></article>`}
let editing=null;
window.openDailyEditor=function(id){editing=db.daily.find(r=>String(r.id)===String(id));if(!editing)return;closeLongDailyDetail();document.getElementById('dailyEditor')?.remove();const r=editing,p=projectFor(r);document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="dailyEditor"><div class="dialog bulk-cash-dialog" role="dialog" aria-modal="true" aria-label="ویرایش گزارش روزانه"><div class="dialog-head"><h2>ویرایش گزارش روزانه</h2><button class="close" onclick="document.getElementById('dailyEditor').remove()">×</button></div><div class="form-grid">${field('پروژه',`<select id="deProject"><option value="">انتخاب پروژه</option>${db.projects.map(x=>`<option value="${esc(x.id)}" ${x===p?'selected':''}>${esc(x.name)}</option>`).join('')}</select>`)}${field('تاریخ گزارش',`<input id="deDate" data-persian-calendar value="${esc(r.date||'')}">`)}${field('تعداد کل نیروها',`<input id="deWorkers" inputmode="numeric" value="${esc(r.workers||0)}">`)}${field('وضعیت هوا',`<input id="deWeather" value="${esc(r.weather||'')}">`)}${labourFields('de',r)}${field('شرح گزارش',`<textarea id="deText" rows="8">${esc(r.text||r.note||'')}</textarea>`,'full')}</div><p>شناسهٔ گزارش و فایل‌های صوتی حفظ می‌شوند؛ تغییر پروژه، گزارش را به پروژهٔ انتخاب‌شده منتقل می‌کند.</p><button class="btn primary" onclick="saveDailyEditor()">ذخیره تغییرات</button></div></div>`)};
window.saveDailyEditor=function(){if(!editing||!db.daily.includes(editing))return toast('گزارش پیدا نشد');let fields;try{fields=read('de',v('deProject'))}catch(e){return toast(e.message)}const before=structuredClone(editing);Object.assign(editing,fields,{updatedAt:new Date().toISOString()});try{save()}catch(e){for(const k of Object.keys(editing))delete editing[k];Object.assign(editing,before);return toast('ذخیره انجام نشد؛ دوباره تلاش کن')}document.getElementById('dailyEditor')?.remove();editing=null;render();toast('گزارش و ارتباط پروژه اصلاح شد')};
const detail=openLongDailyDetail;openLongDailyDetail=async function(id){await detail(id);const r=db.daily.find(r=>String(r.id)===String(id)),box=document.querySelector('#dailyDetailModal .dialog');if(!r||!box)return;const p=projectFor(r);box.insertAdjacentHTML('beforeend',`<p>کارگر روزمزد: ${r.labourWorkers==null?'مشخص نشده':fa(r.labourWorkers)+' نفر × '+fa(r.workDays??1)+' روز'}</p><div class="project-section-actions"><button class="btn primary" onclick="openDailyEditor(${arg(r.id)})">✎ ویرایش مشخصات گزارش</button>${p?`<button class="btn" onclick="closeLongDailyDetail();openProjectSection(${arg(p.id)},'daily')">رفتن به پروژهٔ ${esc(p.name)}</button>`:''}</div>`)};
daily=function(){return layout(`<div class="section-head"><div><h2>گزارش‌های روزانه</h2><p>پروژه، تاریخ، نیروها و شرح هر گزارش قابل اصلاح است.</p></div><button class="btn primary" onclick="openLongDailyReport()">＋ گزارش جدید / صوتی</button></div><div class="project-section-list">${db.daily.map(card).join('')||empty()}</div>`,'گزارش‌ها')};
const hub=projectDetail;projectDetail=function(){const html=hub(),p=db.projects.find(p=>String(p.id)===String(selectedProjectId));if(!p)return html;const holder=document.createElement('div');holder.innerHTML=html;const view=holder.querySelector('[data-project-view=daily]');if(!view)return html;const rows=PeymanyarProjectHub.data(p).daily;const list=view.querySelector('.project-section-list');if(list){list.innerHTML=[...rows].sort((a,b)=>normalizeDateValue(b.date).localeCompare(normalizeDateValue(a.date))).map(card).join('')||empty();list.insertAdjacentHTML('beforebegin',summary(rows))}return holder.innerHTML};
const longOpen=openLongDailyReport;openLongDailyReport=function(...args){longOpen(...args);const grid=document.querySelector('#dailyLongModal .form-grid');if(grid&&!document.getElementById('dailyVoiceLabour'))grid.insertAdjacentHTML('beforeend',labourFields('dailyVoice'))};
const formOpen=openForm;openForm=function(type){formOpen(type);if(type==='daily')document.querySelector('#modal .form-grid')?.insertAdjacentHTML('beforeend',labourFields('f'))};
const submit=submitForm;submitForm=function(type){if(type!=='daily')return submit(type);let fields;try{const p=projectFor({project:v('fProject')});fields=read('f',p?.id)}catch(e){return toast(e.message)}const row={id:uid(),...fields,source:'manual'};db.daily.unshift(row);try{save()}catch(e){db.daily.splice(db.daily.indexOf(row),1);return toast('گزارش ذخیره نشد؛ دوباره تلاش کن')}closeModal();render();toast('گزارش ثبت شد')};
const suggest=suggestDailyReportFields;suggestDailyReportFields=function(...args){suggest(...args);const text=norm(v('dailyVoiceText'));const m=text.match(/(\d+|یک|دو|سه|چهار|پنج|شش|هفت|هشت|نه|ده)\s*(?:تا\s*|نفر\s*)?کارگر/);const input=document.getElementById('dailyVoiceLabour');if(m&&input&&!input.value){const words=['صفر','یک','دو','سه','چهار','پنج','شش','هفت','هشت','نه','ده'];const count=/^\d+$/.test(m[1])?Number(m[1]):words.indexOf(m[1]);input.value=count;const workers=document.getElementById('dailyVoiceWorkers');if(workers&&!workers.value)workers.value=count}};
window.PeymanyarDaily={totals,projectFor,values,read};render();
})();
