(function(){
 'use strict';
 const states=new Map();let personProject='';
 const headers=['ردیف','تاریخ','پروژه','طرف حساب','شرح / بابت','دریافتی (تومان)','پرداختی (تومان)','وضعیت سند'];
 const defaults=()=>({from:'',to:'',order:'asc',kind:'all',search:''});
 function state(key){if(!states.has(key))states.set(key,defaults());return states.get(key)}
 function sorted(rows,order='asc'){return rows.map((row,index)=>({row,index,date:normalizeDateValue(row.date)})).sort((a,b)=>{if(!a.date&&!b.date)return a.index-b.index;if(!a.date)return 1;if(!b.date)return -1;return (a.date.localeCompare(b.date)||a.index-b.index)*(order==='desc'?-1:1)}).map(x=>x.row)}
 function filtered(rows,s,person=''){const from=normalizeDateValue(s.from),to=normalizeDateValue(s.to);return sorted(rows.filter(r=>{const date=normalizeDateValue(r.date);return(!from||date&&date>=from)&&(!to||date&&date<=to)&&(s.kind==='all'||r.kind===s.kind||s.kind==='income'&&r.kind==='expense'&&r.fundingSource==='client-direct'&&!person)&&(!s.search||[r.party,r.project,r.category,r.note].some(v=>String(v||'').includes(s.search)))}),s.order)}
 function ledgerSummary(rows){const s=reportSummary(rows);return {...s,received:activeReport.person?s.received:(s.projectReceived??s.received)}}
 function matrix(rows){return rows.map((r,i)=>[i+1,normalizeDateValue(r.date)||r.date||'ثبت نشده',r.project||'بدون پروژه',r.party||'بدون طرف حساب',(r.note||r.category||'ثبت مالی')+(r.fundingSource==='client-direct'?' — پرداخت مستقیم '+(r.fundingClient||'کارفرما')+'؛ خارج از حساب مدیر':''),r.kind==='income'||r.fundingSource==='client-direct'&&r.kind==='expense'&&!activeReport.person?Number(r.amount)||0:0,r.kind==='expense'?Number(r.amount)||0:0,transactionHasDocument(r)?'سند موجود':'بدون سند'])}
 function activate(rows,title,project='',person='',s=defaults()){activeReport={title,rows:filtered(rows,s,person),project,person,dateFrom:s.from,dateTo:s.to,order:s.order,kind:s.kind,search:s.search};return activeReport.rows}
 window.ledgerSet=function(key,field,value){const s=state(key);s[field]=value;if(s.from&&!normalizeDateValue(s.from)||s.to&&!normalizeDateValue(s.to)){toast('تاریخ را به شکل ۱۴۰۵/۰۷/۰۱ وارد کن');return}if(s.from&&s.to&&normalizeDateValue(s.from)>normalizeDateValue(s.to)){toast('تاریخ شروع باید قبل از پایان باشد');return}if(key==='modal')refreshModal();else render()};
 const originalOpenPerson=openPerson;openPerson=function(id){personProject='';originalOpenPerson(id)};
 window.openLedgerPerson=function(id,project){document.getElementById('reportModal')?.remove();originalOpenPerson(id);personProject=project||'';render()};
 window.ledgerPersonScope=function(project){personProject=project;render()};
 function controls(key,s){return `<form class="ledger-filters" onsubmit="event.preventDefault();ledgerApply('${key}')"><label>از تاریخ شمسی<input id="ledgerFrom" value="${esc(s.from)}" placeholder="۱۴۰۵/۰۷/۰۱" inputmode="numeric"></label><label>تا تاریخ شمسی<input id="ledgerTo" value="${esc(s.to)}" placeholder="۱۴۰۵/۰۷/۳۰" inputmode="numeric"></label><label>نوع گردش<select onchange="ledgerSet('${key}','kind',this.value)">${[['all','همه گردش‌ها'],['expense','فقط پرداخت‌ها'],['income','فقط دریافت‌ها']].map(([v,t])=>`<option value="${v}" ${s.kind===v?'selected':''}>${t}</option>`).join('')}</select></label><label>ترتیب تاریخ<select onchange="ledgerSet('${key}','order',this.value)"><option value="asc" ${s.order==='asc'?'selected':''}>قدیمی به جدید</option><option value="desc" ${s.order==='desc'?'selected':''}>جدید به قدیمی</option></select></label><label>جست‌وجو<input id="ledgerSearch" value="${esc(s.search)}" placeholder="نام یا شرح پرداخت"></label><button class="btn primary" type="submit">اعمال فیلتر</button><button class="btn" type="button" onclick="ledgerReset('${key}')">پاک‌کردن فیلتر</button></form>`}
 window.ledgerApply=function(key){const form=key==='modal'?document.querySelector('#reportModal .ledger-filters'):document.querySelector('#app .ledger-filters');const s=state(key),from=form.querySelector('#ledgerFrom').value.trim(),to=form.querySelector('#ledgerTo').value.trim();if(from&&!normalizeDateValue(from)||to&&!normalizeDateValue(to)||from&&to&&normalizeDateValue(from)>normalizeDateValue(to))return toast('بازهٔ تاریخ معتبر وارد کن؛ مثال ۱۴۰۵/۰۷/۰۱');Object.assign(s,{from,to,search:form.querySelector('#ledgerSearch').value.trim()});if(key==='modal')refreshModal();else render()};
 window.ledgerReset=function(key){states.set(key,defaults());if(key==='modal')refreshModal();else render()};
 function exports(){return `<div class="ledger-exports"><button class="btn" onclick="exportActiveExcel()">↓ Excel</button><button class="btn" onclick="printActiveReport()">↓ PDF / چاپ</button><button class="btn" onclick="exportActiveCSV()">↓ CSV</button><button class="btn" onclick="exportActiveWord()">↓ Word</button></div>`}
 function summary(rows){const s=ledgerSummary(rows);return `<div class="ledger-summary"><div><small>تعداد ردیف</small><strong>${fa(rows.length)}</strong></div><div><small>دریافتی این جدول</small><strong>${money(s.received)}</strong></div><div><small>کل هزینهٔ این جدول</small><strong>${money(s.paid)}</strong></div><div><small>تراز گردش مدیر</small><strong>${money(s.cashBalance??s.received-s.paid)}</strong></div></div>`}
 transactionReportTable=function(rows){const data=matrix(rows),sum=ledgerSummary(rows);return `<div class="ledger-scroll" role="region" aria-label="جدول گردش مالی" tabindex="0"><table class="ledger-table"><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}<th scope="col" class="ledger-actions">عملیات</th></tr></thead><tbody>${rows.map((r,i)=>{const p=knownPerson(r.party),linked=db.people.find(p=>String(p.id)===String(r.personId??r.contractorId)),person=linked||p;return `<tr>${data[i].map((v,j)=>`<td class="${j===5?'ledger-income':j===6?'ledger-expense':j===4?'ledger-description':''}">${j===3&&person?`<button class="ledger-name" onclick="openLedgerPerson(${Number(person.id)},${esc(JSON.stringify(r.project||''))})">${esc(v)}</button>`:j===7?(transactionHasDocument(r)?`<button class="ledger-doc available" onclick="viewDocument(${Number(r.documentId)})">📎 مشاهده سند</button>`:`<button class="ledger-doc missing" onclick="attachTransactionDocument(${Number(r.id)})">＋ افزودن سند</button>`):j===0?fa(v):j===5||j===6?v?fa(v):'—':esc(v)}</td>`).join('')}<td class="ledger-actions"><details class="ledger-row-menu"><summary aria-label="عملیات ردیف ${i+1}">⋯</summary><div><button onclick="openRecordEditor('transaction',${Number(r.id)})">ویرایش ثبت</button><button class="danger" onclick="removeTransaction(${Number(r.id)})">حذف ثبت مالی</button></div></details></td></tr>`}).join('')||`<tr><td colspan="9" class="ledger-empty">هیچ ثبت مالی در این محدوده وجود ندارد.</td></tr>`}</tbody><tfoot><tr><th colspan="5">جمع ${fa(rows.length)} ردیف — تومان</th><td>${fa(sum.received)}</td><td>${fa(sum.paid)}</td><td colspan="2"></td></tr></tfoot></table></div><p class="ledger-mobile-hint">برای دیدن تمام ستون‌ها، جدول را به چپ و راست حرکت بده.</p>`};
 function panel(rows,title,project,person,key){const s=state(key),visible=activate(rows,title,project,person,s);return `<section class="ledger-panel"><div class="ledger-heading"><div><h2>${esc(title)}</h2><p>هر ثبت مالی یک سطر؛ مبالغ به تومان</p></div>${exports()}</div>${controls(key,s)}${summary(visible)}${transactionReportTable(visible)}</section>`}
 function extras(html){const holder=document.createElement('div');holder.innerHTML=html;const main=holder.querySelector('main');if(!main)return '';main.querySelectorAll('.project-hero,.back-btn,.report-actions,.detail-kpis,.project-completion').forEach(x=>x.remove());main.querySelectorAll('.detail-section').forEach(section=>{if(section.querySelector('.ledger-table'))section.remove()});if(page==='projectDetail'){const project=db.projects.find(p=>String(p.id)===String(selectedProjectId));if(project)main.querySelectorAll('[onclick]').forEach(button=>{const match=button.getAttribute('onclick').match(/^openPerson\((\d+)\)$/);if(match)button.setAttribute('onclick',`openLedgerPerson(${match[1]},${JSON.stringify(project.name)})`)})}return `<details class="ledger-extras"><summary>مشخصات، قراردادها و سایر اطلاعات</summary>${main.innerHTML}</details>`}
 const oldProject=projectDetail;projectDetail=function(){const p=db.projects.find(x=>String(x.id)===String(selectedProjectId));if(!p)return oldProject();const extra=extras(oldProject());return layout(`<button class="back-btn" onclick="go('projects')">← پروژه‌ها</button><div class="ledger-context"><h2>${esc(p.name)}</h2><button class="btn" onclick="openEntityNameEditor('project',${Number(p.id)})">ویرایش نام پروژه</button><button class="btn primary" onclick="openQuick()">＋ ثبت مالی</button><button class="btn" onclick="openBulkCash(${esc(JSON.stringify(p.name))})">ثبت گروهی</button></div>${panel(reportRows({project:p.name}),'گزارش مالی پروژهٔ '+p.name,p.name,'','project:'+p.id)}${extra}`,'گزارش مالی پروژه')};
 const oldPerson=personDetail;personDetail=function(){const p=db.people.find(x=>String(x.id)===String(selectedPersonId));if(!p)return oldPerson();const extra=extras(oldPerson()),projects=[...new Set([p.project,...(p.projects||[]),...reportRows({personId:p.id}).map(r=>r.project)].filter(Boolean))],project=personProject,title='حساب '+p.name+' — '+(project?'پروژهٔ '+project:'همهٔ پروژه‌ها');return layout(`<button class="back-btn" onclick="${project?`openProject(${Number(db.projects.find(p=>p.name===project)?.id||0)})`:`go('people')`}">← ${project?'بازگشت به پروژه':'افراد'}</button><div class="ledger-context"><div><h2>${esc(p.name)}</h2><p>${esc(p.role||'تخصص ثبت نشده')}</p></div><button class="btn" onclick="openEntityNameEditor('person',${Number(p.id)})">ویرایش نام و تخصص</button><label>محدودهٔ حساب<select onchange="ledgerPersonScope(this.value)"><option value="">همهٔ پروژه‌ها</option>${projects.map(name=>`<option value="${esc(name)}" ${name===project?'selected':''}>${esc(name)}</option>`).join('')}</select></label></div>${panel(reportRows({personId:p.id,project}),title,project,p.name,'person:'+p.id+':'+project)}${extra}`,'گزارش مالی شخص')};
 finance=function(){return layout(`<div class="ledger-context"><h2>دفتر گردش مالی</h2><button class="btn primary" onclick="openForm('transaction')">＋ ثبت مالی</button><button class="btn" onclick="openBulkCash()">ثبت گروهی تنخواه</button></div>${panel(db.transactions,'گزارش مالی همهٔ پروژه‌ها','','','finance')}`,'امور مالی')};
 let modalSource=null;
 showReportModal=function(){modalSource={...activeReport,rows:activeReport.rows.slice()};states.set('modal',{...defaults(),from:activeReport.dateFrom||'',to:activeReport.dateTo||''});refreshModal()};
 function refreshModal(){if(!modalSource)return;document.getElementById('reportModal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="reportModal"><div class="dialog ledger-dialog"><div class="dialog-head"><h2>گزارش مالی</h2><button class="close" onclick="document.getElementById('reportModal').remove();render()">×</button></div>${panel(modalSource.rows,modalSource.title,modalSource.project,modalSource.person,'modal')}</div></div>`)}
 reportMatrix=function(){return [headers,...matrix(activeReport.rows)]};
 function exportMatrix(){const s=ledgerSummary(activeReport.rows);return [[activeReport.title],[`بازه: ${activeReport.dateFrom||'ابتدا'} تا ${activeReport.dateTo||'انتها'}`],headers,...matrix(activeReport.rows),['جمع','','','','',s.received,s.paid,'']]}
 exportActiveCSV=function(){const safe=v=>typeof v==='string'&&/^[=+\-@\t\r]/.test(v)?"'"+v:v;download(`${safeFileName()}.csv`,'\ufeff'+exportMatrix().map(row=>row.map(v=>`"${String(safe(v)).replaceAll('"','""')}"`).join(',')).join('\r\n'),'text/csv;charset=utf-8')};
 function printable(){const rows=exportMatrix();return `<html lang="fa" dir="rtl"><head><meta charset="utf-8"><title>${esc(activeReport.title)}</title><style>@page{size:A4 landscape;margin:12mm}body{font-family:Tahoma,sans-serif;color:#17362f;margin:24px}h1{font-size:20px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{padding:8px;border:1px solid #b5c2bc;text-align:right;white-space:pre-wrap;overflow-wrap:anywhere}th{background:#eaf1ed}thead{display:table-header-group}tr{break-inside:avoid}tfoot{font-weight:bold}button{padding:10px;margin-bottom:15px}@media print{button,.print-help{display:none}}</style></head><body><button onclick="window.print()">چاپ / ذخیره PDF</button><p class="print-help">برای خروجی PDF، در پنجرهٔ چاپ گزینهٔ Save as PDF / ذخیره در فایل را انتخاب کن.</p><h1>${esc(rows[0][0])}</h1><p>${esc(rows[1][0])} • ${fa(activeReport.rows.length)} ردیف • مبالغ به تومان</p><table><thead><tr>${headers.map(v=>`<th>${esc(v)}</th>`).join('')}</tr></thead><tbody>${matrix(activeReport.rows).map(row=>`<tr>${row.map(v=>`<td>${typeof v==='number'?fa(v):esc(v)}</td>`).join('')}</tr>`).join('')}</tbody><tfoot><tr>${rows.at(-1).map(v=>`<td>${typeof v==='number'?fa(v):esc(v)}</td>`).join('')}</tr></tfoot></table></body></html>`}
 printActiveReport=function(){const w=window.open('','_blank');if(!w)return toast('اجازهٔ بازشدن پنجرهٔ چاپ را فعال کن');w.document.write(printable());w.document.close();w.onload=()=>w.print()};
 exportActiveWord=function(){download(`${safeFileName()}.doc`,printable(),'application/msword;charset=utf-8')};
 // Native XLSX with typed numeric cells; no service receives financial data.
 const xml=v=>String(v).replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g,'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
 function zip(files){const encoder=new TextEncoder(),parts=[],central=[];let offset=0;const crc=bytes=>{let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=c>>>1^(c&1?0xedb88320:0)}return(c^0xffffffff)>>>0};const header=(size)=>{const b=new Uint8Array(size);return [b,new DataView(b.buffer)]};for(const [name,content]of Object.entries(files)){const n=encoder.encode(name),data=encoder.encode(content),checksum=crc(data),[h,v]=header(30);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint32(14,checksum,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,n.length,true);parts.push(h,n,data);const[c,cv]=header(46);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint32(16,checksum,true);cv.setUint32(20,data.length,true);cv.setUint32(24,data.length,true);cv.setUint16(28,n.length,true);cv.setUint32(42,offset,true);central.push(c,n);offset+=h.length+n.length+data.length}const length=central.reduce((s,b)=>s+b.length,0),[end,ev]=header(22);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,Object.keys(files).length,true);ev.setUint16(10,Object.keys(files).length,true);ev.setUint32(12,length,true);ev.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
 window.exportActiveExcel=function(){const rows=exportMatrix(),cells=rows.map((row,i)=>`<row r="${i+1}">${row.map((v,j)=>{const ref=String.fromCharCode(65+j)+(i+1),style=i===2||i===rows.length-1?1:typeof v==='number'?2:0;return typeof v==='number'?`<c r="${ref}" s="${style}"><v>${v}</v></c>`:`<c r="${ref}" s="${style}" t="inlineStr"><is><t xml:space="preserve">${xml(v)}</t></is></c>`}).join('')}</row>`).join('');const files={
 '[Content_Types].xml':'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>',
 '_rels/.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
 'xl/workbook.xml':'<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="گزارش مالی" sheetId="1" r:id="rId1"/></sheets></workbook>',
 'xl/_rels/workbook.xml.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
 'xl/styles.xml':'<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Tahoma"/></font><font><b/><sz val="11"/><name val="Tahoma"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="3"><xf fontId="0"><alignment horizontal="right" vertical="top" wrapText="1"/></xf><xf fontId="1" numFmtId="3"><alignment horizontal="right" wrapText="1"/></xf><xf fontId="0" numFmtId="3"><alignment horizontal="right"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>',
 'xl/worksheets/sheet1.xml':`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0" rightToLeft="1"><pane ySplit="3" topLeftCell="A4" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="1" width="7" customWidth="1"/><col min="2" max="4" width="22" customWidth="1"/><col min="5" max="5" width="45" customWidth="1"/><col min="6" max="8" width="24" customWidth="1"/></cols><sheetData>${cells}</sheetData><autoFilter ref="A3:H${rows.length-1}"/><printOptions horizontalCentered="1"/><pageMargins left="0.3" right="0.3" top="0.4" bottom="0.4" header="0.2" footer="0.2"/><pageSetup paperSize="9" orientation="landscape" fitToWidth="1" fitToHeight="0"/></worksheet>`};download(`${safeFileName()}.xlsx`,zip(files),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')};
 const ledgerRenderBase=render;render=function(){ledgerRenderBase();if(document.getElementById('reportModal')&&modalSource){modalSource.rows=reportRows({project:modalSource.project,person:modalSource.person,dateFrom:modalSource.dateFrom,dateTo:modalSource.dateTo});refreshModal()}};
 render();
})();
