/* One voice/text entry, explicit operation previews and recoverable incomplete requests. */
(function(){
'use strict';
const labels={daily_create:'گزارش روزانه پروژه',transaction_create:'پرداخت / دریافت',person_create:'ساخت شخص / پیمانکار / فروشنده',project_create:'ساخت پروژه',contract_create:'پیش‌نویس قرارداد',inventory_create:'ورود / خروج انبار',financial_query:'مشاهده گزارش مالی',unknown:'هنوز مشخص نیست'};
let current=null,busy=false,posting=false;
const closeBase=closeUniversalQuick;closeUniversalQuick=function(...args){if(posting&&current)return toast('ذخیره در حال انجام است؛ چند لحظه صبر کن');return closeBase(...args)};
const norm=s=>PeymanyarCommand.clean(s).replace(/آ/g,'ا');
function match(value,rows){const exact=rows.filter(x=>[x.name,...(x.aliases||[])].some(n=>norm(n)===norm(value)));return exact.length===1?exact[0]:null}
function mentioned(text,rows){const s=' '+norm(text)+' ';const hits=rows.map(x=>({x,n:Math.max(0,...[x.name,...(x.aliases||[])].map(n=>s.includes(' '+norm(n)+' ')?norm(n).length:0))})).filter(x=>x.n).sort((a,b)=>b.n-a.n);return hits.length&&(hits.length===1||hits[0].n>hits[1].n)?hits[0].x:null}
function extract(text,key){const m=PeymanyarCommand.clean(text).match(new RegExp('(?:'+key+')\\s+(.+?)(?=\\s+(?:برای پروژه|در پروژه|پروژه|موضوع|بابت|مبلغ|تومان|تومن|شماره|تلفن|موبایل|آدرس|نشانی|مدت|تاریخ|بساز|ثبت کن|ایجاد کن|تنظیم کن|بنویس|با تخصص|به عنوان)(?:\\s|$)|$)'));return m?.[1]?.replace(/\s+(?:را|رو)$/,'').trim()||''}
function detect(text){const c=PeymanyarCommand.parse(text,db,todayFa());if(c.intent==='daily_create'||c.intent==='contract_create')return c.intent;if(/(?:انبار|کیسه|شاخه|بسته|سیمان|گچ|چسب).*(?:وارد|ورود|رسید|اومد|آمد|مصرف|خروج|انتقال)/.test(text))return 'inventory_create';return c.intent}
function plan(text,intent){const base=PeymanyarCommand.parse(text,db,todayFa()),p=mentioned(text,db.projects),person=mentioned(text,db.people);return{...base,intent,text,...(base.intent==='daily_create'&&/کارگر/.test(text)?{labourWorkers:base.workers}:{}),project:p?.name||base.project||'',party:person?.name||base.party||base.name||extract(text,'قرارداد با|پیمانکار(?: جدید)?(?: به نام)?|فروشنده(?: جدید)?(?: به نام)?|شخص(?: جدید)?(?: به نام)?|نفر(?: جدید)?(?: به نام)?')||'',role:base.role||inferPartyRole(text)||'',phone:(normalizeDigits(text).match(/09\d{9}/)||[])[0]||'',address:extract(text,'آدرس|نشانی'),scope:extract(text,'موضوع|بابت|در خصوص'),date:PeymanyarCommand.dateOf(text,todayFa())}}
function routeBar(kind){return `<div class="intent-route"><label for="irKind">نوع درخواست</label><select id="irKind" onchange="changeCommandIntent(this.value)">${Object.entries(labels).map(([k,l])=>`<option value="${k}" ${k===kind?'selected':''}>${l}</option>`).join('')}</select><small>تشخیص را می‌توانی تغییر بدهی؛ ثبت فقط پس از تأیید تو انجام می‌شود.</small></div>`}
function input(id,value,list=''){return `<input id="${id}" value="${esc(value||'')}" ${list?`list="${list}"`:''}>`}
function body(p){const opts=`<datalist id="irProjects">${db.projects.map(x=>`<option value="${esc(x.name)}">`).join('')}</datalist><datalist id="irPeople">${db.people.map(x=>`<option value="${esc(x.name)}">`).join('')}</datalist>`;
let fields=field('پروژه',input('irProject',p.project,'irProjects'));
if(p.intent==='daily_create')fields+=field('تاریخ شمسی',`<input id="irDate" value="${esc(p.date)}" data-persian-calendar="1">`)+field('تعداد کل نیرو',`<input id="irWorkers" inputmode="numeric" value="${p.workers||''}">`)+field('کارگر روزمزد (اختیاری)',`<input id="irLabour" inputmode="numeric" value="${p.labourWorkers??''}">`)+field('سهم روز کارگری',input('irDays',p.workDays??1))+field('وضعیت هوا',input('irWeather',p.weather));
else if(p.intent==='person_create')fields+=field('نام شخص / پیمانکار',input('irParty',p.party,'irPeople'))+field('تخصص / نوع کار',input('irRole',p.role))+field('موبایل',input('irPhone',p.phone))+field('نشانی',input('irAddress',p.address));
else if(p.intent==='contract_create')fields+=field('نام پیمانکار / طرف قرارداد',input('irParty',p.party,'irPeople'))+field('تخصص / نوع کار',input('irRole',p.role))+field('عنوان قرارداد',input('irTitle',p.title||'قرارداد '+(p.role||'پیمانکاری')))+field('تاریخ شمسی',`<input id="irDate" value="${esc(p.date)}" data-persian-calendar="1">`)+field('مبلغ توافق‌شده (اختیاری، تومان)',`<input id="irAmount" inputmode="numeric" value="${p.amount||''}">`)+field('موضوع کار',`<textarea id="irScope">${esc(p.scope||'')}</textarea>`)+field('نام واگذارنده',input('irIssuer',p.issuer||db.contractIssuer?.name))+field('نشانی پیمانکار',input('irAddress',p.address))+field('تلفن پیمانکار',input('irPhone',p.phone));
return `${opts}<div class="smart-plan-grid">${fields}</div>${field(p.intent==='daily_create'?'شرح گزارش؛ قابل ویرایش':'متن کامل درخواست',`<textarea id="irText" rows="6">${esc(p.text)}</textarea>`)}<p id="irStatus" role="status">${p.intent==='daily_create'?'این درخواست فقط گزارش روزانه است؛ مبلغ‌های داخل شرح تراکنش ایجاد نمی‌کنند.':'اطلاعات موجود را بررسی کن؛ باقی اطلاعات را می‌توانی بعداً تکمیل کنی.'}</p><div class="dialog-actions"><button class="btn primary" onclick="saveRoutedCommand(false)">${p.intent==='daily_create'?'تأیید و ثبت گزارش':p.intent==='person_create'?'تأیید و ثبت شخص':'ذخیره پیش‌نویس قرارداد'}</button><button class="btn" onclick="saveRoutedCommand(true)">فعلاً ناقص ذخیره کن</button></div>`}
function show(text,forced){if(!text.trim())return;const input=document.getElementById('quickText'),old=current;current={...plan(text,forced||detect(text)),draftId:old?.draftId||null,audioIds:old?.audioIds||[],blob:input?._voiceBlob||old?.blob||null};const p=current,box=document.getElementById('parsedResult');if(!box)return;
window.v21Plan=null;window.parsedCommand=null;
if(['daily_create','person_create','contract_create','unknown'].includes(p.intent)){box.innerHTML=`<section class="parsed">${routeBar(p.intent)}<h3>${labels[p.intent]}</h3>${body(p)}</section>`;return}
// Reuse the existing specialist flows, while making the interpretation editable.
if(p.intent==='inventory_create'){window.inventoryParsedPlan=PeymanyarInventory.parse(text);box.innerHTML=`<section class="parsed">${routeBar(p.intent)}<h3>پیش‌نویس انبار</h3><button class="btn primary" onclick="openInventoryEntry('',null,null,window.inventoryParsedPlan)">باز کردن فرم انبار</button></section>`}
else {if(forced&&detect(text)!==forced){const original=input.value;input.value=forced==='financial_query'?`گزارش مالی پروژه ${p.project} را نشان بده`:forced==='project_create'?`یک پروژه جدید به نام ${p.project||'نام پروژه'} بساز`:`پرداخت ${PeymanyarCommand.amountOf(text)||0} تومان برای پروژه ${p.project} به ${p.party} بابت ${p.role||'هزینه عمومی'}`;try{baseParse();if(window.v21Plan)window.v21Plan.note=text}finally{input.value=original}}else baseParse()}
if(!document.getElementById('irKind'))box.insertAdjacentHTML('afterbegin',routeBar(p.intent));box.insertAdjacentHTML('beforeend','<button class="btn" onclick="saveRoutedCommand(true)">فعلاً ناقص ذخیره کن</button>');
}
window.changeCommandIntent=function(kind){if(busy)return;const text=v('irText')||v('quickText');show(text,kind)};
const baseParse=parseQuick;parseQuick=function(...args){if(document.getElementById('bulkCashModal'))return baseParse(...args);if(document.querySelector('.voice-fullscreen'))return baseParse(...args);const text=v('quickText');if(!text)return baseParse(...args);if(current&&current.text!==text)current=null;show(text)};
function read(){const p={...current};for(const [k,id] of Object.entries({project:'spProject',party:'spParty',role:'spRole',name:'spProjectName',client:'spClient',date:'spDate'}))if(document.getElementById(id))p[k]=v(id);if(document.getElementById('spAmount'))p.amount=n('spAmount');for(const [k,id] of Object.entries({project:'irProject',party:'irParty',role:'irRole',phone:'irPhone',address:'irAddress',date:'irDate',title:'irTitle',scope:'irScope',issuer:'irIssuer',text:'irText'})){if(document.getElementById(id))p[k]=v(id)}if(document.getElementById('irWorkers')){p.workers=n('irWorkers');p.labourWorkers=v('irLabour')===''?null:n('irLabour');p.workDays=n('irDays');p.weather=v('irWeather')}if(document.getElementById('irAmount'))p.amount=n('irAmount');return p}
async function audio(p){if(p.blob&&!p.audioIds.length){const id=uid(),file=new File([p.blob],`فرمان-${id}.wav`,{type:p.blob.type||'audio/wav'});await storeFile(id,file);p.audioIds=[id];current.audioIds=p.audioIds}return p.audioIds}
function storedPlan(p){const {blob,...data}=p;return data}
window.saveRoutedCommand=async function(incomplete){if(busy||!current)return;busy=true;posting=true;const p=read(),status=document.getElementById('irStatus');let snapshot;
try{
 if(!p.text.trim())throw Error('شرح درخواست را وارد کن');
 if(!incomplete){if(!['daily_create','person_create','contract_create'].includes(p.intent))throw Error('نوع درخواست را انتخاب کن یا فعلاً ناقص ذخیره کن');if(p.intent==='person_create'&&!p.party)throw Error('نام شخص را وارد کن یا فعلاً ناقص ذخیره کن');if(p.intent!=='person_create'&&!match(p.project,db.projects))throw Error('پروژه را از فهرست انتخاب کن یا فعلاً ناقص ذخیره کن');if(p.intent==='daily_create'){if(!PeymanyarCalendar.parse(p.date))throw Error('تاریخ شمسی معتبر وارد کن');if(!Number.isInteger(p.workers)||p.workers<0||p.labourWorkers!==null&&(!Number.isInteger(p.labourWorkers)||p.labourWorkers<0||p.labourWorkers>p.workers)||!(p.workDays>0&&p.workDays<=1))throw Error('تعداد نیرو، کارگر و سهم روز را بررسی کن')}if(p.intent==='contract_create'&&(!p.party||!p.scope||!PeymanyarCalendar.parse(p.date)||!Number.isFinite(p.amount)||p.amount<0))throw Error('نام طرف قرارداد، موضوع و تاریخ را کامل کن یا فعلاً ناقص ذخیره کن');if(p.project&&!match(p.project,db.projects))throw Error('پروژه را از فهرست انتخاب کن')}
 await audio(p);snapshot=JSON.stringify(db);const project=match(p.project,db.projects);
 if(incomplete){db.commandDrafts=db.commandDrafts||[];const old=db.commandDrafts.find(x=>String(x.id)===String(p.draftId)),row={...storedPlan(p),id:old?.id||uid(),status:'در انتظار تکمیل',updatedAt:new Date().toISOString()};if(old)Object.assign(old,row);else db.commandDrafts.unshift(row)}
 else if(p.intent==='daily_create'){db.daily.unshift({id:uid(),projectId:project.id,project:project.name,date:normalizeDateValue(p.date),workers:p.workers,labourWorkers:p.labourWorkers,workDays:p.workDays,weather:p.weather,text:p.text,audioIds:p.audioIds,source:'universal-voice'})}
 else {let person=match(p.party,db.people);if(!person&&db.people.some(x=>norm(x.name)===norm(p.party)))throw Error('چند شخص با این نام وجود دارد؛ نام کامل را انتخاب کن');if(!person){person={id:uid(),name:p.party,role:p.role||'تخصص ثبت نشده',phone:p.phone||'',address:p.address||'',project:project?.name||'',...(project?{projectId:project.id}:{}),sourceText:p.text,audioIds:p.audioIds};db.people.push(person)}
 if(p.intent==='contract_create'){const template=PeymanyarContracts.templateFor(p.role||person.role);db.contracts.push({id:uid(),title:p.title||template.title,projectId:project.id,project:project.name,personId:person.id,contractorId:person.id,party:person.name,amount:p.amount||0,date:normalizeDateValue(p.date),status:'پیش‌نویس',templateKey:template.key,fields:{issuer:p.issuer||'',scope:p.scope,contractorAddress:p.address||person.address||'',contractorPhone:p.phone||person.phone||''},sourceText:p.text,audioIds:p.audioIds,completeness:p.issuer?'draft':'incomplete'})}}
 if(!incomplete&&p.draftId)db.commandDrafts=(db.commandDrafts||[]).filter(x=>String(x.id)!==String(p.draftId));save();current=null;closeUniversalQuick();document.getElementById('commandDraftInbox')?.remove();render();toast(incomplete?'در انتظار تکمیل ذخیره شد':p.intent==='daily_create'?'گزارش در پروژه ثبت شد':p.intent==='person_create'?'شخص ثبت شد؛ حساب تکراری ساخته نشد':'پیش‌نویس قرارداد در پروژه و پرونده شخص ذخیره شد');
}catch(e){if(snapshot){const before=JSON.parse(snapshot);for(const k of Object.keys(db))if(!(k in before))delete db[k];Object.assign(db,before)}if(status)status.textContent=e.message;else toast(e.message)}finally{busy=false;posting=false}};
window.openCommandDrafts=function(){document.getElementById('commandDraftInbox')?.remove();const rows=db.commandDrafts||[];document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="commandDraftInbox"><div class="dialog"><div class="dialog-head"><h2>درخواست‌های در انتظار تکمیل</h2><button class="close" onclick="document.getElementById('commandDraftInbox').remove()">×</button></div>${rows.map(r=>`<article class="phone-row"><strong>${esc(labels[r.intent]||'درخواست')} • ${esc(r.project||'پروژه مشخص نشده')}</strong><p>${esc(r.text)}</p><button class="btn" onclick="resumeCommandDraft(${esc(JSON.stringify(String(r.id)))})">تکمیل و ثبت</button></article>`).join('')||'<p>درخواست ناقصی باقی نمانده است.</p>'}</div></div>`)};
window.resumeCommandDraft=function(id){const r=(db.commandDrafts||[]).find(x=>String(x.id)===String(id));if(!r)return;document.getElementById('commandDraftInbox')?.remove();openQuick();current={...r,draftId:r.id};document.getElementById('quickText').value=r.text;show(r.text,r.intent);current={...current,...r,draftId:r.id};for(const [k,id] of Object.entries({project:'spProject',party:'spParty',role:'spRole',name:'spProjectName',client:'spClient',date:'spDate',amount:'spAmount'}))if(document.getElementById(id)&&r[k]!=null)document.getElementById(id).value=r[k];if(['daily_create','person_create','contract_create','unknown'].includes(r.intent))document.getElementById('parsedResult').innerHTML=`<section class="parsed">${routeBar(r.intent)}<h3>${labels[r.intent]}</h3>${body(current)}</section>`};
const openBase=openQuick;openQuick=function(...args){if(busy)return;current=null;return openBase(...args)};
function inboxLink(){const count=(db.commandDrafts||[]).length;return `<section class="card"><h3>درخواست‌های در انتظار تکمیل</h3><p>${fa(count)} درخواست؛ متن و صوت محفوظ است تا اطلاعات باقی‌مانده را تکمیل کنی.</p><button class="btn" onclick="openCommandDrafts()">تکمیل درخواست‌ها</button></section>`}
const dashBase=dashboard;dashboard=function(){return dashBase().replace('</main>',inboxLink()+'</main>')};const settingsBase=settings;settings=function(){return settingsBase().replace('</main>',inboxLink()+'</main>')};
let specialist=null;
const saveBase=save;save=function(...args){if(specialist){const list=db[specialist.collection]||[],fresh=list.filter(r=>!specialist.ids.has(String(r.id)));if(fresh.length){for(const row of fresh){if(specialist.p.audioIds?.length)row.audioIds=specialist.p.audioIds;row.sourceText=row.sourceText||specialist.p.text}if(specialist.p.draftId)db.commandDrafts=(db.commandDrafts||[]).filter(r=>String(r.id)!==String(specialist.p.draftId))}}return saveBase(...args)};
function specialistAction(base,args,kind){if(!current||current.intent!==kind)return base(...args);if(busy)return;const p=read(),collection=kind==='project_create'?'projects':kind==='inventory_create'?'inventoryMoves':'transactions';function run(){specialist={p,collection,ids:new Set((db[collection]||[]).map(r=>String(r.id)))};try{const result=base(...args);if(result?.then)return result.finally(()=>{specialist=null});specialist=null;return result}catch(e){specialist=null;throw e}}if(!p.blob||p.audioIds.length)return run();busy=true;return audio(p).then(run).catch(e=>toast(e.message)).finally(()=>{specialist=null;busy=false})}

const confirmBase=confirmSmartPlan;confirmSmartPlan=function(...args){return specialistAction(confirmBase,args,current?.intent==='project_create'?'project_create':'transaction_create')};
const inventorySaveBase=saveInventoryEntry;saveInventoryEntry=function(...args){return specialistAction(inventorySaveBase,args,'inventory_create')};
window.PeymanyarIntents={detect,plan};const css=document.createElement('style');css.textContent='.intent-route{display:flex;flex-direction:column;gap:8px;border:1px solid #d4dfd7;background:#f3f7f2;padding:12px;border-radius:14px;margin-bottom:14px}.intent-route small{line-height:1.8;color:#58675d}#irText{width:100%;min-height:130px}#irStatus{line-height:1.9}';document.head.append(css);render();
})();
