/* Portable local backup: records and document blobs; never exports API secrets. */
(function(){
 const collections=['projects','people','transactions','contracts','daily','documents'];
 async function files(){const rows=new Map(memoryFiles);const idb=await openFileDB();const stored=await new Promise((resolve,reject)=>{const r=idb.transaction(FILE_STORE,'readonly').objectStore(FILE_STORE).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});stored.forEach(r=>rows.set(r.id,r));return [...rows.values()]}
 function encode(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(r.error);r.readAsDataURL(blob)})}
 async function pack(){const data=JSON.parse(JSON.stringify(db)),rows=await files();const attachments=[];for(const r of rows)attachments.push({id:r.id,name:r.name||'',type:r.type||r.blob.type||'',data:await encode(r.blob)});const available=new Set(rows.map(r=>String(r.id)));const missing=(data.documents||[]).filter(r=>!available.has(String(r.id))).map(r=>r.name);return {format:'peymanyar-portable',version:1,createdAt:new Date().toISOString(),revision:document.querySelector('meta[name="app-revision"]')?.content,data,files:attachments,missingFiles:missing}}
 function validate(input){const portable=input.format==='peymanyar-portable';if(portable&&input.version!==1)throw Error('نسخهٔ فایل پشتیبان پشتیبانی نمی‌شود.');const data=portable?input.data:input;if(!data||!collections.every(k=>Array.isArray(data[k])))throw Error('این فایل پشتیبان معتبر پیمان‌یار نیست.');for(const k of ['inventoryItems','inventoryMoves'])if(data[k]!==undefined&&!Array.isArray(data[k]))throw Error('فهرست انبار در پشتیبان معتبر نیست.');const rows=portable?input.files:[];if(!Array.isArray(rows))throw Error('فهرست فایل‌ها معتبر نیست.');const ids=new Set();const decoded=rows.map(r=>{if(r.id===undefined||ids.has(String(r.id))||typeof r.data!=='string')throw Error('فایل‌های پشتیبان معتبر نیستند.');ids.add(String(r.id));const bytes=Uint8Array.from(atob(r.data),c=>c.charCodeAt(0));return {id:r.id,name:r.name||'',type:r.type||'',blob:new Blob([bytes],{type:r.type||''})}});return {data,decoded,portable,missing:input.missingFiles||[]}}
 async function restore(input,ask=true,guard=()=>{}){const parsed=validate(input);const count=collections.map(k=>`${k==='projects'?'پروژه':k==='people'?'نفر':k==='transactions'?'تراکنش':k==='documents'?'سند':k==='contracts'?'قرارداد':'گزارش'}: ${fa(parsed.data[k].length)}`).join('\n');if(ask&&!confirm(`بازگردانی پشتیبان:\n${count}\nفایل پیوست: ${fa(parsed.decoded.length)}\n${parsed.portable?'':'پشتیبان قدیمی است؛ فایل‌های پیوست را ندارد.\n'}اطلاعات فعلی این مرورگر جایگزین می‌شود. ادامه می‌دهی؟`))return false;
 const old=localStorage.getItem(STORAGE),oldDb=db;const idb=await openFileDB();const previous=await files();guard();await new Promise((resolve,reject)=>{const t=idb.transaction(FILE_STORE,'readwrite');for(const r of parsed.decoded)t.objectStore(FILE_STORE).put(r);t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||Error('ذخیرهٔ فایل‌ها انجام نشد.'))});
 try{guard();localStorage.setItem(STORAGE+':before-restore',old||JSON.stringify(oldDb));localStorage.setItem(STORAGE,JSON.stringify(parsed.data))}catch(error){await new Promise((resolve,reject)=>{const t=idb.transaction(FILE_STORE,'readwrite'),s=t.objectStore(FILE_STORE);for(const r of parsed.decoded)s.delete(r.id);for(const r of previous)s.put(r);t.oncomplete=resolve;t.onerror=()=>reject(t.error)});throw error}
 db=parsed.data;parsed.decoded.forEach(r=>memoryFiles.set(r.id,r));render();toast('اطلاعات و فایل‌ها بازگردانی شد');return true}
 window.PeymanyarBackup={pack,restore,validate};
 backup=async function(){try{toast('در حال آماده‌سازی پشتیبان کامل…');const p=await pack();if(p.missingFiles.length)alert('این فایل‌ها در حافظه پیدا نشدند و داخل پشتیبان نیستند:\n'+p.missingFiles.join('\n'));download('peymanyar-backup-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(p),'application/json');localStorage.setItem(STORAGE+':last-export',p.createdAt);toast('پشتیبان کامل آماده شد؛ فایل را در Files ذخیره کن.')}catch(e){alert('پشتیبان ساخته نشد؛ اطلاعات فعلی حفظ شده است. '+e.message)}};
 window.importPeymanyarBackup=async function(input){const file=input.files?.[0];if(!file)return;try{await restore(JSON.parse(await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsText(file)})))}catch(e){alert('بازگردانی انجام نشد: '+e.message)}finally{input.value=''}};
 const baseSettings=settings;settings=function(){const html=baseSettings();return html.replace('دانلود پشتیبان</button>','دانلود پشتیبان کامل</button><label class="btn" style="margin-top:12px;display:inline-block;cursor:pointer">بازگردانی پشتیبان<input type="file" accept=".json,application/json" hidden onchange="importPeymanyarBackup(this)"></label><p style="line-height:1.9">پشتیبان کامل شامل جدول‌ها و فایل رسیدهاست. آن را در Files یا iCloud Drive نگه دار؛ سپس در مرورگر جدید همین‌جا بازگردانی کن. اطلاعات فعلاً فقط در همین مرورگر ذخیره می‌شود؛ ذخیرهٔ مرکزی و ورود کاربران هنوز فعال نیست.</p>')};
 const baseDashboard=dashboard;dashboard=function(){return baseDashboard().replace('<main class="phone-content">','<main class="phone-content"><div class="card" style="margin-bottom:14px"><strong>حفظ اطلاعات و انتقال به گوشی</strong><p>اطلاعات فعلاً در همین مرورگر است. برای انتقال، پشتیبان کامل بگیر و در مرورگر جدید بازگردانی کن.</p><button class="btn" onclick="backup()">پشتیبان کامل</button> <button class="btn" onclick="go(\'settings\')">بازگردانی و تنظیمات</button></div>')};
 navigator.storage?.persist?.().catch(()=>{});
 render();
})();

