(function(){
 'use strict';
 const direct=t=>t.kind==='expense'&&t.fundingSource==='client-direct';
 const num=v=>PeymanyarStatements.number(v);
 const eq=(a,b)=>String(a)===String(b);
 function sum(rows){let received=0,paid=0,directPaid=0;for(const t of rows){const a=Number(t.amount)||0;if(t.kind==='income')received+=a;if(t.kind==='expense'){paid+=a;if(direct(t))directPaid+=a}}return {received,paid,directPaid,cashPaid:paid-directPaid,cashBalance:received-paid+directPaid,funded:received+directPaid,projectReceived:received+directPaid}}
 reportSummary=sum;
 totals=function(){const s=sum(db.transactions);return {income:s.projectReceived,cashIncome:s.received,expense:s.paid,directPaid:s.directPaid,cashExpense:s.cashPaid,cashBalance:s.cashBalance}};
 function projectSummary(id,to=''){const p=db.projects.find(p=>eq(p.id,id));if(!p)return null;const rows=db.transactions.filter(t=>t.project===p.name&&(!to||normalizeDateValue(t.date)&&normalizeDateValue(t.date)<=to));const s=sum(rows),base=rows.filter(t=>t.kind==='expense'&&t.managementFeeEligible!==false&&!t.isManagementFee).reduce((a,t)=>a+(Number(t.amount)||0),0),rate=p.managementFeePercent==null?null:Number(p.managementFeePercent);return {...s,base,rate,fee:rate==null?null:Math.round(base*rate/100)}}
 function modal(title,body){document.getElementById('projectFundingModal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="projectFundingModal"><div class="dialog" role="dialog" aria-modal="true"><div class="dialog-head"><h2>${esc(title)}</h2><button class="close" onclick="document.getElementById('projectFundingModal').remove()">×</button></div>${body}</div></div>`)}
 const opts=(rows,value,key='name')=>rows.map(p=>`<option value="${esc(p[key])}" ${eq(p[key],value)?'selected':''}>${esc(p.name)}</option>`).join('');
 window.openProjectFee=function(id){const p=db.projects.find(p=>eq(p.id,id));if(!p)return;modal('درصد مدیریت پیمان — '+p.name,`${field('درصد مدیریت پیمان',`<input id="pfRate" inputmode="decimal" value="${esc(p.managementFeePercent??'')}" placeholder="مثلاً ۱۵">`)}<p>مبنای محاسبه: هزینه‌های پروژه، شامل پرداخت مستقیم کارفرما. دریافتی‌ها، صورت‌وضعیت‌های پرداخت‌نشده و خودِ حق مدیریت دوباره در مبنا جمع نمی‌شوند. این محاسبه به‌تنهایی تراکنش مالی ایجاد نمی‌کند.</p><button class="btn primary" onclick="saveProjectFee(${Number(p.id)})">ذخیره درصد</button>`)};
 window.saveProjectFee=function(id){const p=db.projects.find(p=>eq(p.id,id)),r=num(document.getElementById('pfRate').value);if(!p||!Number.isFinite(r)||r<0||r>100)return toast('درصد معتبر از صفر تا صد وارد کن');const before=structuredClone(db);p.managementFeePercent=r;try{save()}catch(e){db=before;return toast('ذخیره نشد؛ اطلاعات قبلی حفظ شد')}document.getElementById('projectFundingModal').remove();render();toast('درصد این پروژه ذخیره شد')};
 window.openClientDirectPayment=function(project='',id=''){const t=db.transactions.find(t=>eq(t.id,id));if(t?.paymentMethod==='cheque')return toast('برای تغییر منبع چک، ابتدا وضعیت چک را بررسی کن؛ این فرم مخصوص پرداخت مستقیم قطعی است');project=t?.project||project;const p=db.projects.find(p=>p.name===project);modal(t?'اصلاح منبع و هزینهٔ ثبت قبلی':'پرداخت مستقیم کارفرما',`<p>در دفتر پروژه هم دریافت مستقیم و هم هزینه منظور می‌شود؛ پول به حساب مدیر پروژه وارد نشده است. طرف حساب، فروشنده یا پیمانکاری است که پول گرفته.</p><div class="form-grid">${field('پروژه',`<select id="pfProject"><option value="">انتخاب پروژه</option>${opts(db.projects,project)}</select>`)}${field('منبع پرداخت',`<select id="pfSource"><option value="client-direct" ${!t||direct(t)?'selected':''}>مستقیم از کارفرما</option><option value="manager" ${t&&!direct(t)?'selected':''}>از حساب مدیر پروژه</option></select>`)}${field('نام کارفرمای پرداخت‌کننده',`<input id="pfClient" value="${esc(t?.fundingClient||p?.client||'')}">`)}${field('فروشنده / پیمانکار دریافت‌کننده',`<input id="pfParty" list="pfPeople" value="${esc(t?.kind==='expense'?t.party||'':'')}"><datalist id="pfPeople">${db.people.map(p=>`<option value="${esc(p.name)}">`).join('')}</datalist>`)}${field('مبلغ تومان',`<input id="pfAmount" inputmode="numeric" oninput="formatStatementPrice(this)" value="${esc(t?fa(t.amount):'')}">`)}${field('تاریخ شمسی',`<input id="pfDate" data-persian-calendar="1" onclick="PeymanyarCalendar.open(this)" value="${esc(t?.date||normalizeDateValue(todayFa()))}">`)}${field('بابت',`<input id="pfCategory" value="${esc(t?.kind==='expense'?t.category||'خرید مصالح':'خرید مصالح')}">`)}${field('شرح',`<textarea id="pfNote">${esc(t?.note||'')}</textarea>`)}</div><label><input id="pfEligible" type="checkbox" ${t?.managementFeeEligible!==false?'checked':''}> جزو مبنای درصد مدیریت پیمان باشد</label><p>حق مدیریت پرداخت‌شده یا جابه‌جایی تنخواه را در مبنای درصد نگذار. اگر قبلاً همین هزینه را جدا ثبت کرده‌ای، این ثبت را دوباره تبدیل نکن؛ ابتدا دو ردیف را بررسی کن.</p>${t?.kind==='income'?'<p>این ردیف فعلاً «دریافت» است؛ با تأیید تو همان ردیف به هزینه تبدیل می‌شود، بدون ایجاد ردیف اضافه.</p>':''}<button class="btn primary" onclick="saveClientDirectPayment(${esc(JSON.stringify(id))})">${t?'ذخیره اصلاح':'ثبت پرداخت مستقیم'}</button>`)};
 window.saveClientDirectPayment=function(id=''){const value=id=>document.getElementById(id).value.trim(),old=db.transactions.find(t=>eq(t.id,id)),project=value('pfProject'),amount=num(value('pfAmount')),date=PeymanyarStatements.date(value('pfDate')),party=value('pfParty'),client=value('pfClient'),source=value('pfSource');if(!db.projects.some(p=>p.name===project)||!Number.isSafeInteger(amount)||amount<=0||!date||!party||!value('pfCategory')||source==='client-direct'&&!client)return toast('پروژه، مبلغ، تاریخ، طرف حساب، بابت و نام کارفرما را کامل کن');if(old&&!confirm('همان ردیف مالی اصلاح شود؟ قبل از تأیید مطمئن شو هزینهٔ تکراری ثبت نشده است.'))return;const before=structuredClone(db),person=knownPerson(party),record={...old,id:old?.id||uid(),kind:'expense',project,amount,date,party,personId:person?.id||null,contractorId:person?.id||null,category:value('pfCategory'),note:value('pfNote'),fundingSource:source,fundingClient:source==='client-direct'?client:'',managementFeeEligible:document.getElementById('pfEligible').checked};if(old)Object.assign(old,record);else db.transactions.push(record);const doc=old?.documentId&&db.documents.find(d=>eq(d.id,old.documentId));if(doc)Object.assign(doc,{project,amount,date,party,category:record.category,note:record.note,fundingSource:source,fundingClient:record.fundingClient});try{save()}catch(e){db=before;return toast('ذخیره نشد؛ اطلاعات قبلی حفظ شد')}document.getElementById('projectFundingModal').remove();render();toast('هزینه و منبع پرداخت ذخیره شد؛ دریافت و هزینهٔ پروژه هم‌زمان ثبت شد؛ خارج از حساب مدیر')};
 function panel(project){const p=db.projects.find(p=>p.name===project),s=p?projectSummary(p.id):sum(db.transactions);return `<section class="card project-funding-panel" style="margin-bottom:16px"><h3>${p?'هزینه و حق مدیریت پیمان':'تفکیک گردش مدیر و پرداخت کارفرما'}</h3><div class="ledger-summary"><div><small>دریافت واقعی مدیر</small><strong>${money(s.received)}</strong></div><div><small>پرداخت از حساب مدیر</small><strong>${money(s.cashPaid)}</strong></div><div><small>پرداخت مستقیم کارفرما</small><strong>${money(s.directPaid)}</strong></div><div><small>کل هزینهٔ پروژه${p?'':'‌ها'}</small><strong>${money(s.paid)}</strong></div><div><small>تراز گردش مدیر</small><strong>${money(s.cashBalance)}</strong></div><div><small>کل دریافتی پروژه (حساب مدیر + مستقیم)</small><strong>${money(s.funded)}</strong></div></div>${p?`<p>مبنای حق مدیریت: ${money(s.base)} • درصد: ${s.rate==null?'تعیین نشده':fa(s.rate)+'٪'} • حق مدیریت محاسبه‌شده: ${s.fee==null?'—':money(s.fee)}</p><button class="btn" onclick="openProjectFee(${Number(p.id)})">تعیین / ویرایش درصد مدیریت</button>`:''}<button class="btn primary" onclick="openClientDirectPayment(${esc(JSON.stringify(project||''))})">＋ پرداخت مستقیم کارفرما</button><p>تراز، گردش ثبت‌شده است نه موجودی بانک. حق مدیریت محاسبه‌شده در هزینه‌ها دوباره ثبت نمی‌شود.</p></section>`}
 function insertPanel(html,project){const holder=document.createElement('div');holder.innerHTML=html;holder.querySelector('main')?.insertAdjacentHTML('afterbegin',panel(project));return holder.innerHTML}
 const baseProject=projectDetail;projectDetail=function(){const html=baseProject(),p=db.projects.find(p=>eq(p.id,selectedProjectId));return p?insertPanel(html,p.name):html};
 const baseFinance=finance;finance=function(){return insertPanel(baseFinance(),'')};
 const baseTable=transactionReportTable;transactionReportTable=function(rows){const html=baseTable(rows),holder=document.createElement('div');holder.innerHTML=html;holder.querySelectorAll('tbody tr').forEach((tr,i)=>{const t=rows[i];if(!t)return;const menu=tr.querySelector('.ledger-row-menu div');if(menu&&t.paymentMethod!=='cheque')menu.insertAdjacentHTML('beforeend',`<button onclick="openClientDirectPayment('',${Number(t.id)})">منبع پرداخت / مبنای درصد</button>`);if(direct(t)){const cell=tr.cells[4];if(cell)cell.insertAdjacentHTML('beforeend',`<small style="display:block">پرداخت مستقیم ${esc(t.fundingClient||'کارفرما')}؛ خارج از حساب مدیر</small>`)}});return holder.innerHTML};
 const baseEditor=openRecordEditor;openRecordEditor=function(kind,id){const t=kind==='transaction'?db.transactions.find(t=>eq(t.id,id)):db.transactions.find(t=>eq(t.documentId,id));if(t&&direct(t))return openClientDirectPayment('',t.id);return baseEditor(kind,id)};
 window.PeymanyarFunding={sum,projectSummary,isDirect:direct};
 render();
})();

