/* A project starts with a compact overview; detail pages remain scoped to its ID. */
(function(){
'use strict';
let section='overview';
const eq=(a,b)=>a!=null&&b!=null&&String(a)===String(b),key=s=>PeymanyarCommand.clean(s).replace(/آ/g,'ا');
const names=p=>[p.name,...(p.aliases||[])].filter(Boolean);
function belongs(r,p){if(r.projectId!=null&&db.projects.some(x=>eq(x.id,r.projectId)))return eq(r.projectId,p.id);return names(p).some(n=>key(n)===key(r.project||r.projectName))}
function data(p){const tx=db.transactions.filter(r=>belongs(r,p)),contracts=db.contracts.filter(r=>belongs(r,p)),statements=(db.workStatements||[]).filter(r=>belongs(r,p)),daily=db.daily.filter(r=>belongs(r,p)),docs=db.documents.filter(r=>belongs(r,p));const people=db.people.filter(person=>eq(person.projectId,p.id)||(person.projectIds||[]).some(id=>eq(id,p.id))||[person.project,...(person.projects||[])].some(n=>names(p).some(a=>key(a)===key(n)))||[...tx,...contracts,...statements].some(r=>eq(r.personId??r.contractorId,person.id)||r.personId==null&&r.contractorId==null&&knownPerson(r.party)?.id===person.id));const contractor=person=>contracts.some(r=>transactionPersonMatch(r,person))||statements.some(r=>eq(r.personId,person.id))||/پیمانکار|جوشکار|بنایی|بنا|کابینت|برقکار|لوله کش|کاشی|گچ کار|نقاش|نجار|تاسیسات|تأسیسات/.test(key(person.role));return {tx,contracts,statements,daily,docs,people:people.filter(x=>!contractor(x)),contractors:people.filter(contractor),photos:docs.filter(d=>/^image\//.test(d.type||'')||d.docType==='تصویر پروژه')}}
const titles={finance:'مالی پروژه',people:'افراد و طرف حساب‌ها',contractors:'پیمانکاران پروژه',inventory:'انبار و تجهیزات پروژه',statements:'صورت‌وضعیت‌ها',photos:'عکس‌های پروژه',daily:'گزارش‌های پروژه',contracts:'قراردادهای پروژه',settings:'مشخصات و مدیریت پروژه'};
const icons={finance:'↗',people:'♙',contractors:'♧',inventory:'▦',statements:'▤',photos:'▧',daily:'☷',contracts:'✎',settings:'⚙'};
const arg=v=>esc(JSON.stringify(v));
function summary(p,rows){const s=PeymanyarFunding.sum(rows);return `<section class="project-hub-summary"><div class="project-hub-summary-head"><h3>خلاصهٔ مالی پروژه</h3><span>تومان</span></div><table aria-label="خلاصه مالی پروژه ${esc(p.name)}"><thead><tr><th scope="col">ورودی پروژه</th><th scope="col">هزینهٔ پروژه</th><th scope="col">تراز گردش مدیر</th></tr></thead><tbody><tr><td>${fa(s.funded)}</td><td>${fa(s.paid)}</td><td class="${s.cashBalance<0?'hub-negative':''}">${fa(s.cashBalance)}</td></tr></tbody></table>${s.directPaid?`<p>ورودی شامل ${money(s.directPaid)} پرداخت مستقیم کارفرماست؛ این مبلغ وارد حساب مدیر نشده است.</p>`:''}</section>`}
function tile(p,k,count,description){return `<button class="project-hub-tile" data-project-section="${k}" onclick="openProjectSection(${arg(p.id)},'${k}')"><span class="project-hub-icon" aria-hidden="true">${icons[k]}</span><span><strong>${titles[k]}</strong><small>${esc(description)}</small></span><span class="project-hub-count">${count==null?'←':fa(count)}</span></button>`}
function overview(p,d){const stock=PeymanyarInventory.stock(p.id).filter(x=>x.quantity>0);return summary(p,d.tx)+`<nav class="project-hub-grid" aria-label="بخش‌های پروژه ${esc(p.name)}">${tile(p,'finance',d.tx.length,'ثبت، ریزحساب و خروجی گزارش')}${tile(p,'people',d.people.length,'نیروها، فروشندگان و طرف حساب‌ها')}${tile(p,'contractors',d.contractors.length,'حساب و ماندهٔ هر پیمانکار')}${tile(p,'inventory',stock.length,'موجودی، ورود، مصرف و انتقال')}${tile(p,'statements',d.statements.length,'ثبت و رسیدگی به صورت‌وضعیت')}${tile(p,'photos',d.photos.length,'تصاویر و پیوست‌های پروژه')}${tile(p,'daily',d.daily.length,'گزارش‌های روزانه و صوتی')}${tile(p,'contracts',d.contracts.length,'قراردادها و مدارک')}${tile(p,'settings',null,'مشخصات، ادغام و بررسی موارد مشکوک')}</nav>`}
const legacy=projectDetail;
function finance(p,d){const holder=document.createElement('div');holder.innerHTML=PeymanyarLedger.projectPanel(d.tx,p);const panel=holder.querySelector('.ledger-panel');if(panel){panel.querySelector('.ledger-summary')?.remove();panel.querySelector('.ledger-heading h2')?.remove()}return `<div class="project-section-actions"><button class="btn primary" onclick="openQuick()">＋ ثبت مالی</button><button class="btn" onclick="openBulkCash(${arg(p.name)})">ثبت گروهی</button><button class="btn" onclick="openClientDirectPayment(${arg(p.name)})">پرداخت مستقیم کارفرما</button><button class="btn" onclick="openProjectFee(${arg(p.id)})">درصد مدیریت پیمان</button></div>${summary(p,d.tx)}${panel?.outerHTML||transactionReportTable(d.tx)}`}
function persons(p,rows,contractors){return `<div class="project-section-actions"><button class="btn primary" onclick="openProjectEntry('person',${arg(p.id)})">＋ ${contractors?'پیمانکار':'فرد'} جدید</button></div><div class="project-section-list">${rows.map(person=>`<article class="project-person-row"><button onclick="openLedgerPerson(${Number(person.id)},${arg(p.name)})"><span class="project-person-avatar">${esc(person.name?.slice(0,1)||'♙')}</span><span><strong>${esc(person.name)}</strong><small>${esc(person.role||'تخصص ثبت نشده')}</small></span><span>←</span></button>${contractors?`<button class="btn" onclick="openContractorAccount(${arg(person.id)},${arg(p.name)})">مانده و صورت‌حساب</button>`:''}</article>`).join('')||empty('هنوز موردی در این پروژه ثبت نشده است.')}</div>`}
function statements(p,rows){return `<div class="project-section-actions"><button class="btn primary" onclick="openWorkStatement('',${arg(p.name)})">＋ صورت‌وضعیت جدید</button><button class="btn" onclick="openContractorOverview(${arg(p.name)})">گزارش مانده / چاپ</button><button class="btn" onclick="showWorkStatements('',${arg(p.name)})">فیلتر و گزارش کامل</button></div><div class="project-section-list">${rows.map(s=>`<article class="phone-row"><div class="phone-row-head"><strong>${esc(s.title)}</strong><span class="pill">${s.status==='approved'?'تأییدشده':'پیش‌نویس'}</span></div><p>${esc(s.party)} • ${esc(s.date)}</p><strong>${money(PeymanyarStatements.total(s))}</strong><div class="project-section-actions"><button class="btn" onclick="openWorkStatement('', '',${arg(s.id)})">دیدن / ویرایش</button><button class="btn" onclick="printWorkStatement(${arg(s.id)})">چاپ</button><button class="btn danger" onclick="deleteWorkStatement(${arg(s.id)})">حذف</button></div></article>`).join('')||empty()}</div>`}
function documents(p,rows,photos){return `<div class="project-section-actions"><button class="btn primary" onclick="openSmartUpload(${arg(p.name)})">＋ ${photos?'عکس':'سند'} پروژه</button></div><div class="${photos?'project-photo-grid':'project-section-list'}">${rows.map(r=>photos?`<article class="project-photo-card"><button class="project-photo-open" onclick="viewDocument(${Number(r.id)})"><span aria-hidden="true">▧</span><strong>${esc(r.title||r.name)}</strong><small>${esc(r.date||'')}</small><span class="btn">نمایش و زوم</span></button><button class="btn" onclick="openRecordEditor('document',${Number(r.id)})">ویرایش مشخصات</button></article>`:documentInfoCard(r)).join('')||empty()}</div>`}
function daily(p,rows){return `<div class="project-section-actions"><button class="btn primary" onclick="openLongDailyReport(${arg(p.name)})">＋ گزارش روزانه / صوتی</button></div><div class="project-section-list">${[...rows].sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(r=>`<article class="phone-row"><div class="phone-row-head"><strong>${esc(r.date)}</strong><span>${fa(r.workers)} نفر</span></div><p class="project-report-text">${esc(r.text||r.note||'')}</p><div class="project-section-actions"><button class="btn" onclick="openLongDailyDetail(${Number(r.id)})">گزارش کامل و صوت</button><button class="btn danger" onclick="removeEntity('daily',${Number(r.id)})">حذف گزارش</button></div></article>`).join('')||empty()}</div>`}
function settings(p,d){const flagged=['transactions','documents','contracts','daily'].reduce((n,k)=>n+(db[k]||[]).filter(r=>r.mergeReview&&belongs(r,p)).length,0);return `<table class="project-info-table"><tbody>${[['کارفرما',p.client],['موقعیت',p.location],['تاریخ شروع',p.start],['وضعیت',p.status],['پیشرفت',fa(p.progress)+'٪']].map(([label,value])=>`<tr><th>${label}</th><td>${esc(value||'ثبت نشده')}</td></tr>`).join('')}</tbody></table><div class="project-section-actions"><button class="btn" onclick="openProjectCompletionEditor(${arg(p.id)})">ویرایش مشخصات</button><button class="btn" onclick="openEntityNameEditor('project',${arg(p.id)})">ویرایش نام</button><button class="btn" onclick="openProjectMerge(${arg(p.id)})">ادغام پروژه‌ها</button>${flagged?`<button class="btn merge-review" onclick="openMergeReview(${arg(p.id)})">بررسی ${fa(flagged)} مورد مشکوک</button>`:''}</div>`}
window.openProjectEntry=function(kind,id){openForm(kind);const p=db.projects.find(p=>eq(p.id,id)),input=document.getElementById('fProject');if(p&&input){input.value=p.name;input.dispatchEvent(new Event('change',{bubbles:true}))}};
const baseOpen=openProject;openProject=function(...args){section='overview';return baseOpen(...args)};
window.openProjectSection=function(id,next='overview'){const p=db.projects.find(p=>eq(p.id,id));if(!p)return;if(next==='inventory')return openInventory(p.id);if(next!=='overview'&&!titles[next])return;selectedProjectId=Number(p.id);page='projectDetail';section=next;render();window.scrollTo(0,0)};
projectDetail=function(){const p=db.projects.find(p=>eq(p.id,selectedProjectId));if(!p)return projects();const d=data(p);let body;if(section==='overview')body=overview(p,d);else if(section==='finance')body=finance(p,d);else if(section==='people'||section==='contractors')body=persons(p,d[section],section==='contractors');else if(section==='statements')body=statements(p,d.statements);else if(section==='photos')body=documents(p,d.photos,true);else if(section==='contracts')body=`<div class="project-section-actions"><button class="btn primary" onclick="openProjectEntry('contract',${arg(p.id)})">＋ قرارداد جدید</button><button class="btn" onclick="openManagementContract(${arg(p.id)})">قرارداد مدیریت پیمان</button></div><div class="project-section-list">${d.contracts.map(c=>`<article class="phone-row"><strong>${esc(c.title)}</strong><p>${esc(c.party)} • ${esc(c.date)}</p><strong>${money(c.amount)}</strong>${c.templateKey==='management'?`<button class="btn" onclick="openManagementContract(${arg(p.id)},${arg(c.id)})">دیدن / ویرایش</button>`:''}</article>`).join('')||empty()}</div><h3>اسناد و پیوست‌ها</h3>${documents(p,d.docs,false)}`;else if(section==='daily')body=daily(p,d.daily);else body=settings(p,d);return layout(`<div class="project-hub" data-project-id="${esc(String(p.id))}" data-project-view="${section}"><button class="back-btn" onclick="${section==='overview'?"go('projects')":`openProjectSection(${arg(p.id)})`}">← ${section==='overview'?'همهٔ پروژه‌ها':'صفحهٔ پروژه'}</button><header class="project-hub-header"><small>پروژه</small><h1>${esc(p.name)}</h1>${section==='overview'?`<p>${esc(p.client||'کارفرما ثبت نشده')}${p.location?' • '+esc(p.location):''}</p>`:`<h2>${titles[section]}</h2>`}</header>${body}</div>`,section==='overview'?'پروژه':titles[section])};
window.PeymanyarProjectHub={data,belongs};render();
})();
