(function(){
 'use strict';
 const backupKey=STORAGE+':project-merge-backup';
 const norm=value=>personIdentityKey(String(value||''));
 const names=p=>[p.name,...(p.aliases||[])].filter(Boolean);
 const same=(a,b)=>norm(a)&&norm(a)===norm(b);
 const labels={transactions:'ثبت مالی',documents:'سند',contracts:'قرارداد',daily:'گزارش روزانه'};
 function projectMatches(row,p){return String(row.projectId??'')===String(p.id)||names(p).some(n=>same(row.project||row.projectName,n))}
 function signature(key,r){const date=normalizeDateValue(r.date),party=knownPerson(r.party);const identity=party?String(party.id):r.personId!=null?String(r.personId):norm(r.party);if(key==='transactions')return date&&Number(r.amount)>0?[date,Number(r.amount),identity,r.kind].join('|'):'';if(key==='documents'){if(r.tracking)return 'tracking:'+normalizeDigits(String(r.tracking));return r.name&&r.size?[norm(r.name),r.size,r.type||''].join('|'):''}if(key==='contracts')return r.title&&Number(r.amount)>0?[norm(r.title),identity,Number(r.amount)].join('|'):'';return date&&(r.text||r.note||r.description)?[date,norm(r.text||r.note||r.description)].join('|'):''}
 function refreshFlags(data){let changed=false;for(const key of Object.keys(labels)){const groups=new Map();for(const r of data[key]||[]){if(!r.mergeReview)continue;const project=data.projects.find(p=>projectMatches(r,p)),sig=signature(key,r),group=(project?String(project.id):norm(r.project||r.projectName))+'|'+sig;if(!groups.has(group))groups.set(group,[]);groups.get(group).push(r)}for(const group of groups.values())if(group.length<2||!signature(key,group[0]))for(const r of group){r.mergeReview=false;delete r.mergeReviewReason;changed=true}}return changed}
 function reconcile(){const draft=JSON.parse(JSON.stringify(db));if(!refreshFlags(draft))return;try{localStorage.setItem(STORAGE,JSON.stringify(draft));db=draft}catch{toast('به‌روزرسانی موارد تکراری ذخیره نشد')}}
 window.openProjectMerge=function(targetId=''){if(db.projects.length<2)return toast('برای ادغام باید دو پروژه داشته باشی');document.getElementById('projectMerge')?.remove();const opts=id=>db.projects.map(p=>`<option value="${esc(String(p.id))}" ${String(p.id)===String(id)?'selected':''}>${esc(p.name)}</option>`).join('');const target=db.projects.find(p=>String(p.id)===String(targetId))||db.projects[0],source=db.projects.find(p=>String(p.id)!==String(target.id));document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="projectMerge"><div class="dialog" role="dialog" aria-modal="true" aria-label="ادغام پروژه‌ها"><div class="dialog-head"><h2>ادغام پروژه‌ها</h2><button class="close" onclick="document.getElementById('projectMerge').remove()">×</button></div>${field('پروژهٔ نهایی — این نام باقی می‌ماند',`<select id="mergeTarget">${opts(target.id)}</select>`)}${field('پروژه‌ای که به آن منتقل شود',`<select id="mergeSource">${opts(source.id)}</select>`)}<p>همهٔ سوابق و مدارک حفظ می‌شوند. موارد مشکوک به تکرار قرمز می‌شوند؛ بررسی‌شان را بعداً انجام بده.</p><button class="btn primary full-action" onclick="confirmProjectMerge()">ادغام و حفظ همهٔ سوابق</button></div></div>`)};
 window.confirmProjectMerge=function(){const target=db.projects.find(p=>String(p.id)===v('mergeTarget')),source=db.projects.find(p=>String(p.id)===v('mergeSource'));if(!target||!source||target===source)return toast('دو پروژهٔ متفاوت انتخاب کن');if(!confirm(`«${source.name}» به «${target.name}» منتقل شود؟\nهیچ پرداخت یا سندی حذف نمی‌شود.`))return;const before=JSON.stringify(db),draft=JSON.parse(before),t=draft.projects.find(p=>String(p.id)===String(target.id)),s=draft.projects.find(p=>String(p.id)===String(source.id));let count=0;for(const key of Object.keys(labels)){const groups=new Map();for(const row of draft[key]||[]){if(!projectMatches(row,s)&&!projectMatches(row,t))continue;const sig=signature(key,row);if(sig){if(!groups.has(sig))groups.set(sig,[]);groups.get(sig).push(row)}}for(const group of groups.values())if(group.length>1){for(const r of group){r.mergeReview=true;r.mergeReviewReason='مشکوک به تکرار پس از ادغام';count++}}}
 function move(obj){if(!obj||typeof obj!=='object')return;for(const [key,value]of Object.entries(obj)){if(['project','projectName'].includes(key)&&names(s).some(n=>same(value,n)))obj[key]=t.name;else if(key==='projectId'&&String(value)===String(s.id))obj[key]=typeof value==='number'?t.id:String(t.id);else if(key==='projects'&&Array.isArray(value))obj[key]=[...new Set(value.map(n=>names(s).some(old=>same(n,old))?t.name:n))];else if(key==='projectIds'&&Array.isArray(value))obj[key]=[...new Set(value.map(id=>String(id)===String(s.id)?String(t.id):id))];else if(value&&typeof value==='object')move(value)}}
 move(draft);for(const task of draft.completionTasks||[])if(task.entityType==='project'&&String(task.entityId)===String(s.id))task.entityId=t.id;t.aliases=[...new Set([...names(t),...names(s)])].filter(n=>n!==t.name);for(const key of ['client','location','start'])if(!t[key]||t[key]==='ثبت نشده')t[key]=s[key]||t[key];draft.projects=draft.projects.filter(p=>String(p.id)!==String(s.id));const after=JSON.stringify(draft);try{localStorage.setItem(backupKey,JSON.stringify({before,after}));localStorage.setItem(STORAGE,after)}catch{return toast('فضای ذخیره کافی نیست؛ ادغام انجام نشد')}db=draft;document.getElementById('projectMerge')?.remove();openProject(t.id);toast(`ادغام انجام شد؛ ${fa(count)} مورد مشکوک برای بررسی قرمز شد`)};
 window.undoProjectMerge=function(){let backup;try{backup=JSON.parse(localStorage.getItem(backupKey))}catch{}if(!backup)return toast('نسخهٔ قبل از ادغام موجود نیست');if(JSON.stringify(db)!==backup.after)return toast('بعد از ادغام تغییراتی ثبت شده؛ برگشت مستقیم ممکن نیست');if(!confirm('آخرین ادغام برگردد؟'))return;try{localStorage.setItem(STORAGE,backup.before)}catch{return toast('برگشت ذخیره نشد')}db=JSON.parse(backup.before);localStorage.removeItem(backupKey);go('projects');toast('آخرین ادغام برگشت')};
 const baseProjects=projects;projects=function(){return baseProjects().replace('<div class="toolbar">',`<div class="toolbar"><button class="btn" onclick="openProjectMerge()">ادغام پروژه‌ها</button>${localStorage.getItem(backupKey)?'<button class="btn" onclick="undoProjectMerge()">برگشت آخرین ادغام</button>':''}`)};
 const baseDetail=projectDetail;projectDetail=function(){reconcile();const p=db.projects.find(p=>String(p.id)===String(selectedProjectId));let html=baseDetail();if(!p)return html;const count=Object.keys(labels).reduce((n,k)=>n+(db[k]||[]).filter(r=>r.mergeReview&&projectMatches(r,p)).length,0);return html.replace('<div class="ledger-context">',`<div class="ledger-context"><button class="btn" onclick="openProjectMerge(${Number(p.id)})">ادغام با پروژهٔ دیگر</button>${count?`<button class="btn merge-review" onclick="openMergeReview(${Number(p.id)})">${fa(count)} مورد مشکوک به تکرار — بررسی بعداً</button>`:''}`)};
 const baseTable=transactionReportTable;transactionReportTable=function(rows){const holder=document.createElement('div');holder.innerHTML=baseTable(rows);holder.querySelectorAll('tbody tr').forEach((tr,i)=>{if(rows[i]?.mergeReview){tr.classList.add('merge-review');tr.setAttribute('title','مشکوک به تکرار؛ مبلغ هنوز در جمع حساب منظور می‌شود');const cell=tr.querySelector('td');cell?.insertAdjacentHTML('beforeend','<small>مشکوک به تکرار</small>')}});return holder.innerHTML};
 const baseDoc=documentInfoCard;documentInfoCard=function(doc){let html=baseDoc(doc);return doc.mergeReview?html.replace('<article','<article style="border:2px solid #b42318;background:#fff0ee"').replace('</article>','<p class="merge-review">مشکوک به تکرار پس از ادغام</p></article>'):html};
 window.openMergeReview=function(id){reconcile();const p=db.projects.find(p=>String(p.id)===String(id));if(!p)return;document.getElementById('mergeReview')?.remove();if(!Object.keys(labels).some(key=>(db[key]||[]).some(r=>r.mergeReview&&projectMatches(r,p))))return;document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="mergeReview"><div class="dialog" role="dialog" aria-modal="true" aria-label="موارد مشکوک به تکرار"><div class="dialog-head"><h2>بررسی موارد قرمز</h2><button class="close" onclick="document.getElementById('mergeReview').remove()">×</button></div><p>هیچ موردی حذف نشده و مبلغ‌ها هنوز در جمع حساب هستند. بعد از بررسی، اگر تکراری نبود علامت را بردار.</p>${Object.entries(labels).map(([key,label])=>(db[key]||[]).filter(r=>r.mergeReview&&projectMatches(r,p)).map(r=>`<article class="merge-review merge-review-item"><strong>${label}: ${esc(r.party||r.title||r.name||'')}</strong><p>${esc(r.date||'')} • ${r.amount?money(r.amount):''} ${esc(r.note||r.description||'')}</p>${key==='transactions'||key==='documents'?`<button class="btn" onclick="openRecordEditor('${key==='transactions'?'transaction':'document'}',${Number(r.id)})">ویرایش</button>`:''}<button class="btn danger" onclick="deleteMergeReview('${key}',${esc(JSON.stringify(String(r.id)))},${Number(id)})">حذف این مورد</button><button class="btn" onclick="clearMergeReview('${key}',${esc(JSON.stringify(String(r.id)))},${Number(id)})">بررسی شد؛ تکراری نیست</button></article>`).join('')).join('')}</div></div>`)};
 window.deleteMergeReview=async function(key,id,projectId){if(!labels[key])return;const p=db.projects.find(p=>String(p.id)===String(projectId)),record=(db[key]||[]).find(r=>String(r.id)===String(id));if(!p||!record?.mergeReview||!projectMatches(record,p))return;const detail=[record.party||record.title||record.name,record.date,record.amount?money(record.amount):''].filter(Boolean).join(' — '),linked=key==='documents'?' ثبت مالی و قراردادهای متصل باقی می‌مانند و پیوستشان جدا می‌شود.':key==='transactions'?' سند پیوست، اگر وجود داشته باشد، در بایگانی باقی می‌ماند.':key==='contracts'?' فایل‌های قرارداد در بایگانی باقی می‌مانند.':'';if(!confirm(`${labels[key]} «${detail}» از کل سوابق برنامه حذف شود؟\nفقط همین مورد حذف می‌شود؛ نسخهٔ دیگر باقی می‌ماند.${linked}`))return;const draft=JSON.parse(JSON.stringify(db));draft[key]=draft[key].filter(r=>String(r.id)!==String(id));const singular={transactions:'transaction',documents:'document',contracts:'contract',daily:'daily'}[key],ref=singular+'Id';for(const collection of Object.values(draft).filter(Array.isArray))for(const row of collection)if(String(row[ref]??'')===String(id))row[ref]=null;draft.completionTasks=(draft.completionTasks||[]).filter(t=>!(String(t.entityId)===String(id)&&(t.entityType===singular||String(t.type||'').startsWith(singular+'.'))));refreshFlags(draft);try{localStorage.setItem(STORAGE,JSON.stringify(draft))}catch{return toast('حذف ذخیره نشد؛ دوباره تلاش کن')}db=draft;if(key==='documents')try{await deleteStoredFile(record.id)}catch{}render();openMergeReview(projectId);toast('مورد انتخاب‌شده از سوابق حذف شد')};
 window.clearMergeReview=function(key,id,projectId){if(!labels[key])return;const r=(db[key]||[]).find(r=>String(r.id)===String(id));if(!r)return;r.mergeReview=false;delete r.mergeReviewReason;refreshFlags(db);save();render();openMergeReview(projectId)};
 const editBase=saveRecordEditor;saveRecordEditor=function(...args){const result=editBase(...args);reconcile();render();const review=document.getElementById('mergeReview');if(review)openMergeReview(selectedProjectId);return result};
 const removeTxBase=removeTransaction;removeTransaction=function(...args){const result=removeTxBase(...args);reconcile();render();return result};
 const removeDocBase=removeDocument;removeDocument=function(...args){const result=removeDocBase(...args);reconcile();render();return result};
 reconcile();render();
})();
