(function(){
 'use strict';
 let changed=new Set(),saving=false;
 const digits=s=>String(s||'').replace(/[۰-۹٠-٩]/g,c=>String(c.charCodeAt(0)-(c.charCodeAt(0)>=0x6f0?0x6f0:0x660)));
 function date(value){let s=digits(value).trim().replace(/[\\٫]/g,'/');if(/^\d{1,2}[/-]\d{1,2}$/.test(s))s=digits(todayFa()).match(/1[34]\d{2}/)[0]+'/'+s;return PeymanyarReceiptDate.date(s)}
 function amount(value){const s=digits(value).replace(/[٬,\s]/g,'');return s&&/^\d+(?:\.\d+)?$/.test(s)?Number(s):0}
 function linked(kind,id){const doc=kind==='document'?db.documents.find(x=>String(x.id)===String(id)):db.documents.find(x=>String(x.id)===String(db.transactions.find(t=>String(t.id)===String(id))?.documentId));const tx=kind==='transaction'?db.transactions.find(x=>String(x.id)===String(id)):db.transactions.find(x=>String(x.documentId)===String(id));return {doc,tx}}
 function entities(project,party,eventDate){let p=db.projects.find(x=>[x.name,...(x.aliases||[])].some(n=>normalizedProjectName(n)===normalizedProjectName(project)));project=p?.name||project;if(project&&project!=='بدون پروژه'&&!p){p={id:uid(),name:project,client:'ثبت نشده',location:'',budget:0,progress:0,status:'فعال',start:eventDate,completeness:'draft'};db.projects.push(p)}let person=party?knownPerson(party):null;if(party&&!person){person={id:uid(),name:party,role:'طرف حساب',project:project||'',projects:project?[project]:[]};db.people.push(person)}if(person&&project&&project!=='بدون پروژه')person.projects=[...new Set([...(person.projects||[]),person.project,project].filter(Boolean))];return {project:project||'بدون پروژه',projectId:p?.id??null,party:person?.name||party,personId:person?.id??null,contractorId:person?.id??null}}
 const openBase=openSmartUpload;openSmartUpload=function(...args){changed=new Set();return openBase(...args)};
 document.addEventListener('input',e=>{if(e.target.closest?.('#smartUploadModal')){changed.add(e.target.id);queueMicrotask(updateSmartQuestions)}},true);
 document.addEventListener('change',e=>{if(e.target.closest?.('#smartUploadModal')){changed.add(e.target.id);queueMicrotask(updateSmartQuestions)}},true);
 const analyzeBase=analyzeSmartDocument;analyzeSmartDocument=function(){const before=new Map([...changed].map(id=>[id,document.getElementById(id)?.value]));const result=analyzeBase();for(const [id,value] of before){const el=document.getElementById(id);if(el&&value!==undefined)el.value=value}updateSmartQuestions();return result};
 updateSmartQuestions=function(){if(!document.getElementById('smartUploadModal'))return [];const notes=[];if(!pendingSmartFile)notes.push('فایل سند را انتخاب کن.');if(!v('smartProject'))notes.push('پروژه بعداً قابل تکمیل است.');if(!v('smartCategory')&&!v('smartDocCommand'))notes.push('شرح یا دستهٔ هزینه بعداً قابل تکمیل است.');if(!date(v('smartDate')))notes.push(v('smartDate')?'تاریخ نیازمند بررسی است؛ متن واردشده حفظ می‌شود.':'تاریخ سند بعداً قابل تکمیل است.');const box=document.getElementById('smartQuestions');if(box)box.innerHTML=notes.length?`<strong>برای بررسی بعدی:</strong><ul>${notes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul><small>مبدأ، مقصد، بانک و شماره پیگیری اختیاری‌اند.</small>`:'<strong class="ready">اطلاعات اصلی آمادهٔ ثبت است.</strong>';return pendingSmartFile?[]:['فایل سند را انتخاب کن']};
 saveSmartDocument=async function(){
  if(saving)return;if(!pendingSmartFile)return toast('ابتدا فایل سند را انتخاب کن');if(smartAiReceiptBusy||smartOcrBusy)return toast('خواندن تصویر هنوز تمام نشده است');
  const rawAmount=v('smartAmount'),value=amount(rawAmount);if(rawAmount&&!value)return toast('مبلغ را فقط با عدد وارد کن؛ سایر اطلاعات حفظ شده‌اند');
  const file=pendingSmartFile,modal=document.getElementById('smartUploadModal'),id=uid(),eventDate=date(v('smartDate')),description=v('smartDocCommand'),category=v('smartCategory')||description||'نیازمند تکمیل',names=entities(v('smartProject'),v('smartPerson'),eventDate),type=v('smartType')||'سایر',tx=linkingTransactionId&&db.transactions.find(x=>String(x.id)===String(linkingTransactionId));
  const meta={id,name:file.name,title:v('smartTitle')||category,category,...names,docType:type,date:eventDate,amount:value,origin:smartReceiptFields.origin||'',destination:names.party,originBank:smartReceiptFields.originBank||'',destinationBank:smartReceiptFields.destinationBank||'',time:smartReceiptFields.time||'',tracking:smartReceiptFields.tracking||'',note:description,description,ocrText:document.getElementById('smartOcrRaw')?.value??smartOcrText,rawDate:v('smartDate'),size:`${Math.max(1,Math.round(file.size/1024))} KB`,type:file.type||'',status:!eventDate||names.project==='بدون پروژه'||category==='نیازمند تکمیل'?'نیازمند تکمیل':'کامل'};
  saving=true;try{memoryFiles.set(id,{id,blob:file,type:file.type,name:file.name});try{await storeFile(id,file)}catch{}db.documents.unshift(meta);if(!db.categories.includes(category))db.categories.push(category);
   if(tx){Object.assign(meta,{transactionId:tx.id,project:tx.project,party:tx.party,date:tx.date,amount:tx.amount,category:tx.category||category});tx.documentId=id;linkingTransactionId=null;db.completionTasks=db.completionTasks.filter(t=>!(t.type==='transaction.attachment'&&String(t.entityId)===String(tx.id)))}
   else if(/فاکتور خرید|رسید پرداخت|رسید واریزی|سند مالی/.test(type)&&value)db.transactions.push({id:uid(),documentId:id,...names,category,amount:value,date:eventDate,kind:type==='رسید واریزی'?'income':'expense',note:description,time:meta.time,tracking:meta.tracking});
   if(type==='قرارداد پیمانکار'&&names.party&&value)db.contracts.push({id:uid(),documentId:id,title:meta.title,...names,amount:value,date:eventDate,status:'در حال اجرا'});
   meta.status=!date(meta.date)||meta.project==='بدون پروژه'||!meta.category||meta.category==='نیازمند تکمیل'?'نیازمند تکمیل':'کامل';if(meta.status==='نیازمند تکمیل')addCompletionTask('document.review','تکمیل اطلاعات سند',{entityId:id,project:meta.project,key:`document.review:${id}`});save();if(modal===document.getElementById('smartUploadModal'))closeSmartUpload();render();toast(tx?'سند به همان ردیف وصل شد؛ مبلغ دوباره ثبت نشد':'سند و اطلاعات فعلی فرم ذخیره شد');completionSaved('smartUploadModal');
  }finally{saving=false}
 };
 const editorBase=openRecordEditor;openRecordEditor=function(kind,id){editorBase(kind,id);const {doc,tx}=linked(kind,id),record=doc||tx;if(!record)return;const form=document.querySelector('#recordEditor .form-grid');if(!form)return;
  document.getElementById('reDate').value=record.date||record.rawDate||record.rawEntry?.date||'';
  if(doc){document.getElementById('reNote').value=doc.note??tx?.note??'';const details=document.createElement('details');details.className='field full receipt-extra';details.innerHTML='<summary>جزئیات بانکی و متن اسکن (اختیاری)</summary><div class="form-grid"></div>';form.append(details);for(const id of ['reTime','reOrigin','reDestination','reTracking','reOriginBank','reDestinationBank','reDescription']){const field=document.getElementById(id)?.closest('.field');if(field)details.lastElementChild.append(field)}details.lastElementChild.insertAdjacentHTML('beforeend',field('متن کامل اسکن',`<textarea id="reOcrText" rows="4">${esc(doc.ocrText||'')}</textarea>`,'full'))}
  const hint=document.querySelector('#recordEditor .dialog>p');if(hint)hint.textContent='ویرایش متن و پاک‌کردن جزئیات ذخیره می‌شود. اطلاعات ناقص را می‌توانی بعداً تکمیل کنی؛ تصویر اصلی حفظ می‌شود.';
 };
 saveRecordEditor=function(kind,id){const {doc,tx}=linked(kind,id);if(!doc&&!tx)return toast('مورد پیدا نشد');const rawAmount=v('reAmount'),value=amount(rawAmount);if(rawAmount&&!value)return toast('مبلغ معتبر را با عدد وارد کن');const eventDate=date(v('reDate')),names=entities(v('reProject'),v('reParty'),eventDate),category=v('reCategory'),note=v('reNote'),common={...names,date:eventDate,amount:value,category,note,time:v('reTime'),tracking:v('reTracking')};
  if(doc){Object.assign(doc,common,{title:v('reTitle'),docType:v('reType')||'سایر',origin:v('reOrigin'),destination:v('reDestination'),originBank:v('reOriginBank'),destinationBank:v('reDestinationBank'),description:v('reDescription'),ocrText:v('reOcrText'),rawDate:v('reDate')});doc.status=!eventDate||names.project==='بدون پروژه'||!category||!doc.title||(/قرارداد/.test(doc.docType)&&!names.party)?'نیازمند تکمیل':'کامل';if(doc.status==='نیازمند تکمیل')addCompletionTask('document.review','تکمیل اطلاعات سند',{entityId:doc.id,project:doc.project,key:`document.review:${doc.id}`});const contract=db.contracts.find(c=>String(c.documentId)===String(doc.id));if(contract)Object.assign(contract,common,{title:doc.title})}
  if(tx){Object.assign(tx,common,{kind:v('reKind')||tx.kind,dateSource:eventDate?'explicit':'missing',rawDate:v('reDate')});tx.status=!eventDate||names.project==='بدون پروژه'||!names.party||!value?'نیازمند تکمیل':'ثبت اولیه'}
  if(category&&!db.categories.includes(category))db.categories.push(category);save();document.getElementById('recordEditor')?.remove();render();toast('تغییرات و پاک‌کردن متن‌ها ذخیره شد');completionSaved('recordEditor');
 };
 const cardBase=documentInfoCard;documentInfoCard=function(doc){const box=document.createElement('div');box.innerHTML=cardBase(doc);const meta=box.querySelector('.document-meta');if(meta){const details=document.createElement('details');details.className='receipt-extra';details.innerHTML='<summary>جزئیات بانکی</summary><div class="document-meta"></div>';for(const span of [...meta.children])if(/^(مبدأ|مقصد|بانک|پیگیری):?/.test(span.textContent))details.lastElementChild.append(span);meta.after(details);const note=[...meta.children].find(s=>s.textContent.startsWith('بابت:'));if(note&&note.textContent.length>180){const text=note.textContent;note.textContent=text.slice(0,160)+'…';const more=document.createElement('details');more.className='receipt-extra';const summary=document.createElement('summary');summary.textContent='نمایش شرح کامل';const p=document.createElement('p');p.textContent=text;more.append(summary,p);details.before(more)}}return box.innerHTML};
})();

