(function(){
 'use strict';
 let clip=null,clipInput=null,objectUrl='',panel=null;
 function remove(){panel?.remove();panel=null;if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=''}
 function show(input){remove();if(!input?.isConnected||!clip)return;panel=document.createElement('section');panel.className='voice-review';const title=document.createElement('strong');title.textContent='صدای همین فرمان';const audio=document.createElement('audio');audio.controls=true;audio.preload='metadata';objectUrl=URL.createObjectURL(clip);audio.src=objectUrl;const note=document.createElement('p');note.textContent='اگر متن اشتباه است، صدا را گوش کن و تبدیل را دوباره بزن؛ پیش از ثبت، مبلغ، پروژه و تاریخ را بررسی کن.';const retry=document.createElement('button');retry.type='button';retry.className='btn';retry.textContent='تبدیل دوباره همین صدا';retry.onclick=()=>{if(aiVoiceSending)return toast('تبدیل قبلی هنوز در حال انجام است');if(input!==document.getElementById('quickText'))return toast('این فرمان بسته شده است؛ دوباره ضبط کن');sendVoiceToAIReliable(clip).catch(e=>setVoiceState(voiceServiceError(e)))};panel.append(title,audio,note,retry);const status=document.getElementById('voiceStatus');if(status)status.insertAdjacentElement('afterend',panel);else input.insertAdjacentElement('afterend',panel)}
 sendVoiceToAIReliable=async function(blob){
  if(!blob||blob.size<400)throw new Error('empty_audio');const input=document.getElementById('quickText');if(!input)throw new Error('input_missing');clip=blob;clipInput=input;show(input);aiVoiceSending=true;setVoiceState('صدا ضبط شد؛ در حال تبدیل به متن فارسی…',true);
  const saved=(localStorage.getItem(AI_ENDPOINT_KEY)||'').replace(/\/$/,''),endpoints=[...new Set([saved||DEFAULT_AI_ENDPOINT,DEFAULT_AI_ENDPOINT])],form=new FormData();form.append('file',blob,`voice.${voiceFileExtension(blob.type)}`);
  try{let failure;for(const endpoint of endpoints){try{const recognized=await voiceTranscriptionRequest(endpoint,form);if(input!==document.getElementById('quickText')||!input.isConnected)return;if(!recognized){setVoiceState('گفتاری تشخیص داده نشد؛ صدای ضبط‌شده را گوش کن یا تبدیل دوباره را بزن.');return}input.value=recognized;input.dispatchEvent(new Event('input',{bubbles:true}));setVoiceState('متن فارسی آماده شد؛ پیش‌نویس را قبل از ثبت بررسی کن.');setTimeout(()=>{if(input===document.getElementById('quickText')&&input.isConnected)parseQuick()},100);return}catch(error){failure=error;if(error?.name==='AbortError')failure=new Error('timeout');if(!/^(?:TypeError|AbortError)$/.test(error?.name||'')&&!/502|503|504|timeout/i.test(String(error?.message||'')))break}}throw failure}finally{aiVoiceSending=false}
 };
 const style=document.createElement('style');style.textContent='.voice-review{display:flex;flex-direction:column;gap:8px;background:#f5f3eb;border:1px solid #ddd4bf;border-radius:14px;padding:12px;margin:10px 0;min-width:0}.voice-review audio{width:100%;max-width:100%;height:42px}.voice-review p{font-size:12px;margin:0;line-height:1.8}.voice-review button{align-self:flex-start}';document.head.append(style);
 new MutationObserver(()=>{if(clipInput&&!clipInput.isConnected){clip=null;clipInput=null;remove()}}).observe(document.body,{childList:true,subtree:true});
})();
