const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require(process.env.LEDGER_JSDOM||'../../voice-test-runtime/node_modules/jsdom');
const root=path.join(__dirname,'..'),storage='peymanyar-v1-data';
function boot(saved){
 const errors=[],console=new VirtualConsole();console.on('jsdomError',e=>errors.push(e));
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
 const w=new JSDOM(html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,''),{url:'https://alvandi111.github.io/mehdi/',runScripts:'dangerously',virtualConsole:console}).window;
 w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.scrollTo=()=>{};w.confirm=()=>true;w.alert=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});w.fetch=async()=>{throw Error('offline test')};
 if(saved)w.localStorage.setItem(storage,saved);
 // All app scripts in the deployed order. The network SDK is not used in this local ledger test.
 for(const m of html.matchAll(/<script src="([^?\"]+)/g)){const file=m[1];if(file.startsWith('vendor/'))continue;const s=w.document.createElement('script');s.textContent=fs.readFileSync(path.join(root,file),'utf8');w.document.body.append(s)}
 assert.deepEqual(errors,[]);return w;
}

const initial={projects:[{id:1,name:'آرشام'}],people:[],transactions:[{id:99,project:'آرشام',amount:123}],documents:[],contracts:[],daily:[],workStatements:[]};
(async()=>{const w=boot(JSON.stringify(initial)),d=w.document,records=new Map();let urls=0;w.URL.createObjectURL=()=>`blob:advert-test-${++urls}`;w.URL.revokeObjectURL=()=>{};w.storeFile=async(id,file)=>records.set(id,{id,blob:file,name:file.name,type:file.type});w.readFile=async id=>records.get(id);w.eval('openFileDB=async function(){return window.testIDB}');w.testIDB={transaction(){return {objectStore(){return {getAll(){const req={};setTimeout(()=>{req.result=[...records.values()];req.onsuccess()},0);return req}}}}}};
const set=(id,v)=>d.getElementById(id).value=v,financial=JSON.stringify(w.eval('db.transactions'));assert.ok(d.querySelector('.dashboard-ad').textContent.includes('افزودن تبلیغ'));w.openAdvertisement();assert.ok(d.getElementById('adFile').accept.includes('video/mp4'));const gif=new w.File(['GIF89a'],'motion.gif',{type:'image/gif'});w.previewAdvertisement({files:[gif]});assert.ok(d.querySelector('#advertPreview img'));set('adTitle','معرفی خدمات نمونه');set('adDescription','طراحی و اجرای معماری');set('adLink','https://example.com/');await w.saveAdvertisement();assert.ok(w.eval('db.advertisement.fileId').startsWith('advert-'));const firstId=w.eval('db.advertisement.fileId');await w.PeymanyarAdvertisement.hydrate();assert.ok(d.querySelector('#advertMedia img'));assert.equal(d.querySelector('.advert-copy a').href,'https://example.com/');assert.equal(JSON.stringify(w.eval('db.transactions')),financial);
const packed=await w.PeymanyarBackup.pack();assert.ok(packed.files.some(x=>x.id===firstId));assert.equal(packed.data.advertisement.title,'معرفی خدمات نمونه');const stored=w.localStorage.getItem(storage);w.openAdvertisement();set('adTitle','ویرایش بدون تعویض');await w.saveAdvertisement();assert.equal(w.eval('db.advertisement.fileId'),firstId);
w.openAdvertisement();const video=new w.File(['fake-mp4'],'motion.mp4',{type:'video/mp4'});w.previewAdvertisement({files:[video]});assert.ok(d.querySelector('#advertPreview video[controls]'));await w.saveAdvertisement();const videoId=w.eval('db.advertisement.fileId');assert.notEqual(firstId,videoId);await w.PeymanyarAdvertisement.hydrate();assert.ok(d.querySelector('#advertMedia video[controls]'));assert.ok(records.has(firstId));w.openAdvertisement();w.hideAdvertisement();assert.equal(w.eval('db.advertisement.enabled'),false);assert.equal(w.eval('db.advertisement.fileId'),videoId);assert.equal(d.querySelector('#advertMedia'),null);w.openAdvertisement();d.getElementById('adEnabled').checked=true;await w.saveAdvertisement();assert.equal(w.eval('db.advertisement.enabled'),true);
w.openAdvertisement();set('adLink','javascript:alert(1)');await w.saveAdvertisement();assert.ok(d.getElementById('adStatus').textContent.includes('لینک معتبر'));assert.equal(w.eval('db.advertisement.link'),'https://example.com/');set('adLink','https://example.com');w.previewAdvertisement({files:[new w.File(['x'],'bad.html',{type:'text/html'})],value:'bad'});assert.ok(d.getElementById('adStatus').textContent.includes('معتبر'));assert.equal(w.PeymanyarAdvertisement.mediaType({type:'',name:'film.mov'}),'video/quicktime');assert.throws(()=>w.PeymanyarAdvertisement.safeLink('https://secret:password@example.com'));
const before=JSON.stringify(w.eval('db.advertisement'));w.previewAdvertisement({files:[gif]});const store=w.storeFile;w.storeFile=async()=>{throw Error('quota')};await w.saveAdvertisement();assert.equal(JSON.stringify(w.eval('db.advertisement')),before);assert.ok(d.getElementById('advertEditor'));w.storeFile=store;w.eval('window.savedAdSave=save;save=()=>{throw Error("quota")}');await w.saveAdvertisement();assert.equal(JSON.stringify(w.eval('db.advertisement')),before);w.eval('save=window.savedAdSave');w.closeAdvertisement();w.go('settings');assert.ok(d.getElementById('app').textContent.includes('مدیریت تبلیغات'));assert.equal(JSON.stringify(w.eval('db.transactions')),financial);w.close();const reloaded=boot(stored);assert.equal(reloaded.eval('db.advertisement.fileId'),firstId);reloaded.close();console.log('PASS: dashboard/settings entry; GIF/video preview and safe links; persist/reload; metadata edits preserve media; replacement and hide retain previous files; portable backup includes advert and blob; invalid file/link blocked; failed storage preserves previous advert and financial records')})().catch(e=>{console.error(e);process.exitCode=1});
