const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');const {JSDOM}=require(process.env.LEDGER_JSDOM||'../../voice-test-runtime/node_modules/jsdom');const w=new JSDOM('<div id="app"></div><div id="toast"></div>',{url:'https://alvandi111.github.io/mehdi/',runScripts:'dangerously'}).window;w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.scrollTo=()=>{};w.confirm=()=>true;w.alert=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});
for(const f of ['workspace-engine.js','collaboration-engine.js','command-engine.js','contract-engine.js','receipt-date.js','app.js','daily-voice.js','persian-calendar.js','receipt-transport.js','live-dictation.js','entity-editor.js','financial-ledger.js','bulk-entry.js','project-merge.js']){const s=w.document.createElement('script');s.textContent=fs.readFileSync(path.join(__dirname,'..',f),'utf8');w.document.body.appendChild(s)}const db=w.eval('db');db.projects=[{id:1,name:'آرشام',status:'فعال',progress:0}];db.people=[{id:10,name:'کاظم‌پور',aliases:['کازمپور'],role:'بنا',project:'آرشام'}];db.transactions=[];

w.confirm=()=>{throw new Error('Registration must not request confirmation')};
w.openBulkCash('آرشام');w.saveBulkCash();assert.equal(db.transactions.length,0,'blank placeholder ignored');
w.bulkCell(0,'party','کازمپور');w.bulkCell(0,'amount','۵٬۰۰۰٬۰۰۰');w.saveBulkCash();assert.equal(db.transactions.length,1);assert.equal(db.transactions[0].personId,10);assert.equal(db.transactions[0].date,'');assert.equal(db.transactions[0].status,'نیازمند تکمیل');assert.ok(db.completionTasks.some(t=>t.type==='transaction.review'&&t.entityId===db.transactions[0].id));assert.match(w.transactionReportTable(db.transactions),/نیازمند تکمیل/);
const first=db.transactions[0],task=db.completionTasks.find(t=>t.entityId===first.id);assert.equal(w.taskSatisfied(task),false);w.completionAction(task.id);assert.equal(w.document.getElementById('reDate').value,'','editor must not invent date');w.document.getElementById('reDate').value='1405/07/01';w.saveRecordEditor('transaction',first.id);assert.equal(w.taskSatisfied(task),true);assert.equal(first.status,'ثبت اولیه');
w.openBulkCash('آرشام');w.bulkCell(0,'party','کاظم‌پور');w.bulkCell(0,'amount','5000000');w.bulkCell(0,'date','1405/07/01');w.saveBulkCash();assert.equal(db.transactions.length,2);assert.equal(first.mergeReview,'مشکوک به تکرار');assert.equal(db.transactions[1].mergeReview,'مشکوک به تکرار');
w.openBulkCash();w.bulkCell(0,'project','پروژه جدید');w.bulkCell(0,'party','رضایی');w.bulkCell(0,'amount','100');w.bulkCell(0,'date','۶/۶');assert.equal(w.document.querySelector('[aria-label="date ردیف 1"]').value,'۱۴۰۵/۰۶/۰۶');w.saveBulkCash();assert.equal(db.people.length,2);assert.equal(db.projects.length,2);assert.equal(db.transactions[2].date,'1405/06/06');assert.equal(db.transactions[2].personId,db.people[1].id);
w.openBulkCash();w.bulkCell(0,'note','بابت خرید؛ مبلغ را بعداً وارد می‌کنم');w.bulkCell(0,'date','13/40');w.saveBulkCash();const incomplete=db.transactions[3];assert.equal(incomplete.amount,0);assert.equal(incomplete.date,'');assert.equal(incomplete.rawEntry.date,'13/40');assert.equal(incomplete.project,'بدون پروژه');assert.equal(incomplete.party,'');assert.equal(incomplete.personId,null);assert.equal(db.people.length,2);assert.equal(db.projects.length,2);assert.equal(incomplete.status,'نیازمند تکمیل');
w.openBulkCash('آرشام');w.document.getElementById('bulkEntryDate').value='1405/07/01';w.bulkAddRow();w.saveBulkCash();assert.equal(db.transactions.length,4,'default date does not create an empty row');
w.document.getElementById('quickText').value='به رضایی پنج میلیون تومان بابت خرید آهن پرداخت کردم';w.saveBulkCash();assert.equal(db.transactions.length,5,'remaining text parsed and registered');
w.openBulkCash('آرشام');let cell=w.document.querySelector('[aria-label="date ردیف 1"]');cell.value='6/6';cell.focus();cell.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(cell.value,'۱۴۰۵/۰۶/۰۶');assert.equal(w.document.activeElement.getAttribute('aria-label'),'project ردیف 1');for(const key of ['project','party','category']){cell=w.document.activeElement;cell.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}))}cell=w.document.activeElement;assert.equal(cell.getAttribute('aria-label'),'amount ردیف 1');cell.value='۵۰۰۰۰۰۰';cell.setSelectionRange(7,7);cell.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(cell.value,'۵٬۰۰۰٬۰۰۰');assert.equal(cell.parentElement.querySelector('.amount-words').textContent,'پنج میلیون تومان');assert.equal(w.document.activeElement,cell);cell.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(w.document.activeElement.getAttribute('aria-label'),'kind ردیف 1');w.document.activeElement.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Tab',bubbles:true}));assert.equal(w.document.activeElement.getAttribute('aria-label'),'note ردیف 1');w.document.activeElement.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(w.document.activeElement.getAttribute('aria-label'),'date ردیف 2');
console.log('PASS: nonblocking incomplete/duplicate registration, auto-create names, alias linkage, raw input preservation, completion editing, empty placeholders, voice text registration, short dates, keyboard progression and money grouping');w.close();
