const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const {JSDOM}=require('../../voice-test-runtime/node_modules/jsdom');
const w=new JSDOM('<div id="app"></div><div id="toast"></div>',{url:'https://alvandi111.github.io/mehdi/',runScripts:'dangerously'}).window;
w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.scrollTo=()=>{};w.confirm=()=>true;w.alert=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});
for(const file of ['workspace-engine.js','collaboration-engine.js','command-engine.js','contract-engine.js','receipt-date.js','app.js','daily-voice.js','persian-calendar.js','receipt-transport.js','live-dictation.js','entity-editor.js','financial-ledger.js','bulk-entry.js','bulk-grid.js','project-merge.js','receipt-editor.js','dashboard-cash.js','cash-photo.js']){const s=w.document.createElement('script');s.textContent=fs.readFileSync(require('path').join(__dirname,'..',file),'utf8');w.document.body.appendChild(s)}
const db=w.eval('db');db.projects=[{id:1,name:'آرشام'}];db.people=[];db.transactions=[];
w.openCashMode('photo','آرشام');assert.ok(w.document.getElementById('cashPhotoRead'));assert.equal(w.document.getElementById('cashPhotoUnit').value,'rial');
w.bulkImportPhotoRows([{party:'اسماعیل ملکی',description:'آهنگری',amount_toman:30000000,date:'1405/06/08',raw_text:'اصل سطر'},{description:'حمل نخاله',amount_toman:null,date:'',uncertain:['مبلغ ناخوانا']}]);
assert.equal(w.document.querySelectorAll('.bulk-edit-table tbody tr').length,2);assert.equal(w.document.querySelector('[aria-label="party ردیف 1"]').value,'اسماعیل ملکی');
w.saveBulkCash();assert.equal(db.transactions.length,2);assert.equal(db.transactions[0].project,'آرشام');assert.equal(db.transactions[0].amount,30000000);assert.equal(db.transactions[1].status,'نیازمند تکمیل');assert.match(db.transactions[1].note,/مبلغ ناخوانا/);assert.ok(db.completionTasks.some(t=>t.entityId===db.transactions[1].id));w.close();
(async()=>{const code=fs.readFileSync(require('path').join(__dirname,'../ai-worker/worker.js'),'utf8').replace('export default {','const worker = {');const context={Response,Request,File,FormData,AbortSignal,Uint8Array,btoa,URL,fetch:async(url,init)=>{const p=JSON.parse(init.body);assert.match(p.messages[0].content[0].text,/rial/);return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({rows:[{party:'اسماعیل ملکی',amount_toman:30000000,date:'1405/06/08'},{amount_toman:'invalid',date:'6/8',uncertain:['مبلغ']} ]})}}]}),{status:200})}};vm.createContext(context);vm.runInContext(code+';globalThis.readTable=readCashTable;',context);const f=new FormData();f.append('file',new File(['image'],'cash.jpg',{type:'image/jpeg'}));f.append('unit','rial');f.append('year','1405');const r=await context.readTable(new Request('https://test/cash-table',{method:'POST',body:f}),{GROQ_API_KEY:'test'},'https://alvandi111.github.io');const data=await r.json();assert.equal(data.rows.length,2);assert.equal(data.rows[0].amount_toman,30000000);assert.equal(data.rows[1].amount_toman,null);assert.equal(data.rows[1].date,'');console.log('PASS: photo table preview, default project, incomplete saving and completion tasks; backend parsing and invalid-field handling');})().catch(e=>{console.error(e);process.exitCode=1});
