const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require(process.env.LEDGER_JSDOM||'../../voice-test-runtime/node_modules/jsdom');
const root=path.join(__dirname,'..'),storage='peymanyar-v1-data';
function boot(saved){
 const errors=[],console=new VirtualConsole();console.on('jsdomError',e=>errors.push(e));
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
 const w=new JSDOM(html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,''),{url:'https://alvandi111.github.io/mehdi/',runScripts:'dangerously',virtualConsole:console}).window;
 w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.scrollTo=()=>{};w.confirm=()=>true;w.alert=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});w.fetch=async()=>{throw Error('offline test')};
 if(saved)w.localStorage.setItem(storage,saved);
 // All app scripts in the deployed order. The network SDK is not used in this local ledger test.
 for(const m of html.matchAll(/<script src="([^?\"]+)/g)){const file=m[1];if(file.startsWith('vendor/'))continue;const s=w.document.createElement('script');s.textContent=fs.readFileSync(path.join(root,file),'utf8');w.document.body.append(s)}
 assert.deepEqual(errors,[]);return w;
}

const initial={projects:[{id:1,name:'آرشام',aliases:['ارشام']},{id:2,name:'حسن‌وند'}],people:[],transactions:[{id:99,amount:700}],documents:[],contracts:[],workStatements:[],daily:[{id:10,projectId:1,project:'آرشام',date:'1405/07/15',workers:7,text:'گزارش اولیه',audioIds:[123],custom:'keep'},{id:11,project:'ارشام',date:'1405/07/16',workers:7,labourWorkers:7,workDays:1,text:'هفت کارگر'},{id:12,projectId:1,project:'آرشام',date:'1405/07/16',workers:7,labourWorkers:7,workDays:1,text:'تکمیل همان روز'}]};
(async()=>{let w=boot(JSON.stringify(initial)),d=w.document;const value=(id,x)=>d.getElementById(id).value=x;w.go('daily');assert.equal(d.querySelectorAll('[onclick^="openDailyEditor"]').length,3);w.openDailyEditor(10);value('deProject','2');value('deDate','۱۴۰۵/۰۷/۱۴');value('deWorkers','۷');value('deLabour','۷');value('deDays','۰٫۵');value('deWeather','ابری');value('deText','اصلاح متن');w.saveDailyEditor();let db=w.eval('db');assert.equal(db.daily.length,3);const r=db.daily.find(x=>x.id===10);assert.equal(r.projectId,2);assert.equal(r.project,'حسن‌وند');assert.equal(r.date,'1405/07/14');assert.equal(r.labourWorkers,7);assert.equal(r.workDays,.5);assert.equal(r.text,'اصلاح متن');assert.deepEqual(Array.from(r.audioIds),[123]);assert.equal(r.custom,'keep');assert.equal(db.transactions[0].amount,700);assert.equal(w.PeymanyarDaily.totals(w.PeymanyarProjectHub.data(db.projects[0]).daily).personDays,7);assert.equal(w.PeymanyarDaily.totals(w.PeymanyarProjectHub.data(db.projects[1]).daily).personDays,3.5);w.openProjectSection(2,'daily');assert.ok(d.getElementById('app').textContent.includes('کارکرد کارگران'));assert.ok(d.getElementById('app').textContent.includes('اصلاح متن'));assert.ok(!d.getElementById('app').textContent.includes('هفت کارگر'));
// Reject impossible dates, negative counts, labour greater than total; rollback failed persistence.
w.openDailyEditor(10);value('deDate','1405/07/31');w.saveDailyEditor();assert.ok(d.getElementById('dailyEditor'));assert.equal(r.date,'1405/07/14');value('deDate','1405/07/14');value('deWorkers','-1');w.saveDailyEditor();assert.equal(r.workers,7);value('deWorkers','7');value('deLabour','8');w.saveDailyEditor();assert.equal(r.labourWorkers,7);value('deLabour','7');value('deText','must rollback');w.eval('window.realDailySave=save;save=()=>{throw Error("quota")}');w.saveDailyEditor();assert.equal(r.text,'اصلاح متن');w.eval('save=window.realDailySave');d.getElementById('dailyEditor').remove();
// Reload saved data; project ID and audio survive. Old workforce alone is not counted as labour.
const saved=w.localStorage.getItem(storage);w.close();w=boot(saved);d=w.document;assert.equal(w.eval('db.daily.find(x=>x.id===10).projectId'),2);assert.equal(w.PeymanyarDaily.totals([{workers:100,date:'1405/07/01'}]).personDays,0);
w.openLongDailyReport('آرشام');value('dailyVoiceText','امروز هفت تا کارگر داشتیم در پروژه آرشام');w.suggestDailyReportFields();assert.equal(d.getElementById('dailyVoiceLabour').value,'7');assert.equal(d.getElementById('dailyVoiceWorkers').value,'7');value('dailyVoiceDate','1405/07/17');await w.saveLongDailyReport();assert.equal(w.eval('db.daily[0].labourWorkers'),7);assert.equal(w.eval('db.daily[0].projectId'),1);assert.equal(w.eval('db.daily.length'),4);
w.openForm('daily');value('fProject','حسن‌وند');value('fDate','1405/07/17');value('fWorkers','3');value('fLabour','3');value('fDays','1');value('fText','گزارش دستی');w.submitForm('daily');assert.equal(w.eval('db.daily[0].projectId'),2);assert.equal(w.eval('db.daily[0].labourWorkers'),3);assert.equal(w.eval('db.daily.length'),5);
await w.openLongDailyDetail(w.eval('db.daily[0].id'));assert.ok(d.getElementById('dailyDetailModal').textContent.includes('ویرایش مشخصات'));assert.ok(d.getElementById('dailyDetailModal').textContent.includes('حسن‌وند'));w.close();console.log('PASS: deployed report editing, reassign/reload, identity/audio preservation, manual and Persian voice-text labour, daily dedup totals, strict validation and failed-save rollback')})().catch(e=>{console.error(e);process.exitCode=1});
