const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {JSDOM}=require('../../voice-test-runtime/node_modules/jsdom');
const w=new JSDOM('<div id="app"></div><div id="toast"></div>',{url:'https://alvandi111.github.io/mehdi/',runScripts:'dangerously'}).window;
w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.scrollTo=()=>{};w.confirm=()=>true;w.alert=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});
for(const f of ['workspace-engine.js','collaboration-engine.js','command-engine.js','contract-engine.js','receipt-date.js','app.js','entity-editor.js','financial-ledger.js','entity-delete.js']){const s=w.document.createElement('script');s.textContent=fs.readFileSync(path.join(__dirname,'..',f),'utf8');w.document.body.append(s)}
Object.assign(w.eval('db'),{projects:[{id:1,name:'آرشام',status:'فعال',progress:0},{id:2,name:'امامی',status:'فعال',progress:0}],people:[{id:10,name:'احمد',role:'بنا',project:'آرشام'}],transactions:[{id:20,personId:10,party:'احمد',project:'آرشام',projectId:1,amount:100,kind:'expense'}],documents:[{id:30,name:'رسید',personId:10,project:'آرشام',projectId:1}],contracts:[{id:40,title:'بنا',personId:10,party:'احمد',project:'آرشام',amount:1000}],daily:[{id:50,project:'آرشام',text:'کار',date:'1405/07/01',workers:2}],completionTasks:[{id:60,entityId:10,type:'person.details'},{id:61,entityId:20,type:'transaction.review'}]});
w.go('people');assert.equal(w.document.querySelectorAll('.entity-swipe').length,1);assert.equal(w.document.querySelectorAll('.entity-swipe .entity-delete-visible').length,1);assert.equal(w.document.querySelector('button button'),null);
function touch(row,type,x,y){const e=new w.Event(type,{bubbles:true});Object.defineProperty(e,type==='touchstart'?'touches':'changedTouches',{value:[{clientX:x,clientY:y}]});row.dispatchEvent(e)}
let row=w.document.querySelector('.entity-swipe');touch(row,'touchstart',100,100);touch(row,'touchend',102,200);assert.ok(!row.classList.contains('entity-swipe-open'));
touch(row,'touchstart',100,100);touch(row,'touchend',30,102);assert.ok(row.classList.contains('entity-swipe-open'));assert.equal(row.querySelector('.entity-delete-reveal').tabIndex,0);
w.go('people');row=w.document.querySelector('.entity-swipe');touch(row,'touchstart',100,100);touch(row,'touchend',180,100);assert.ok(row.classList.contains('entity-swipe-right'));row.querySelector('.project-card-button').click();assert.equal(w.eval('page'),'people');
let before=JSON.stringify(w.eval('db'));w.confirm=()=>false;w.removeEntity('person',10);assert.equal(JSON.stringify(w.eval('db')),before);
w.confirm=()=>true;w.openPerson(10);assert.ok(w.document.querySelector('.ledger-context .entity-delete-visible'));w.removeEntity('person',10);assert.equal(w.eval('page'),'people');let db=w.eval('db');assert.equal(db.people.length,0);assert.equal(db.transactions[0].amount,100);assert.equal(db.transactions[0].party,'احمد');assert.equal(db.transactions[0].personId,null);assert.equal(db.documents.length,1);assert.equal(db.contracts.length,1);assert.equal(db.completionTasks.length,1);
w.openProject(1);assert.ok(w.document.querySelector('.ledger-context .entity-delete-visible'));w.removeEntity('project',1);db=w.eval('db');assert.equal(db.projects.length,1);assert.equal(db.transactions[0].project,'آرشام');assert.equal(db.transactions[0].projectId,null);assert.equal(db.daily.length,1);assert.equal(JSON.parse(w.localStorage.getItem('peymanyar-v1-data')).projects.length,1);
w.go('contracts');assert.ok(w.document.querySelector('.entity-swipe'));w.removeEntity('contract',40);assert.equal(w.eval('db').contracts.length,0);assert.equal(w.eval('db').transactions.length,1);
w.go('daily');assert.ok(w.document.querySelector('.entity-swipe'));w.removeEntity('daily',50);assert.equal(w.eval('db').daily.length,0);
w.eval('db').people.push({id:100,name:'یاسر'});const originalSave=w.save;w.save=()=>{throw Error('quota')};w.removeEntity('person',100);assert.equal(w.eval('db').people.length,1);w.save=originalSave;
console.log('PASS: visible buttons and both swipe directions; vertical scrolling and click suppression; cancellation; historical amounts/files preserved; references/tasks cleaned; detail navigation; persistence failure rollback');w.close();
