const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require(process.env.LEDGER_JSDOM||'../../voice-test-runtime/node_modules/jsdom');
const root=path.join(__dirname,'..');
const w=new JSDOM('<div id="app"></div><div id="toast"></div>',{url:'https://alvandi111.github.io/mehdi/',runScripts:'dangerously'}).window;
w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.Blob=Blob;w.scrollTo=()=>{};w.confirm=()=>true;w.alert=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});
for(const f of ['workspace-engine.js','collaboration-engine.js','command-engine.js','contract-engine.js','receipt-date.js','app.js','daily-voice.js','persian-calendar.js','receipt-transport.js','live-dictation.js','entity-editor.js','financial-ledger.js']){const script=w.document.createElement('script');script.textContent=fs.readFileSync(path.join(root,f),'utf8');w.document.body.appendChild(script)}
const db=w.eval('db');Object.assign(db,{projects:[{id:1,name:'آرشام',status:'فعال',progress:0},{id:2,name:'سپیدار',status:'فعال',progress:0}],people:[{id:10,name:'کاظم‌پور',role:'بنا',project:'آرشام',projects:['آرشام','سپیدار']}],transactions:[{id:20,party:'کاظم‌پور',project:'آرشام',amount:5000000,date:'۱۴۰۵/۷/۳',kind:'expense',documentId:30,note:'علی‌الحساب'},{id:21,party:'کاظم‌پور',project:'سپیدار',amount:9000000,date:'1405/07/02',kind:'expense'},{id:22,party:'کارفرما',project:'آرشام',amount:12000000,date:'1405/07/01',kind:'income'},{id:23,party:'کاظم‌پور',project:'آرشام',amount:2000000,date:'1405/07/02',kind:'expense'}],documents:[{id:30,name:'رسید',party:'کاظم‌پور',project:'آرشام',type:'رسید پرداخت'}],contracts:[],daily:[],completionTasks:[]});
w.openProject(1);const d=w.document;assert.equal(d.querySelectorAll('.ledger-panel').length,1);assert.equal(d.querySelectorAll('.ledger-table tbody tr').length,3);assert.equal(w.eval('activeReport.rows[0].id'),22);assert.equal(w.eval('activeReport.rows[2].id'),20);assert.equal(w.eval('activeReport.rows.reduce((s,r)=>s+(r.kind==="expense"?r.amount:0),0)'),7000000);assert.ok(d.querySelector('.ledger-extras'));assert.match(d.querySelector('.ledger-table').textContent,/مشاهده سند/);assert.match(d.querySelector('.ledger-table').textContent,/افزودن سند/);
d.querySelector('.ledger-name').click();assert.equal(d.querySelectorAll('.ledger-table tbody tr').length,2);assert.match(d.querySelector('.ledger-heading h2').textContent,/آرشام/);assert.equal(w.eval('activeReport.rows.some(r=>r.project==="سپیدار")'),false);
w.ledgerPersonScope('');assert.equal(d.querySelectorAll('.ledger-table tbody tr').length,3);
w.openProject(1);d.getElementById('ledgerFrom').value='۱۴۰۵/۰۷/۰۲';d.getElementById('ledgerTo').value='۱۴۰۵/۰۷/۰۳';w.ledgerApply('project:1');assert.equal(w.eval('activeReport.rows.length'),2);w.ledgerSet('project:1','order','desc');assert.equal(w.eval('activeReport.rows[0].id'),20);
let output;w.download=(name,data,type)=>{output={name,data,type}};w.exportActiveCSV();assert.match(output.data,/علی‌الحساب/);assert.doesNotMatch(output.data,/12000000|9000000/);assert.match(output.data,/7000000/);
let html='';w.open=()=>({document:{write:s=>html=s,close(){}},print(){}});w.printActiveReport();assert.match(html,/علی‌الحساب/);assert.doesNotMatch(html,/سپیدار/);assert.match(html,/Save as PDF/);
(async()=>{w.exportActiveExcel();assert.match(output.name,/\.xlsx$/);fs.writeFileSync('/tmp/ledger-test.xlsx',Buffer.from(await output.data.arrayBuffer()));w.prepareReport('آرشام','کاظم‌پور');assert.equal(d.querySelectorAll('#reportModal .ledger-table tbody tr').length,2);assert.equal(w.eval('activeReport.rows.length'),2);w.ledgerSet('modal','order','desc');assert.equal(w.eval('activeReport.rows[0].id'),20);console.log('PASS: chronological project ledger, project-scoped person drill-down, all-project switch, dates/order, document actions, filtered CSV/print/XLSX, shared query modal');w.close()})().catch(e=>{console.error(e);process.exitCode=1});
