const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require(process.env.LEDGER_JSDOM||'../../voice-test-runtime/node_modules/jsdom');
const root=path.join(__dirname,'..'),storage='peymanyar-v1-data';
function boot(saved){
 const errors=[],console=new VirtualConsole();console.on('jsdomError',e=>errors.push(e));
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
 const w=new JSDOM(html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,''),{url:'https://alvandi111.github.io/mehdi/',runScripts:'dangerously',virtualConsole:console}).window;
 w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.scrollTo=()=>{};w.confirm=()=>true;w.alert=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});w.fetch=async()=>{throw Error('offline test')};
 if(saved)w.localStorage.setItem(storage,saved);
 // All app scripts in the deployed order. The network SDK is not used in this local ledger test.
 for(const m of html.matchAll(/<script src="([^?\"]+)/g)){const file=m[1];if(file.startsWith('vendor/'))continue;const s=w.document.createElement('script');s.textContent=fs.readFileSync(path.join(root,file),'utf8');w.document.body.append(s)}
 assert.deepEqual(errors,[]);return w;
}

const initial={projects:[{id:1,name:'آرشام',aliases:['ارشام']},{id:2,name:'حسن‌وند'}],people:[{id:10,name:'یاسر',role:'نگهبان',project:'آرشام'},{id:11,name:'علی رضایی',role:'جوشکار',project:'آرشام'}],transactions:[],documents:[],contracts:[],daily:[]};
(async()=>{let w=boot(JSON.stringify(initial)),d=w.document;const value=(id,x)=>d.getElementById(id).value=x;
let files=new Map();w.storeFile=async(id,file)=>files.set(id,file);w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};
function command(text){w.openQuick();value('quickText',text);w.parseQuick()}
command('گزارش پروژه آرشام دیروز هفت تا کارگر داشتیم و دو میلیون تومان سیمان خریدیم');assert.equal(w.PeymanyarIntents.detect('گزارش پروژه آرشام دیروز هفت تا کارگر داشتیم و دو میلیون تومان سیمان خریدیم'),'daily_create');assert.equal(d.getElementById('irProject').value,'آرشام');assert.equal(d.getElementById('irWorkers').value,'7');assert.equal(d.getElementById('spAmount'),null);assert.equal(w.eval('db.daily.length'),0);d.getElementById('quickText')._voiceBlob=new w.Blob(['sound'],{type:'audio/wav'});w.parseQuick();await w.saveRoutedCommand(false);assert.equal(w.eval('db.daily.length'),1);assert.equal(w.eval('db.daily[0].projectId'),1);assert.equal(w.eval('db.daily[0].audioIds.length'),1);assert.equal(files.size,1);assert.equal(w.eval('db.transactions.length'),0);
// No project: preserve as an incomplete request, reload and complete exactly once.
command('گزارش پروژه امروز بتن ریزی انجام شد');value('irProject','');await w.saveRoutedCommand(false);assert.ok(d.getElementById('irStatus').textContent.includes('پروژه'));await w.saveRoutedCommand(true);assert.equal(w.eval('db.commandDrafts.length'),1);const draftId=w.eval('db.commandDrafts[0].id');let saved=w.localStorage.getItem(storage);w.close();w=boot(saved);d=w.document;w.storeFile=async()=>{};w.openCommandDrafts();assert.match(d.getElementById('commandDraftInbox').textContent,/بتن ریزی/);w.resumeCommandDraft(draftId);value('irProject','آرشام');await w.saveRoutedCommand(false);assert.equal(w.eval('db.daily.length'),2);assert.equal(w.eval('db.commandDrafts.length'),0);
command('یک قرارداد با علی رضایی برای پروژه آرشام موضوع جوشکاری طبقه دوم مبلغ دو میلیون تومان بساز');assert.equal(d.getElementById('irKind').value,'contract_create');assert.equal(d.getElementById('irParty').value,'علی رضایی');value('irScope','جوشکاری طبقه دوم');await w.saveRoutedCommand(false);assert.equal(w.eval('db.contracts.length'),1);assert.equal(w.eval('db.people.length'),2);assert.equal(w.eval('db.contracts[0].personId'),11);assert.equal(w.eval('db.contracts[0].projectId'),1);assert.equal(w.eval('db.transactions.length'),0);w.editContractDraft(w.eval('db.contracts[0].id'));assert.ok(d.getElementById('ctScope').value.includes('طبقه دوم'));d.getElementById('contractBuilder').remove();
command('ایجاد پیمانکار به نام رضا کریمی با تخصص نقاش برای پروژه آرشام شماره 09123456789');assert.equal(d.getElementById('irKind').value,'person_create');assert.equal(d.getElementById('irPhone').value,'09123456789');await w.saveRoutedCommand(false);assert.equal(w.eval('db.people.length'),3);assert.equal(w.eval('db.people[2].phone'),'09123456789');command('پیمانکار جدید به نام رضا کریمی نقاش برای پروژه آرشام ثبت کن');await w.saveRoutedCommand(false);assert.equal(w.eval('db.people.length'),3);
command('پرداختی به یاسر بابت نگهبانی آرشام دو میلیون تومان');assert.ok(d.getElementById('spAmount'));assert.equal(d.getElementById('spKind').value,'expense');command('گزارش مالی پروژه آرشام را نشان بده');assert.equal(d.getElementById('irKind').value,'financial_query');command('گزارش پروژه آرشام پنجاه کیسه سیمان وارد انبار شد');assert.equal(d.getElementById('irKind').value,'daily_create');command('پنجاه کیسه سیمان وارد انبار پروژه آرشام شد');assert.equal(d.getElementById('irKind').value,'inventory_create');
command('پرداختی به یاسر بابت نگهبانی آرشام دو میلیون تومان');await w.saveRoutedCommand(true);const paymentDraft=w.eval('db.commandDrafts[0].id');w.resumeCommandDraft(paymentDraft);await w.confirmSmartPlan();assert.equal(w.eval('db.commandDrafts.length'),0);assert.equal(w.eval('db.transactions.length'),1);
command('گزارش پروژه آرشام امروز کار کردیم');w.changeCommandIntent('transaction_create');assert.ok(d.getElementById('spAmount'));assert.equal(d.getElementById('irKind').value,'transaction_create');
// Change intent and reject invalid counts; failed persistence rolls back all records.
command('گزارش پروژه آرشام امروز کار کردیم');value('irWorkers','-1');await w.saveRoutedCommand(false);assert.equal(w.eval('db.daily.length'),2);value('irWorkers','3');w.eval('window.realSave=save;save=()=>{throw Error("quota")}');await w.saveRoutedCommand(false);assert.equal(w.eval('db.daily.length'),2);assert.match(d.getElementById('irStatus').textContent,/quota/);w.eval('save=window.realSave');w.changeCommandIntent('contract_create');assert.ok(d.getElementById('irScope'));await w.saveRoutedCommand(true);assert.equal(w.eval('db.commandDrafts.length'),1);w.close();console.log('PASS: full deployed command routing, reports with amounts/stock narrative, audio preservation, reload/complete once, contracts canonical IDs/editing, person phone and no duplicate, payment/query regressions, editable intent, invalid fields and rollback');})().catch(e=>{console.error(e);process.exitCode=1});
