const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require(process.env.LEDGER_JSDOM||'../../voice-test-runtime/node_modules/jsdom');
const root=path.join(__dirname,'..'),storage='peymanyar-v1-data';
function boot(saved){
 const errors=[],console=new VirtualConsole();console.on('jsdomError',e=>errors.push(e));
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
 const w=new JSDOM(html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,''),{url:'https://alvandi111.github.io/mehdi/',runScripts:'dangerously',virtualConsole:console}).window;
 w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.scrollTo=()=>{};w.confirm=()=>true;w.alert=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});w.fetch=async()=>{throw Error('offline test')};
 if(saved)w.localStorage.setItem(storage,saved);
 // All app scripts in the deployed order. The network SDK is not used in this local ledger test.
 for(const m of html.matchAll(/<script src="([^?\"]+)/g)){const file=m[1];if(file.startsWith('vendor/'))continue;const s=w.document.createElement('script');s.textContent=fs.readFileSync(path.join(root,file),'utf8');w.document.body.append(s)}
 assert.deepEqual(errors,[]);return w;
}
const initial={projects:[{id:1,name:'آرشام',aliases:['ارشام']},{id:2,name:'حسن‌وند',aliases:[]}],people:[],transactions:[{id:40,projectId:1,project:'آرشام',amount:1000,party:'فروشنده',date:'1405/07/01',kind:'expense'}],documents:[{id:50,projectId:1,project:'آرشام',name:'فاکتور'}],contracts:[],daily:[]};
let w=boot(JSON.stringify(initial)),d=w.document;const db=()=>w.eval('db'),set=(id,v)=>d.getElementById(id).value=String(v);
function fill(name,qty,unit='عدد',kind='in',projectId=1){w.openInventoryEntry(String(projectId));set('invAction',kind);set('invDate','1405/07/16');const l=d.querySelector('.inventory-line');l.querySelector('.inv-name').value=name;w.inventoryItemChanged(l.querySelector('.inv-name'));l.querySelector('.inv-qty').value=String(qty);l.querySelector('.inv-unit').value=unit;return l}
(async()=>{
assert.ok(w.dashboard().includes('انبار پروژه‌ها'));w.eval('selectedProjectId=1');assert.ok(w.projectDetail().includes('انبار و تجهیزات پروژه'));
const financial=JSON.stringify(db().transactions),docs=JSON.stringify(db().documents);fill('چسب آکواریوم',20);set('invDocument',50);set('invTransaction',40);await w.saveInventoryEntry();assert.equal(db().inventoryMoves.length,1);assert.equal(w.PeymanyarInventory.stock(1)[0].quantity,20);assert.equal(w.PeymanyarInventory.stock(2).length,0);assert.equal(JSON.stringify(db().transactions),financial);assert.equal(JSON.stringify(db().documents),docs);assert.equal(db().inventoryMoves[0].transactionId,'40');
fill('چسب اپوکسی',5,'کیلوگرم');await w.saveInventoryEntry();assert.equal(db().inventoryMoves.length,2);assert.notEqual(db().inventoryMoves[0].itemId,db().inventoryMoves[1].itemId);
fill('چسب مخصوص آب‌بندی',10,'بسته');await w.saveInventoryEntry();const newItem=w.PeymanyarInventory.catalogue().find(i=>i.name==='چسب مخصوص آب‌بندی');assert.ok(newItem);w.openInventoryEntry('2');assert.ok(d.getElementById('inventorySuggestions').innerHTML.includes('چسب مخصوص آب‌بندی'));w.closeInventoryEntry();
fill('چسب آکواریوم',3,'عدد','out');await w.saveInventoryEntry();assert.equal(w.PeymanyarInventory.stock(1).find(i=>i.name==='چسب آکواریوم').quantity,17);
fill('چسب آکواریوم',50,'عدد','out');const before=JSON.stringify(db());await w.saveInventoryEntry();assert.equal(JSON.stringify(db()),before);assert.ok(d.getElementById('inventoryError').textContent.includes('کافی نیست'));w.closeInventoryEntry();
fill('چسب آکواریوم',4,'عدد','transfer');set('invToProject',2);await w.saveInventoryEntry();assert.equal(w.PeymanyarInventory.stock(1).find(i=>i.name==='چسب آکواریوم').quantity,13);assert.equal(w.PeymanyarInventory.stock(2).find(i=>i.name==='چسب آکواریوم').quantity,4);let transfer=db().inventoryMoves.at(-1),id=transfer.id;w.openInventoryEntry('1',id);d.querySelector('.inv-qty').value='2';await w.saveInventoryEntry();assert.equal(db().inventoryMoves.at(-1).id,id);assert.equal(w.PeymanyarInventory.stock(2)[0].quantity,2);
w.confirm=()=>false;w.deleteInventoryMove(id);assert.ok(db().inventoryMoves.some(m=>m.id===id));w.confirm=()=>true;w.deleteInventoryMove(id);assert.ok(!db().inventoryMoves.some(m=>m.id===id));assert.equal(w.PeymanyarInventory.stock(2).length,0);w.deleteInventoryMove(db().inventoryMoves[0].id);assert.ok(db().inventoryMoves.some(m=>m.transactionId==='40'));assert.equal(JSON.stringify(db().transactions),financial);
fill('چسب آکواریوم',1);const storageProto=Object.getPrototypeOf(w.localStorage),setItem=storageProto.setItem;storageProto.setItem=()=>{throw Error('quota')};const safe=JSON.stringify(db());await w.saveInventoryEntry();assert.equal(JSON.stringify(db()),safe);storageProto.setItem=setItem;w.closeInventoryEntry();
fill('چسب آکواریوم',1);w.addInventoryLine();const second=d.querySelectorAll('.inventory-line')[1];second.querySelector('.inv-name').value='جنس تازه';second.querySelector('.inv-qty').value='7';second.querySelector('.inv-unit').value='بسته';await w.saveInventoryEntry();assert.equal(db().inventoryMoves.at(-1).batchId,db().inventoryMoves.at(-2).batchId);
const voice=w.PeymanyarInventory.parse('امروز پنجاه کیسه سیمان برای پروژه آرشام وارد انبار شد');assert.equal(voice.projectId,1);assert.equal(voice.lines[0].quantity,50);assert.equal(voice.lines[0].itemName,'سیمان');const custom=w.PeymanyarInventory.parse('۲۰ بسته چسب مخصوص آب‌بندی در پروژه حسن‌وند وارد انبار شد');assert.equal(custom.projectId,2);assert.equal(custom.lines[0].itemId,newItem.id);const unknown=w.PeymanyarInventory.parse('۱۰ عدد چسب ویژه برای پروژه آرشام وارد انبار شد');assert.equal(unknown.lines[0].itemName,'چسب ویژه');const epoxy=w.PeymanyarInventory.parse('۲ کیلوگرم چسب اپوکسی برای پروژه آرشام وارد انبار شد');assert.equal(epoxy.lines[0].itemName,'چسب اپوکسی');assert.equal(epoxy.lines[0].quantity,2);const fractional=w.PeymanyarInventory.parse('۲٫۵ متر ریسه برای آرشام وارد انبار شد');assert.equal(fractional.lines[0].quantity,2.5);
w.openQuick();set('quickText','دیروز پنجاه کیسه سیمان برای پروژه آرشام وارد انبار شد');w.parseQuick();assert.ok(d.getElementById('parsedResult').textContent.includes('پیش‌نویس انبار'));w.openInventoryEntry('',null,null,w.inventoryParsedPlan);assert.equal(d.getElementById('invProject').value,'1');assert.equal(d.querySelector('.inv-qty').value,'50');await w.saveInventoryEntry();assert.equal(db().inventoryMoves.at(-1).quantity,50);assert.equal(JSON.stringify(db().transactions),financial);
w.editInventoryItem(newItem.id);set('invItemAliases','چسب عایق');w.saveInventoryItem(newItem.id);assert.equal(w.PeymanyarInventory.parse('۵ بسته چسب عایق برای پروژه آرشام وارد انبار شد').lines[0].itemId,newItem.id);
fill('سیمان',1,'کیسه','transfer');set('invToProject',1);await w.saveInventoryEntry();assert.ok(d.getElementById('inventoryError').textContent.includes('متفاوت'));w.closeInventoryEntry();
const records=new Map();w.eval('openFileDB=async function(){return window.testIDB}');w.testIDB={transaction(store,mode){const t={objectStore(){return {getAll(){const req={};setTimeout(()=>{req.result=[...records.values()];req.onsuccess()},0);return req},put(r){records.set(r.id,r)},delete(id){records.delete(id)}}}};if(mode==='readwrite')setTimeout(()=>t.oncomplete?.(),0);return t}};
fill('سیمان',2,'کیسه');const file=new w.File(['invoice'], 'invoice.txt',{type:'text/plain'});Object.defineProperty(d.getElementById('invFile'),'files',{value:[file]});await w.saveInventoryEntry();const uploaded=db().inventoryMoves.at(-1),attached=uploaded.documentId;assert.ok(records.has(attached));assert.ok(db().documents.some(x=>x.id===attached));assert.equal(JSON.stringify(db().transactions),financial);
const packed=await w.PeymanyarBackup.pack();assert.equal(JSON.stringify(packed.data.inventoryMoves),JSON.stringify(db().inventoryMoves));assert.ok(packed.files.some(f=>f.id===attached));w.deleteInventoryMove(uploaded.id);assert.ok(records.has(attached));assert.ok(db().documents.some(x=>x.id===attached));assert.throws(()=>w.PeymanyarBackup.validate({...packed,data:{...packed.data,inventoryMoves:{}}}));
fill('سیمان',1,'کیسه','transfer');set('invDate',db().inventoryMoves.map(m=>m.date).sort().at(-1));set('invToProject',2);await w.saveInventoryEntry();const transferBefore=db().inventoryMoves.at(-1);w.openProjectMerge(1);set('mergeSource',2);set('mergeTarget',1);w.confirmProjectMerge();assert.equal(db().projects.length,1);const mergedTransfer=db().inventoryMoves.find(m=>m.id===transferBefore.id);assert.equal(mergedTransfer.toProjectId,1);assert.equal(mergedTransfer.toProject,'آرشام');assert.equal(w.PeymanyarInventory.stock(1).find(x=>x.name==='سیمان').quantity,50);assert.equal(db().inventoryMoves.length,packed.data.inventoryMoves.length);w.PeymanyarInventory.validateBalances(db().inventoryMoves);
const saved=w.localStorage.getItem(storage),round=JSON.stringify(db().inventoryMoves);w.close();w=boot(saved);d=w.document;assert.equal(JSON.stringify(db().inventoryMoves),round);assert.ok(w.PeymanyarInventory.catalogue().some(i=>i.name==='جنس تازه'));assert.equal(JSON.stringify(db().transactions),financial);
console.log('PASS: production order; inline shared catalogue; distinct adhesives; project isolation; entry/use/transfer; stable-ID editing; cancellation/deletion; chronology and negative-stock protection; quota rollback; multi-item receipt; Persian words and decimals; unknown item and aliases; typed/voice text preview; finance untouched; fresh-page persistence');w.close();
})().catch(e=>{console.error(e);process.exitCode=1});
