const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require(process.env.LEDGER_JSDOM||'../../voice-test-runtime/node_modules/jsdom');
const root=path.join(__dirname,'..'),storage='peymanyar-v1-data';
function boot(saved){
 const errors=[],console=new VirtualConsole();console.on('jsdomError',e=>errors.push(e));
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
 const w=new JSDOM(html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,''),{url:'https://alvandi111.github.io/mehdi/',runScripts:'dangerously',virtualConsole:console}).window;
 w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.scrollTo=()=>{};w.confirm=()=>true;w.alert=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});w.fetch=async()=>{throw Error('offline test')};
 if(saved)w.localStorage.setItem(storage,saved);
 // All app scripts in the deployed order. The network SDK is not used in this local ledger test.
 for(const m of html.matchAll(/<script src="([^?\"]+)/g)){const file=m[1];if(file.startsWith('vendor/'))continue;const s=w.document.createElement('script');s.textContent=fs.readFileSync(path.join(root,file),'utf8');w.document.body.append(s)}
 assert.deepEqual(errors,[]);return w;
}
const initial={projects:[{id:1,name:'ارشام'},{id:2,name:'آرشام'},{id:3,name:'دیگر'}],people:[{id:10,name:'یاسر',role:'نگهبان',project:'ارشام'},{id:11,name:'علی',role:'نگهبان',project:'دیگر'},{id:20,name:'اسماعیل ملکی',role:'جوشکار',project:'ارشام'},{id:21,name:'محمدزاده',role:'جوشکار',project:'ارشام'},{id:22,name:'رضا',role:'جوشکار',project:'دیگر'}],transactions:[],documents:[],contracts:[],daily:[],categories:[],completionTasks:[]};
let w=boot(JSON.stringify(initial)),d=w.document;const db=()=>w.eval('db');
function preview(text){w.openQuick();d.getElementById('quickText').value=text;w.parseQuick()}
function click(selector){const b=d.querySelector(selector);assert.ok(b,selector);b.click()}
preview('یک میلیون تومان بابت نگهبانی در پروژه ارشام دیروز پرداخت شد');assert.equal(d.getElementById('spParty').value,'یاسر');assert.equal(w.v21Plan.pickPersonId,10);assert.ok(d.querySelector('[data-payment-project="2"]'));w.confirmSmartPlan();assert.equal(db().transactions[0].personId,10);assert.equal(db().transactions[0].projectId,1);assert.equal(db().people.length,5);
preview('دو میلیون تومان بابت جوشکاری در پروژه ارشام دیروز پرداخت شد');assert.equal(d.getElementById('spParty').value,'');assert.ok(d.querySelector('#paymentPersonChoices [data-payment-person="20"]'));assert.ok(d.querySelector('#paymentPersonChoices [data-payment-person="21"]'));assert.equal(d.querySelector('#paymentPersonChoices [data-payment-person="22"]'),null);click('[data-payment-person="21"]');w.confirmSmartPlan();assert.equal(db().transactions[1].personId,21);assert.equal(db().transactions[1].amount,2000000);
preview('سه میلیون تومان بابت جوشکاری در پروژه ارشام پرداخت شد');w.confirmSmartPlan();assert.equal(db().transactions.length,3);let unresolved=JSON.parse(JSON.stringify(db().transactions[2]));assert.equal(unresolved.personId,null);assert.equal(unresolved.partyStatus,'unresolved');assert.equal(w.transactionPersonMatch(unresolved,{id:999,name:'طرف حساب نامشخص'}),false);assert.equal(db().people.length,5);assert.ok(w.completionOpen().some(t=>t.type==='transaction.party'&&t.entityId===unresolved.id));
let saved=w.localStorage.getItem(storage);w.close();w=boot(saved);d=w.document;assert.equal(db().transactions[2].partyStatus,'unresolved');const task=w.completionOpen().find(t=>t.type==='transaction.party');w.completionAction(task.id);d.getElementById('paymentCompletionPerson').value='20';w.savePaymentPartyCompletion(unresolved.id);assert.equal(db().transactions.length,3);const completed=db().transactions[2];assert.equal(completed.personId,20);assert.equal(completed.contractorId,20);for(const key of ['id','amount','date','projectId','category','note'])assert.equal(completed[key],unresolved[key]);assert.equal(w.completionOpen().filter(t=>t.type==='transaction.party').length,0);assert.equal(w.PeymanyarStatements.account(20,'ارشام').paid,3000000);
preview('یک میلیون تومان به علی بابت نگهبانی در پروژه ارشام پرداخت شد');assert.equal(d.getElementById('spParty').value,'علی');w.confirmSmartPlan();assert.equal(db().transactions[3].personId,11);
preview('یک میلیون تومان بابت نگهبانی در پروژه ارشام پرداخت شد');d.getElementById('spProject').value='دیگر';d.getElementById('spProject').dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(d.getElementById('spParty').value,'علی');assert.equal(w.v21Plan.pickPersonId,11);click('[data-payment-defer]');assert.equal(d.getElementById('spParty').value,'');w.confirmSmartPlan();assert.equal(db().transactions[4].personId,null);assert.equal(db().transactions[4].projectId,3);
// Two identical names are selected by ID, never by array order.
db().people.push({id:30,name:'علی',role:'نگهبان',project:'ارشام'});preview('یک میلیون تومان به علی در پروژه ارشام پرداخت شد');click('[data-payment-person="30"]');w.confirmSmartPlan();assert.equal(db().transactions[5].personId,30);assert.equal(db().people.length,6);
// Deferred cheques remain a single project payment and retain cheque metadata on completion.
preview('چهار میلیون تومان بابت جوشکاری در پروژه ارشام به صورت چک پرداخت شد');click('[data-payment-defer]');for(const [id,val] of Object.entries({spChequeNumber:'901',spChequeBank:'ملت',spChequeDue:'1405/08/01'}))d.getElementById(id).value=val;w.confirmSmartPlan();let cheque=db().transactions[6];assert.equal(cheque.personId,null);assert.equal(cheque.paymentMethod,'cheque');assert.equal(cheque.chequeStatus,'delivered');w.openPaymentPartyCompletion(cheque.id);d.getElementById('paymentCompletionPerson').value='21';w.savePaymentPartyCompletion(cheque.id);assert.equal(db().transactions.length,7);assert.equal(db().transactions[6].chequeNumber,'901');assert.equal(db().transactions[6].personId,21);
// Failed storage rolls back both payment and completion task.
preview('یک میلیون تومان بابت جوشکاری در پروژه ارشام پرداخت شد');const before=JSON.stringify(db()),save=w.save;w.save=()=>{throw Error('quota')};w.confirmSmartPlan();assert.equal(JSON.stringify(db()),before);w.save=save;
w.close();console.log('PASS: role/project proposals, unique local auto-selection, multiple specialists, exact ID choices, explicit person priority, project change, deferred bank/cheque save, completion without extra payment, reload and quota rollback');
