const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require(process.env.LEDGER_JSDOM||'../../voice-test-runtime/node_modules/jsdom');
const root=path.join(__dirname,'..'),storage='peymanyar-v1-data';
function boot(saved){
 const errors=[],console=new VirtualConsole();console.on('jsdomError',e=>errors.push(e));
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
 const w=new JSDOM(html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,''),{url:'https://alvandi111.github.io/mehdi/',runScripts:'dangerously',virtualConsole:console}).window;
 w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.scrollTo=()=>{};w.confirm=()=>true;w.alert=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});w.fetch=async()=>{throw Error('offline test')};
 if(saved)w.localStorage.setItem(storage,saved);
 // All app scripts in the deployed order. The network SDK is not used in this local ledger test.
 for(const m of html.matchAll(/<script src="([^?\"]+)/g)){const file=m[1];if(file.startsWith('vendor/'))continue;const s=w.document.createElement('script');s.textContent=fs.readFileSync(path.join(root,file),'utf8');w.document.body.append(s)}
 assert.deepEqual(errors,[]);return w;
}
(async()=>{
const w=boot(),d=w.document,cal=w.PeymanyarCalendar;const host=d.createElement('section');d.body.append(host);
host.innerHTML=`<div class="field"><label>تاریخ ثبت</label><input id="explicitDate" data-persian-calendar="1" value="۱۴۰۵/۰۷/۱۶"></div><div class="field"><label>سررسید چک</label><input id="blankDue" data-persian-calendar="1" onclick="PeymanyarCalendar.open(this)"></div><div class="field"><label>تاریخ شروع</label><input id="startDate" value="1405/01/01"></div><div class="field"><label>مبلغ</label><input id="amount" value="1000000"></div><div class="field"><label>روز تحویل</label><input id="legacy" value="1405/07/16"></div><div class="field"><label>موعد برگشت</label><input id="rental" value="1405/07/16"></div>`;
cal.scan();assert.equal(host.querySelectorAll('.pc-controls').length,5);cal.scan();assert.equal(host.querySelectorAll('.pc-controls').length,5);const input=d.getElementById('explicitDate'),bar=input.nextElementSibling;assert.equal(bar.querySelectorAll('button').length,3);let events=[];input.addEventListener('input',()=>events.push('input'));input.addEventListener('change',()=>events.push('change'));bar.querySelector('.pc-previous').click();assert.equal(input.value,'1405/07/15');assert.deepEqual(events,['input','change']);bar.querySelector('.pc-next').click();assert.equal(input.value,'1405/07/16');assert.equal(d.querySelector('.pc-overlay'),null);input.click();assert.equal(d.querySelector('.pc-overlay'),null);
input.value='۱۴۰۰/۰۷/۱۶';bar.querySelector('.pc-previous').click();assert.equal(input.value,'1400/07/15');bar.querySelector('.pc-trigger').click();assert.ok(d.querySelector('.pc-current').textContent.includes('۱۴۰۰'));assert.ok(d.querySelector('.pc-selected').getAttribute('aria-label').includes('۱۵ مهر'));const day=[...d.querySelectorAll('.pc-day')].find(b=>b.getAttribute('aria-label').startsWith('۱۴ مهر'));day.click();assert.equal(input.value,'1400/07/14');assert.equal(d.querySelector('.pc-overlay'),null);
for(const [value,delta,expected] of [['1405/06/31',1,'1405/07/01'],['1405/07/01',-1,'1405/06/31'],['1403/12/29',1,'1403/12/30'],['1403/12/30',1,'1404/01/01'],['1404/01/01',-1,'1403/12/30'],['1404/12/29',1,'1405/01/01'],['١٤٠٥/٠٧/١٦',-1,'1405/07/15']]){input.value=value;cal.step(input,delta);assert.equal(input.value,expected)}
input.value='1300/01/01';cal.step(input,-1);assert.equal(input.value,'1300/01/01');input.value='1404/12/30';cal.step(input,-1);assert.equal(input.value,'1404/12/30');assert.ok(d.querySelector('.pc-overlay'));d.querySelector('.pc-overlay').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));const blank=d.getElementById('blankDue');blank.nextElementSibling.querySelector('.pc-previous').click();assert.equal(blank.value,'');assert.ok(d.querySelector('.pc-overlay'));d.querySelector('.pc-overlay').click();assert.equal(blank.value,'');assert.equal(blank.getAttribute('onclick'),null);
input.value='1405/07/16';input.disabled=true;cal.scan();assert.ok([...bar.querySelectorAll('button')].every(b=>b.disabled));cal.step(input,-1);assert.equal(input.value,'1405/07/16');input.disabled=false;input.readOnly=true;cal.scan();cal.step(input,1);assert.equal(input.value,'1405/07/16');input.readOnly=false;cal.scan();assert.ok([...bar.querySelectorAll('button')].every(b=>!b.disabled));
const late=d.createElement('div');late.className='field';late.innerHTML='<label>تاریخ</label><input id="newDate" data-persian-calendar="1" value="1405/07/16">';host.append(late);await new Promise(r=>setTimeout(r,10));assert.equal(late.querySelectorAll('.pc-controls').length,1);cal.scan();assert.equal(late.querySelectorAll('.pc-controls').length,1);late.replaceChildren();late.innerHTML='<label>تاریخ</label><input id="newDate" data-persian-calendar="1" value="1405/07/16">';await new Promise(r=>setTimeout(r,10));assert.equal(late.querySelectorAll('.pc-controls').length,1);
// Real production modal fields, including fields explicitly tagged before enhancement.
w.openInventoryEntry();await new Promise(r=>setTimeout(r,10));for(const id of ['invDate','invRentalDue'])assert.ok(d.getElementById(id).nextElementSibling.classList.contains('pc-controls'));d.getElementById('invDate').value='1405/07/16';d.getElementById('invDate').nextElementSibling.querySelector('.pc-previous').click();assert.equal(d.getElementById('invDate').value,'1405/07/15');w.closeInventoryEntry();
w.openQuick();d.getElementById('quickText').value='یک میلیون تومان بابت نگهبانی یاسر در پروژه آرشام پرداخت شد';w.parseQuick();await new Promise(r=>setTimeout(r,10));for(const id of ['spDate','spChequeDue'])assert.ok(d.getElementById(id).nextElementSibling.classList.contains('pc-controls'));assert.equal(d.getElementById('spChequeDue').value,'');
console.log('PASS: deployed script order; explicitly marked dates enhanced; all date/due/return fields; current-date relative arrows; typed input stays usable; picker selected date; Persian/Arabic digits; month/year/leap rollover; blank optional dates unchanged; disabled/read-only respected; input/change events; dynamic forms and replacement without duplicate controls; actual warehouse and cheque previews');w.close();
})().catch(e=>{console.error(e);process.exitCode=1});
