const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require(process.env.LEDGER_JSDOM||'../../voice-test-runtime/node_modules/jsdom');
const root=path.join(__dirname,'..'),storage='peymanyar-v1-data';
function boot(saved){
 const errors=[],console=new VirtualConsole();console.on('jsdomError',e=>errors.push(e));
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
 const w=new JSDOM(html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,''),{url:'https://alvandi111.github.io/mehdi/',runScripts:'dangerously',virtualConsole:console}).window;
 w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.scrollTo=()=>{};w.confirm=()=>true;w.alert=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});w.fetch=async()=>{throw Error('offline test')};
 if(saved)w.localStorage.setItem(storage,saved);
 // All app scripts in the deployed order. The network SDK is not used in this local ledger test.
 for(const m of html.matchAll(/<script src="([^?\"]+)/g)){const file=m[1];if(file.startsWith('vendor/'))continue;const s=w.document.createElement('script');s.textContent=fs.readFileSync(path.join(root,file),'utf8');w.document.body.append(s)}
 assert.deepEqual(errors,[]);return w;
}
const initial={projects:[{id:1,name:'آرشام',aliases:['ارشام'],client:'کارفرما',status:'فعال'},{id:2,name:'حسن‌وند',client:'دیگر'}],people:[{id:10,name:'یاسر',role:'نگهبان',project:'آرشام'},{id:11,name:'ملکی',role:'جوشکار',project:'آرشام'},{id:12,name:'خارج پروژه',role:'بنا',project:'حسن‌وند'}],transactions:[{id:20,projectId:1,project:'آرشام',amount:1000,kind:'income',date:'1405/07/01'},{id:21,projectId:1,project:'ارشام',personId:10,party:'یاسر',amount:300,kind:'expense',date:'1405/07/02'},{id:22,projectId:1,project:'آرشام',personId:11,party:'ملکی',amount:200,kind:'expense',fundingSource:'client-direct',date:'1405/07/03'},{id:23,projectId:2,project:'حسن‌وند',amount:99999,kind:'expense',date:'1405/07/01'}],documents:[{id:30,projectId:1,project:'آرشام',name:'عکس پروژه',type:'image/jpeg'},{id:31,projectId:2,project:'حسن‌وند',name:'عکس دیگر',type:'image/jpeg'}],daily:[{id:40,projectId:1,project:'آرشام',date:'1405/07/01',text:'گزارش آرشام'},{id:41,projectId:2,project:'حسن‌وند',date:'1405/07/01',text:'گزارش دیگر'}],contracts:[{id:50,projectId:1,project:'آرشام',title:'قرارداد ملکی',party:'ملکی',amount:500}],workStatements:[{id:60,projectId:1,project:'آرشام',personId:11,party:'ملکی',title:'صورت اول',status:'approved',date:'1405/07/01',items:[{quantity:2,rate:500}]}]};
(async()=>{const w=boot(JSON.stringify(initial)),d=w.document,before=JSON.stringify(w.eval('db'));w.openProject(1);const app=d.getElementById('app');assert.equal(app.querySelector('[data-project-view]').dataset.projectView,'overview');assert.equal(app.querySelector('.project-hub-header h1').textContent,'آرشام');assert.equal(app.querySelectorAll('.project-hub-tile').length,9);assert.ok(app.querySelector('[data-project-section=inventory]'));assert.equal(app.querySelector('.ledger-panel'),null);assert.equal(app.querySelector('.ledger-extras'),null);const cells=app.querySelector('.project-hub-summary tbody tr').children;assert.equal(cells[0].textContent,w.eval('fa(1200)'));assert.equal(cells[1].textContent,w.eval('fa(500)'));assert.equal(cells[2].textContent,w.eval('fa(700)'));
app.querySelector('[data-project-section=inventory]').click();assert.ok(d.getElementById('inventoryHub').textContent.includes('انبار آرشام'));assert.equal(d.getElementById('inventoryProject').value,'1');d.getElementById('inventoryHub').remove();
w.openProjectSection(1,'finance');assert.equal(app.querySelector('[data-project-view]').dataset.projectView,'finance');assert.ok(app.querySelector('.ledger-panel'));assert.equal(app.querySelector('.ledger-extras'),null);assert.equal(app.querySelectorAll('.ledger-table tbody tr').length,3);assert.ok(!app.textContent.includes('۹۹٬۹۹۹'));assert.equal(w.eval('activeReport.rows.length'),3);assert.equal(w.eval('activeReport.project'),'آرشام');assert.equal(app.querySelectorAll('#ledgerFrom').length,1);
w.openProjectSection(1,'people');assert.ok(app.textContent.includes('یاسر'));assert.ok(!app.textContent.includes('ملکی'));w.openProjectSection(1,'contractors');assert.ok(app.textContent.includes('ملکی'));assert.ok(!app.textContent.includes('خارج پروژه'));w.openProjectSection(1,'statements');assert.ok(app.textContent.includes('صورت اول'));assert.ok(app.querySelector('[onclick^="deleteWorkStatement"]'));w.openProjectSection(1,'photos');assert.ok(app.textContent.includes('عکس پروژه'));assert.ok(!app.textContent.includes('عکس دیگر'));w.openProjectSection(1,'daily');assert.ok(app.textContent.includes('گزارش آرشام'));assert.ok(!app.textContent.includes('گزارش دیگر'));w.openProjectSection(1,'contracts');assert.ok(app.textContent.includes('قرارداد ملکی'));w.openProjectSection(1,'settings');assert.ok(app.textContent.includes('ادغام پروژه‌ها'));assert.ok(app.textContent.includes('ویرایش مشخصات'));
w.openProject(2);assert.equal(app.querySelector('[data-project-view]').dataset.projectView,'overview');assert.equal(app.querySelector('.project-hub-header h1').textContent,'حسن‌وند');w.openProjectEntry('person',2);assert.equal(d.getElementById('fProject').value,'حسن‌وند');d.getElementById('modal').remove();assert.equal(JSON.stringify(w.eval('db')),before);
console.log('PASS: production project landing; clear inventory tile; compact financial table with direct payments; scoped ledger/exports and aliases; separate people/contractors/statements/photos/reports/contracts/settings; navigation resets; new forms preselect project; no data or financial changes');w.close()})().catch(e=>{console.error(e);process.exitCode=1});
