const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {JSDOM}=require('../../voice-test-runtime/node_modules/jsdom');
const w=new JSDOM('<div id="app"></div><div id="toast"></div>',{url:'https://alvandi111.github.io/mehdi/',runScripts:'dangerously'}).window;
w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.scrollTo=()=>{};w.confirm=()=>true;w.alert=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});
for(const f of ['workspace-engine.js','collaboration-engine.js','command-engine.js','contract-engine.js','receipt-date.js','app.js','entity-editor.js','financial-ledger.js','persian-calendar.js','entity-delete.js','work-statements.js','project-funding.js']){const s=w.document.createElement('script');s.textContent=fs.readFileSync(path.join(__dirname,'..',f),'utf8');w.document.body.append(s)}
Object.assign(w.eval('db'),{projects:[{id:1,name:'آرشام',client:'نصیری',managementFeePercent:15},{id:2,name:'امامی',managementFeePercent:20}],people:[{id:10,name:'آهن فروش'}],transactions:[{id:1,kind:'income',project:'آرشام',party:'نصیری',amount:100000000,date:'1405/07/01'},{id:2,kind:'expense',project:'آرشام',amount:40000000,date:'1405/07/02'},{id:3,kind:'expense',project:'آرشام',party:'آهن فروش',personId:10,amount:60000000,date:'1405/07/03',fundingSource:'client-direct',fundingClient:'نصیری'},{id:4,kind:'expense',project:'آرشام',amount:5000000,date:'1405/07/04',managementFeeEligible:false},{id:5,kind:'expense',project:'امامی',amount:20000000,date:'1405/07/01'}],contracts:[],documents:[],workStatements:[],daily:[],completionTasks:[]});
const api=w.PeymanyarFunding,d=w.document,set=(id,value)=>d.getElementById(id).value=value;
let s=api.projectSummary(1);assert.equal(s.received,100000000);assert.equal(s.paid,105000000);assert.equal(s.cashPaid,45000000);assert.equal(s.directPaid,60000000);assert.equal(s.cashBalance,55000000);assert.equal(s.base,100000000);assert.equal(s.fee,15000000);assert.equal(s.funded,160000000);assert.equal(api.projectSummary(2).fee,4000000);assert.equal(api.projectSummary(1,'1405/07/02').fee,6000000);assert.equal(w.PeymanyarStatements.account(10,'آرشام').paid,60000000);
w.openProject(1);assert.ok(d.querySelector('.project-funding-panel'));assert.match(d.querySelector('.ledger-panel').textContent,/تراز گردش مدیر/);assert.match(d.querySelector('.ledger-table').textContent,/خارج از حساب مدیر/);w.exportActiveCSV=()=>{};
w.openProjectFee(1);set('pfRate','۱۲٫۵');w.saveProjectFee(1);assert.equal(api.projectSummary(1).fee,12500000);assert.equal(w.eval('db').transactions.length,5);
// Correct an old mislabeled receipt in place, keeping the attachment and stable ID.
w.eval('db').transactions.push({id:6,kind:'income',project:'آرشام',party:'نصیری',amount:30000000,date:'1405/07/05',documentId:99});w.eval('db').documents.push({id:99,name:'رسید آهن'});
w.openClientDirectPayment('',6);set('pfParty','آهن فروش');set('pfClient','نصیری');set('pfSource','client-direct');w.confirm=()=>false;w.saveClientDirectPayment(6);assert.equal(w.eval('db').transactions.at(-1).kind,'income');w.confirm=()=>true;w.saveClientDirectPayment(6);assert.equal(w.eval('db').transactions.length,6);assert.equal(w.eval('db').transactions.at(-1).documentId,99);assert.equal(w.eval('db').documents[0].party,'آهن فروش');assert.equal(api.projectSummary(1).received,100000000);assert.equal(api.projectSummary(1).directPaid,90000000);assert.equal(api.projectSummary(1).fee,16250000);
w.openRecordEditor('transaction',6);assert.ok(d.getElementById('pfSource'));set('pfSource','manager');w.saveClientDirectPayment(6);assert.equal(api.projectSummary(1).directPaid,60000000);assert.equal(api.projectSummary(1).fee,16250000);
w.openClientDirectPayment('آرشام');set('pfParty','آهن فروش');set('pfClient','نصیری');set('pfAmount','۱٬۰۰۰٬۰۰۰');set('pfDate','1405/07/06');const before=JSON.stringify(w.eval('db')),save=w.save;w.save=()=>{throw Error('quota')};w.saveClientDirectPayment();assert.equal(JSON.stringify(w.eval('db')),before);w.save=save;
assert.ok(JSON.parse(w.localStorage.getItem('peymanyar-v1-data')).transactions.some(t=>t.fundingSource==='client-direct'));
console.log('PASS: direct client payments excluded from manager cash; one expense and contractor settlement; per-project fee and cutoff; exclusions; receipt correction preserves identity/document; confirmation and rollback');w.close();
