const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');const {JSDOM}=require('../../voice-test-runtime/node_modules/jsdom');const w=new JSDOM('<div id="app"></div><div id="toast"></div>',{url:'https://alvandi111.github.io/mehdi/',runScripts:'dangerously'}).window;w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.scrollTo=()=>{};w.confirm=()=>true;w.alert=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});
for(const f of ['workspace-engine.js','collaboration-engine.js','command-engine.js','contract-engine.js','receipt-date.js','app.js','daily-voice.js','persian-calendar.js','receipt-transport.js','live-dictation.js','entity-editor.js','financial-ledger.js','bulk-entry.js','receipt-editor.js']){const s=w.document.createElement('script');s.textContent=fs.readFileSync(path.join(__dirname,'..',f),'utf8');w.document.body.appendChild(s)}
const db=w.eval('db');db.projects=[{id:1,name:'آرشام',aliases:['ارشام'],status:'فعال',progress:0}];db.people=[{id:2,name:'کاظم‌پور',aliases:['کازمپور']}];db.transactions=[{id:10,documentId:20,project:'آرشام',party:'کاظم‌پور',personId:2,date:'1405/06/06',category:'خرید مصالح',amount:2000000,kind:'expense',note:'فهرست بلند قدیمی'}];db.documents=[{id:20,project:'آرشام',party:'کاظم‌پور',date:'1405/06/06',amount:2000000,category:'خرید مصالح',title:'رسید خرید',note:'فهرست بلند قدیمی',ocrText:'متن اسکن قدیمی',description:'اطلاعات اضافی',origin:'مهدی',destination:'کاظم‌پور',originBank:'بانک',tracking:'12345',docType:'رسید پرداخت',name:'receipt.jpg'}];
function set(id,value){w.document.getElementById(id).value=value}
(async()=>{
w.openRecordEditor('document',20);assert.ok(w.document.getElementById('reOrigin').closest('details'));set('reDate','٠٦-٠٦-١٤٠٥');set('reAmount','٢٬٠٠٠٬٠٠٠');for(const id of ['reNote','reOcrText','reDescription','reOrigin','reDestination','reTracking','reOriginBank','reDestinationBank'])set(id,'');w.saveRecordEditor('document',20);assert.equal(w.document.getElementById('recordEditor'),null);const doc=db.documents[0],tx=db.transactions[0];assert.equal(doc.date,'1405/06/06');assert.equal(doc.amount,2000000);for(const key of ['note','ocrText','description','origin','destination','tracking','originBank','destinationBank'])assert.equal(doc[key],'');assert.equal(tx.note,'');assert.equal(doc.status,'کامل');
w.openRecordEditor('transaction',10);assert.equal(w.document.getElementById('reNote').value,'');set('reDate','2026-10-04');set('reProject','ارشام');set('reParty','کازمپور');w.saveRecordEditor('transaction',10);assert.match(doc.date,/^1405\//);assert.equal(db.projects.length,1);assert.equal(db.people.length,1);assert.equal(tx.personId,2);
w.openRecordEditor('document',20);set('reDate','تاریخ نامشخص');set('reCategory','');set('reNote','');w.saveRecordEditor('document',20);assert.equal(doc.date,'');assert.equal(doc.rawDate,'تاریخ نامشخص');assert.equal(doc.status,'نیازمند تکمیل');assert.ok(db.completionTasks.some(t=>t.type==='document.review'&&t.entityId===20));w.openRecordEditor('document',20);assert.equal(w.document.getElementById('reDate').value,'تاریخ نامشخص');w.document.getElementById('recordEditor').remove();
w.storeFile=async()=>{};w.openSmartUpload('آرشام');w.eval('pendingSmartFile=new File(["image"],"receipt.jpg",{type:"image/jpeg"});smartReceiptFields={project:"پروژه اشتباه",destination:"نام اشتباه",amount:999,date:"1405/01/01",note:"متن خیلی بلند قدیمی"};smartOcrText="متن اسکن قدیمی"');set('smartProject','آرشام');set('smartDate','۶/۶/۱۴۰۵');set('smartAmount','۲۰۰۰۰۰۰');set('smartPerson','کازمپور');set('smartCategory','خرید مصالح');set('smartDocCommand','');set('smartOcrRaw','');set('smartType','رسید پرداخت');w.updateSmartQuestions();assert.ok(!w.document.getElementById('smartQuestions').textContent.includes('پروژه بعداً'));await w.saveSmartDocument();const saved=db.documents[0];assert.equal(saved.project,'آرشام');assert.equal(saved.date,'1405/06/06');assert.equal(saved.amount,2000000);assert.equal(saved.note,'');assert.equal(saved.description,'');assert.equal(saved.ocrText,'');assert.equal(saved.party,'کاظم‌پور');assert.equal(db.transactions.length,2);
w.attachTransactionDocument(10);w.eval('pendingSmartFile=new File(["image"],"linked.jpg",{type:"image/jpeg"})');await w.saveSmartDocument();assert.equal(db.transactions.length,2,'attachment must not duplicate payment');assert.equal(db.documents[0].transactionId,10);assert.equal(tx.documentId,db.documents[0].id);assert.equal(db.documents[0].amount,tx.amount);
w.openSmartUpload('آرشام');set('smartDocCommand','برای پروژه جدید به نام پروژه اشتباه بابت کرایه وانت');set('smartProject','آرشام');w.document.getElementById('smartProject').dispatchEvent(new w.Event('input',{bubbles:true}));set('smartCategory','');w.document.getElementById('smartCategory').dispatchEvent(new w.Event('input',{bubbles:true}));w.analyzeSmartDocument();assert.equal(w.document.getElementById('smartProject').value,'آرشام');assert.equal(w.document.getElementById('smartCategory').value,'');
console.log('PASS: editable OCR clearing, optional bank fields, Arabic/Persian/date-order/Gregorian parsing, incomplete metadata edits preserved, no OCR resurrection on save, canonical aliases, linked attachment without duplicate payment, manual edits protected from reanalysis');w.close();
})().catch(e=>{console.error(e.stack||e);w.close();process.exitCode=1});
