const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require(process.env.LEDGER_JSDOM||'../../voice-test-runtime/node_modules/jsdom');
const root=path.join(__dirname,'..'),storage='peymanyar-v1-data';
function boot(saved){
 const errors=[],console=new VirtualConsole();console.on('jsdomError',e=>errors.push(e));
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
 const w=new JSDOM(html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,''),{url:'https://alvandi111.github.io/mehdi/',runScripts:'dangerously',virtualConsole:console}).window;
 w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.scrollTo=()=>{};w.confirm=()=>true;w.alert=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});w.fetch=async()=>{throw Error('offline test')};
 if(saved)w.localStorage.setItem(storage,saved);
 // All app scripts in the deployed order. The network SDK is not used in this local ledger test.
 for(const m of html.matchAll(/<script src="([^?\"]+)/g)){const file=m[1];if(file.startsWith('vendor/'))continue;const s=w.document.createElement('script');s.textContent=fs.readFileSync(path.join(root,file),'utf8');w.document.body.append(s)}
 assert.deepEqual(errors,[]);return w;
}

const initial={projects:[{id:1,name:'آرشام',aliases:['ارشام']},{id:2,name:'بیمارستان ۲۶۰'}],people:[],transactions:[{id:1,amount:99}],documents:[],contracts:[],daily:[]};
(async()=>{let w=boot(JSON.stringify(initial)),d=w.document;const value=(id,x)=>d.getElementById(id).value=x;let files=new Map();w.storeFile=async(id,file)=>files.set(id,file);w.URL.createObjectURL=()=> 'blob:fixture';w.URL.revokeObjectURL=()=>{};
w.openSecretariat();w.openCorrespondence('outgoing');value('secTitle','قیمت کابینت بیمارستان');value('secCase','بیمارستان شصت');value('secTags','بیمارستان ۲۶۰، کابینت هایگلس');value('secRecipient','مدیریت بیمارستان');value('secDate','1405/07/17');value('secBody','با سلام و احترام، پیشنهاد قیمت ارسال می‌شود.');await w.saveCorrespondence(false);assert.equal(w.eval('db.correspondence.length'),1);let r=w.eval('db.correspondence[0]');assert.equal(r.projectId,null);assert.equal(r.number,undefined);const id=r.id;assert.equal(w.PeymanyarSecretariat.find('بیمارستان 260').length,1);assert.equal(w.PeymanyarSecretariat.find('شصت').length,1);
w.openCorrespondence('outgoing',id);await w.saveCorrespondence(true);r=w.eval('db.correspondence[0]');assert.equal(r.number,'1405/0001');assert.equal(r.status,'final');w.openCorrespondence('outgoing',id);assert.equal(d.querySelector('#secEditor fieldset').disabled,true);value('secProject','2');value('secTags','بیمارستان شصت، 260');await w.saveCorrespondence(false);assert.equal(w.eval('db.correspondence[0].number'),'1405/0001');assert.equal(w.eval('db.correspondence[0].projectId'),'2');w.openSecretariat(2);assert.equal(w.PeymanyarSecretariat.find('شصت').length,1);
await w.voidCorrespondence(id);assert.equal(w.eval('db.correspondence[0].status'),'void');w.openCorrespondence('quote');value('secTitle','پیش‌فاکتور کابینت');value('secRecipient','مشتری نمونه');value('secDate','1405/07/17');d.querySelector('.sec-description').value='کابینت هایگلس';d.querySelector('.sec-qty').value='۲٫۵';d.querySelector('.sec-rate').value='۱۰٬۰۰۰٬۰۰۰';value('secTerms','۷۰ درصد پیش‌پرداخت؛ الباقی هنگام تحویل');await w.saveCorrespondence(true);assert.equal(w.eval('db.correspondence.length'),2);r=w.eval('db.correspondence[0]');assert.equal(r.number,'1405/0002');assert.equal(w.PeymanyarSecretariat.total(r.items,true),25000000);assert.equal(w.eval('db.transactions.length'),1);const quoteId=r.id;w.reviseCorrespondence(quoteId);assert.equal(d.getElementById('secReference').value,'1405/0002');await w.saveCorrespondence(false);assert.equal(w.eval('db.correspondence.length'),3);assert.equal(w.eval('db.correspondence[0].number'),undefined);
// Persistence and optional linking do not change IDs or ledger entries.
const saved=w.localStorage.getItem(storage);w.close();w=boot(saved);d=w.document;w.storeFile=async()=>{};w.openSecretariat();assert.equal(w.PeymanyarSecretariat.find('1405/0002').length,1);assert.equal(w.eval('db.correspondence.length'),3);w.openCorrespondence('incoming');value('secTitle','نامه تأخیر');value('secDate','1405/07/17');value('secExternal','۲۶۰/۱۷');value('secBody','متن نامه وارده');await w.saveCorrespondence(true);assert.equal(w.eval('db.correspondence[0].number'),'1405/0003');assert.equal(w.eval('db.correspondence[0].externalNumber'),'۲۶۰/۱۷');
// AI suggestions require acceptance and preserve the raw wording on the saved report.
w.openQuick();value('quickText','گزارش پروژه آرشام امروز هفت تا کارگر داشتیم');w.parseQuick();w.fetch=async()=>({ok:true,json:async()=>({text:'امروز در پروژه آرشام هفت کارگر حضور داشتند.',warnings:[],model:'test'})});await w.professionalRewrite('irText');assert.ok(d.getElementById('irText').value.includes('داشتیم'));w.applyWritingReview();assert.ok(d.getElementById('irText').value.includes('حضور'));await w.saveRoutedCommand(false);assert.equal(w.eval('db.daily.length'),1);assert.ok(w.eval('db.daily[0].originalText').includes('داشتیم'));assert.equal(w.eval('db.daily[0].projectId'),1);
// Service unavailable does not replace text; stale proposal never overwrites an edit.
w.openDailyEditor(w.eval('db.daily[0].id'));w.fetch=async()=>({ok:false,status:404});const original=d.getElementById('deText').value;await w.professionalRewrite('deText');assert.match(d.getElementById('writingStatus').textContent,/هنوز فعال نیست/);assert.equal(d.getElementById('deText').value,original);w.closeWritingReview();w.fetch=async()=>({ok:true,json:async()=>({text:'متن پیشنهاد',warnings:[]})});await w.professionalRewrite('deText');value('deText','ویرایش دستی');w.applyWritingReview();assert.equal(d.getElementById('deText').value,'ویرایش دستی');w.closeWritingReview();d.getElementById('dailyEditor').remove();
// Failed persistence leaves the archive and number untouched.
w.openCorrespondence('outgoing');value('secTitle','ذخیره ناموفق');value('secRecipient','نمونه');value('secDate','1405/07/17');value('secBody','متن');const before=w.eval('db.correspondence.length');const proto=Object.getPrototypeOf(w.localStorage),real=proto.setItem;proto.setItem=function(){throw Error('quota')};await w.saveCorrespondence(true);assert.equal(w.eval('db.correspondence.length'),before);assert.ok(d.getElementById('secEditor'));proto.setItem=real;await w.saveCorrespondence(true);assert.equal(w.eval('db.correspondence[0].number'),'1405/0004');assert.equal(w.eval('db.transactions[0].amount'),99);w.close();console.log('PASS: no-project archive, Persian keyword/numeric search, stable linking, immutable final/void numbers, quote totals, revision draft, incoming numbering, reload, AI acceptance/original preservation, unavailable/stale AI protection, quota rollback and unchanged ledger');})().catch(e=>{console.error(e);process.exitCode=1});
