const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'../live-dictation.js'),'utf8');
function setup(mode='browser') {
 const nodes={},overlays=[];let stopped=0,parsed=0;
 class Node {constructor(){this.isConnected=true;this.dataset={};this.style={};this.value='';this.children={};this.hidden=false}setAttribute(k,v){this[k]=v}focus(){doc.activeElement=this}remove(){this.isConnected=false}querySelector(k){return this.children[k]??=new Node()}querySelectorAll(){return Object.values(this.children)}}
 const input=nodes.quickText=new Node();input.value='برای پروژه آرشام';nodes.app=new Node();
 const doc={activeElement:null,body:new Node(),hidden:false,getElementById:id=>nodes[id]||null,querySelectorAll:q=>q.startsWith('[data-')?[]:q.includes('quickText')?[input]:[],createElement:()=>new Node(),addEventListener(){}};
 doc.body.append=n=>overlays.push(n);
 class Audio{constructor(){this.sampleRate=16000;this.state='running';context.audio=this}createMediaStreamSource(){return{connect(){},disconnect(){}}}createScriptProcessor(){return context.processor={connect(){},disconnect(){}}}close(){this.state='closed';return Promise.resolve()}}
 class Recognition{constructor(){context.recognition=this}start(){this.onstart?.()}stop(){this.onend?.()}abort(){}}
 const context={document:doc,navigator:{mediaDevices:{getUserMedia:async()=>{if(mode==='denied')throw Object.assign(new Error(),{name:'NotAllowedError'});return{getTracks:()=>[{stop(){stopped++}}]}}}},AudioContext:Audio,SpeechRecognition:mode==='browser'?Recognition:undefined,MutationObserver:class{observe(){}},assistantPanel:()=>'<old>',dashboard:()=>'<main class="phone-content"></main>',startVoice(){},parseQuick(){parsed++},confirmSmartPlan(){},setVoiceState:m=>context.lastStatus=m,toast:m=>context.toast=m,render:()=>context.panel=context.assistantPanel(),aiVoiceSending:false,pcmVoiceRecording:false,dailyVoiceSession:null,bulkVoiceSession:null,clearTimeout,clearInterval,setTimeout,setInterval,Date,Map,Object,Float32Array,Promise,confirm:()=>true,addEventListener(){},fa:s=>s,voiceServiceError:e=>e.message,mergePcmChunks:chunks=>chunks[0]||new Float32Array(),downsamplePcm:x=>x,pcmToWav:x=>x,transcribeBulkPart:async()=> 'خرید ماسه دو میلیون تومان'};context.window=context;vm.createContext(context);vm.runInContext(source,context);
 return {context,input,overlays,get stopped(){return stopped},get parsed(){return parsed}};
}
const tick=()=>new Promise(r=>setImmediate(r));
function feed(t,length=8000){t.context.processor.onaudioprocess({outputBuffer:{getChannelData:()=>new Float32Array(length)},inputBuffer:{getChannelData:()=>new Float32Array(length).fill(.2)}})}
(async()=>{
 const t=setup();t.context.mergePcmChunks=chunks=>{const result=new Float32Array(chunks.reduce((n,c)=>n+c.length,0));let offset=0;for(const c of chunks){result.set(c,offset);offset+=c.length}return result};let received,resolve;t.context.transcribeBulkPart=blob=>{received=blob;return new Promise(r=>resolve=r)};
 await t.context.startVoice();feed(t);feed(t);const overlay=t.overlays[0];assert.equal(t.context.recognition,undefined);assert.doesNotMatch(overlay.querySelector('.voice-caption').textContent,/مرورگر/);assert.equal(t.input.value,'برای پروژه آرشام');
 overlay.querySelector('.voice-main-button').onclick();assert.equal(t.stopped,1);assert.equal(overlay.isConnected,true);await tick();assert.equal(received.length,16000);assert.equal(t.input.value,'برای پروژه آرشام');
 resolve('امروز مبلغ دو میلیون و پانصد هزار تومان به ترکاشوند بابت پروژه امامی پرداخت شد');await tick();assert.equal(overlay.isConnected,false);assert.doesNotMatch(t.input.value,/PYM/);assert.match(t.input.value,/پانصد هزار/);assert.equal(t.parsed,0);assert.equal(t.input.readOnly,false);
 const routed=setup();routed.context.PeymanyarIntents={};await routed.context.startVoice();feed(routed);routed.overlays[0].querySelector('.voice-main-button').onclick();await tick();assert.equal(routed.parsed,1);assert.ok(routed.input._voiceBlob);
 const s=setup();let attempts=0,firstBlob;s.context.transcribeBulkPart=async blob=>{if(++attempts===1){firstBlob=blob;throw new Error('network')}assert.equal(blob,firstBlob);return 'مبلغ دو میلیون و پانصد هزار تومان'};await s.context.startVoice();feed(s);assert.equal(s.context.recognition,undefined);const o=s.overlays[0];o.querySelector('.voice-main-button').onclick();await tick();assert.equal(s.stopped,1);assert.equal(o.querySelector('.voice-retry').hidden,false);assert.equal(o.isConnected,true);assert.match(o.querySelector('.voice-caption').textContent,/network/);assert.equal(s.input.value,'برای پروژه آرشام');o.querySelector('.voice-retry').onclick();await tick();assert.equal(o.isConnected,false);assert.match(s.input.value,/پانصد هزار/);assert.equal(s.parsed,0);
 const limited=setup();const timers=new Map();let timerId=0,calls=0;limited.context.setInterval=(fn,ms)=>{assert.equal(ms,1000);timers.set(++timerId,fn);return timerId};limited.context.clearInterval=id=>timers.delete(id);limited.context.transcribeBulkPart=async()=>{calls++;if(calls===1)throw new Error('HTTP 429');return 'صدای حفظ شده'};await limited.context.startVoice();feed(limited);assert.equal(calls,0);limited.overlays[0].querySelector('.voice-main-button').onclick();await tick();assert.equal(calls,1);limited.overlays[0].querySelector('.voice-retry').onclick();await tick();assert.equal(calls,1);for(let i=0;i<30;i++)for(const fn of [...timers.values()])fn();await tick();assert.equal(calls,2);assert.match(limited.input.value,/حفظ شده/);assert.equal(timers.size,0);
 const cancelled=setup();let retryTick;cancelled.context.setInterval=fn=>{retryTick=fn;return 1};cancelled.context.clearInterval=()=>{};let cancelCalls=0;cancelled.context.transcribeBulkPart=async()=>{cancelCalls++;throw new Error('429')};await cancelled.context.startVoice();feed(cancelled);cancelled.overlays[0].querySelector('.voice-main-button').onclick();await tick();cancelled.overlays[0].querySelector('.voice-close').onclick();for(let i=0;i<30;i++)retryTick();await tick();assert.equal(cancelCalls,1);
 const fallback=setup('server');await fallback.context.startVoice();feed(fallback);fallback.overlays[0].querySelector('.voice-main-button').onclick();await tick();assert.match(fallback.input.value,/ماسه/);assert.equal(fallback.stopped,1);
 const empty=setup();await empty.context.startVoice();assert.equal(empty.context.recognition,undefined);empty.overlays[0].querySelector('.voice-main-button').onclick();assert.equal(empty.input.value,'برای پروژه آرشام');assert.match(empty.overlays[0].querySelector('.voice-caption').textContent,/صدای قابل/);empty.overlays[0].querySelector('.voice-close').onclick();
 const denied=setup('denied');await denied.context.startVoice();const d=denied.overlays[0];assert.equal(d.dataset.state,'stopped');assert.match(d.querySelector('.voice-caption').textContent,/اجازه/);d.querySelector('.voice-close').onclick();assert.equal(denied.input.readOnly,false);
 console.log('PASS: browser recognizer never started; full audio sent to ready ASR; final ASR awaited; microphone off during request; same audio retained for retry; server-only mode; silence and denied mic; no auto-analysis');
})().catch(e=>{console.error(e);process.exit(1)});

