const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'../live-dictation.js'),'utf8');
function setup(mode='browser') {
 const nodes={},overlays=[];let stopped=0,parsed=0;
 class Node {constructor(){this.isConnected=true;this.dataset={};this.style={};this.value='';this.children={};this.hidden=false}setAttribute(k,v){this[k]=v}focus(){doc.activeElement=this}remove(){this.isConnected=false}querySelector(k){return this.children[k]??=new Node()}querySelectorAll(){return Object.values(this.children)}}
 const input=nodes.quickText=new Node();input.value='برای پروژه آرشام';nodes.app=new Node();
 const doc={activeElement:null,body:new Node(),hidden:false,getElementById:id=>nodes[id]||null,querySelectorAll:q=>q.startsWith('[data-')?[]:q.includes('quickText')?[input]:[],createElement:()=>new Node(),addEventListener(){}};
 doc.body.append=n=>overlays.push(n);
 class Audio{constructor(){this.sampleRate=16000;this.state='running';context.audio=this}createMediaStreamSource(){return{connect(){},disconnect(){}}}createScriptProcessor(){return context.processor={connect(){},disconnect(){}}}close(){this.state='closed';return Promise.resolve()}}
 class Recognition{constructor(){context.recognition=this}start(){this.onstart?.()}stop(){this.onend?.()}abort(){}}
 const context={document:doc,navigator:{mediaDevices:{getUserMedia:async()=>{if(mode==='denied')throw Object.assign(new Error(),{name:'NotAllowedError'});return{getTracks:()=>[{stop(){stopped++}}]}}}},AudioContext:Audio,SpeechRecognition:mode==='browser'?Recognition:undefined,MutationObserver:class{observe(){}},assistantPanel:()=>'<old>',startVoice(){},parseQuick(){parsed++},confirmSmartPlan(){},setVoiceState:m=>context.lastStatus=m,toast:m=>context.toast=m,render:()=>context.panel=context.assistantPanel(),aiVoiceSending:false,pcmVoiceRecording:false,dailyVoiceSession:null,bulkVoiceSession:null,clearTimeout,clearInterval,setTimeout,setInterval,Date,Map,Object,Float32Array,Promise,confirm:()=>true,addEventListener(){},fa:s=>s,voiceServiceError:e=>e.message,mergePcmChunks:chunks=>chunks[0],downsamplePcm:x=>x,pcmToWav:x=>x,transcribeBulkPart:async()=> 'خرید ماسه دو میلیون تومان'};context.window=context;vm.createContext(context);vm.runInContext(source,context);
 return {context,input,overlays,get stopped(){return stopped},get parsed(){return parsed}};
}
const tick=()=>new Promise(r=>setImmediate(r));
(async()=>{
 const t=setup();assert.match(t.context.panel,/ضبط فرمان/);assert.doesNotMatch(t.context.panel,/old/);await t.context.startVoice();const overlay=t.overlays[0];assert.equal(overlay.dataset.state,'recording');const r=t.context.recognition;r.onresult({resultIndex:0,results:[[{transcript:'دو میلیون تومان پرداخت کردم'}]]});assert.equal(t.input.value,'برای پروژه آرشام');assert.match(overlay.querySelector('.voice-live-text').textContent,/دو میلیون/);overlay.querySelector('.voice-main-button').onclick();assert.equal(t.stopped,1);assert.equal(overlay.isConnected,false);assert.match(t.input.value,/آرشام دو میلیون/);assert.equal(t.parsed,0);assert.equal(t.input.readOnly,false);
 await t.context.startVoice();t.context.recognition.onresult({resultIndex:0,results:[[{transcript:'امروز'}]]});t.overlays[1].querySelector('.voice-main-button').onclick();assert.match(t.input.value,/امروز/);assert.equal(t.stopped,2);
 const s=setup('server');let attempts=0;s.context.transcribeBulkPart=async()=>{if(++attempts===1)throw new Error('network');return 'خرید ماسه'};await s.context.startVoice();s.context.processor.onaudioprocess({outputBuffer:{getChannelData:()=>new Float32Array(8000)},inputBuffer:{getChannelData:()=>new Float32Array(8000).fill(.2)}});const o=s.overlays[0];o.querySelector('.voice-main-button').onclick();await tick();assert.equal(s.stopped,1);assert.equal(o.querySelector('.voice-retry').hidden,false);assert.equal(o.isConnected,true);o.querySelector('.voice-retry').onclick();await tick();assert.equal(o.isConnected,false);assert.match(s.input.value,/ماسه/);assert.equal(s.parsed,0);
 const fallback=setup();await fallback.context.startVoice();fallback.context.processor.onaudioprocess({outputBuffer:{getChannelData:()=>new Float32Array(8000)},inputBuffer:{getChannelData:()=>new Float32Array(8000).fill(.2)}});fallback.context.recognition.onerror({error:'network'});await tick();fallback.overlays[0].querySelector('.voice-main-button').onclick();await tick();assert.match(fallback.input.value,/ماسه/);assert.equal(fallback.stopped,1);
 const denied=setup('denied');await denied.context.startVoice();const d=denied.overlays[0];assert.equal(d.dataset.state,'stopped');assert.match(d.querySelector('.voice-caption').textContent,/اجازه/);d.querySelector('.voice-close').onclick();assert.equal(d.isConnected,false);assert.equal(denied.input.readOnly,false);
 console.log('PASS: live preview, stop releases mic, transfer without analysis, repeat capture, server fallback, retry retains audio, denied microphone, legacy dashboard replaced');
})().catch(e=>{console.error(e);process.exit(1)});
