const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');const {JSDOM}=require('../../voice-test-runtime/node_modules/jsdom');
const w=new JSDOM('<div id="app"></div><div id="toast"></div>',{url:'https://alvandi111.github.io/mehdi/',runScripts:'dangerously'}).window;w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.scrollTo=()=>{};w.confirm=()=>true;w.alert=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});
for(const f of ['workspace-engine.js','collaboration-engine.js','command-engine.js','contract-engine.js','receipt-date.js','app.js','entity-editor.js','financial-ledger.js','persian-calendar.js','entity-delete.js','work-statements.js']){const s=w.document.createElement('script');s.textContent=fs.readFileSync(path.join(__dirname,'..',f),'utf8');w.document.body.append(s)}
Object.assign(w.eval('db'),{projects:[{id:1,name:'آرشام',status:'فعال',progress:0},{id:2,name:'امامی',status:'فعال',progress:0}],people:[{id:10,name:'احمد',role:'بنا',project:'آرشام'},{id:11,name:'دیگری'}],transactions:[{id:20,personId:10,party:'احمد',project:'آرشام',amount:5000000,date:'1405/07/01',kind:'expense'},{id:21,personId:11,party:'دیگری',project:'آرشام',amount:999,date:'1405/07/01',kind:'expense'},{id:22,personId:10,party:'احمد',project:'امامی',amount:7000000,date:'1405/07/01',kind:'expense'},{id:23,personId:10,party:'احمد',project:'آرشام',amount:1000000,date:'1405/07/05',kind:'income'}],contracts:[{id:30,party:'احمد',project:'آرشام',amount:900000000}],documents:[],daily:[],completionTasks:[],workStatements:[]});
const api=w.PeymanyarStatements,d=w.document,set=(id,v)=>d.getElementById(id).value=v;
assert.equal(api.number('۱۲٫۵'),12.5);assert.equal(api.number('۲۰۰٬۰۰۰'),200000);assert.ok(Number.isNaN(api.number('1e6')));assert.equal(api.date('1405/07/31'),'');
w.openWorkStatement(10,'آرشام');set('wsTitle','دیوارچینی');set('wsDate','1405/07/02');let tr=d.querySelector('#wsItems tbody tr');tr.querySelector('.ws-description').value='دیوارچینی';tr.querySelector('.ws-quantity').value='۱۰۰';tr.querySelector('.ws-rate').value='۲۰۰٬۰۰۰';w.addWorkStatementLine();tr=d.querySelector('#wsItems tbody tr:last-child');tr.querySelector('.ws-description').value='سیمان‌کاری';tr.querySelector('.ws-quantity').value='۱۰';tr.querySelector('.ws-rate').value='۵۰٬۰۰۰';w.saveWorkStatement();let data=w.eval('db');assert.equal(data.workStatements.length,1);const id=data.workStatements[0].id;assert.equal(api.account(10,'آرشام').earned,0);assert.equal(api.total(data.workStatements[0]),20500000);
w.openWorkStatement('','',id);set('wsStatus','approved');w.confirm=()=>false;w.saveWorkStatement();assert.equal(w.eval('db').workStatements[0].status,'draft');w.confirm=()=>true;w.saveWorkStatement();assert.equal(api.account(10,'آرشام').earned,20500000);assert.equal(api.account(10,'آرشام').balance,16500000);assert.equal(api.account(10,'آرشام','1405/07/02').balance,15500000);assert.equal(w.eval('db').workStatements.length,1);
w.openContractorPayment(10,'آرشام');set('cpAmount','۳۰۰۰۰۰۰');set('cpDate','1405/07/03');set('cpMethod','cheque');set('cpNumber','123');set('cpDue','1405/08/01');w.saveContractorPayment();const cheque=w.eval('db').transactions.at(-1).id;assert.equal(api.account(10,'آرشام').balance,13500000);assert.equal(api.account(10,'آرشام').pending,3000000);const count=w.eval('db').transactions.length;w.setContractorCheque(cheque,'cleared');assert.equal(api.account(10,'آرشام').balance,13500000);assert.equal(api.account(10,'آرشام').pending,0);assert.equal(w.eval('db').transactions.length,count);
w.openContractorPayment(10,'آرشام');set('cpAmount','1000000');set('cpDate','1405/07/03');set('cpMethod','cheque');set('cpNumber','124');set('cpDue','1405/08/01');w.saveContractorPayment();const cancelled=w.eval('db').transactions.at(-1).id;w.setContractorCheque(cancelled,'cancelled');assert.equal(api.account(10,'آرشام').balance,13500000);assert.equal(w.eval('db').transactions.at(-1).amount,0);
w.eval('db').transactions.find(t=>t.id===cancelled).chequeCancelledDate='1405/07/10';assert.equal(api.account(10,'آرشام','1405/07/04').paid,9000000);assert.equal(api.account(10,'آرشام','1405/07/10').paid,8000000);assert.ok(api.account(10,'آرشام').events.some(e=>e.title.includes('لغو تحویل چک')&&e.credit===1000000));
w.renameEntity('person',10,'اوسا احمد');assert.equal(w.eval('db').workStatements[0].party,'اوسا احمد');assert.equal(api.account(10,'آرشام').earned,20500000);w.openPerson(10);assert.match(d.querySelector('.statement-person-panel').textContent,/مانده طلب پیمانکار/);assert.ok(d.querySelector('.ledger-context .entity-delete-visible'));w.showWorkStatements(10,'آرشام');set('statementTo','1405/07/02');w.workStatementFilter();assert.match(d.getElementById('app').textContent,/۱۵٬۵۰۰٬۰۰۰/);w.openContractorAccount(10,'آرشام','1405/07/02');assert.equal(d.querySelectorAll('#contractorAccount tbody tr').length,2);
const snapshot=JSON.stringify(w.eval('db'));w.confirm=()=>false;w.deleteWorkStatement(id);assert.equal(JSON.stringify(w.eval('db')),snapshot);w.confirm=()=>true;w.deleteWorkStatement(id);assert.equal(api.account(10,'آرشام').balance,-7000000);assert.ok(w.eval('db').transactions.length>0);assert.match(JSON.parse(w.localStorage.getItem('peymanyar-v1-data')).transactions[0].party,/اوسا احمد/);
console.log('PASS: Persian/fractional quantities; draft/approved separation; item math; edit without duplicates; project/person/cutoff scoping; historical payments and refunds; contract not double-counted; cheque deducted once, clearing unchanged, cancelling reverses; rename linkage; reports and deletion');w.close();
